languagetool-org/languagetool

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java
Support embedding languagetool-core in Java EE containers that use VFS file systems for deployments. If the file protocol of the .dic and .aff files is vfs:, the Dictionary should behave similar to webstart, by moving the files to a temporary folder.
=> Support embedding languagetool-core in Java EE containers

languagetool-language-modules/ja/src/main/resources/org/languagetool/rules/ja/grammar.xml
A prolounged soud mark "ー" is placed before Katakana/Hiragana character.
This rule comes from the following discussion:
https://sourceforge.net/p/languagetool/mailman/message/34107974/
=> Bad prolonged soud mark

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AvsAnRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/AvsAnRuleTest.java
- support for A as an identifier
- issue was, that the "A" in the term "station A" has been seen as an indefinite article.
- it has been recognized before as a "A_VS_AN"-A
- added test
- cleaned up matcher
=> support usage of "A" as an identifier

languagetool-server/src/main/java/org/languagetool/server/HTTPSServer.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServer.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/Server.java
First attempt at a fix for issue #280.
This adds a new option, `rulesFile`, to the server configuration file specified with `--config`.  The `rulesFile` option points to the location of a .languagetool.cfg-style rules file.
This is a little odd (the config file now points to another config file), but my thinking was that it was better to keep the server options consolidated in the `--config` file, rather than adding a new top-level switch.  I am also allowing the `rulesFile` param to point to an arbitrary file location, since that's more convenient for server deployment scenarios where we don't want to depend on things like the location of the home directory of the "user" running the service.
I'm happy to rework any portion of this if you'd like it to work a different way.
=> Add 'rulesFile' option to config properties

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-GB/grammar.xml
New category, and two new rules to catch instances of the word 'licence' when it is used as a noun and inadvertently spelled with an 's' instead of a 'c'.
Reference for spelling usage in en-GB:
http://www.oxforddictionaries.com/definition/english/licence
http://www.grammar-monster.com/easily_confused/licence_license.htm
Thanks,
Graeme
=> New rules for 'licence' when used as a noun in en-GB.

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/Hunspell.java, languagetool-dev/src/main/java/org/languagetool/dev/eval/SimpleCorpusEvaluator.java, languagetool-language-modules/en/src/main/java/org/languagetool/chunking/EnglishChunker.java, languagetool-language-modules/ro/src/main/java/org/languagetool/synthesis/ro/RomanianSynthesizer.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2444 - Lazy initialization of "static" fields should be "synchronized"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2444
Please let me know if you have any questions.
Kirill Vlasov
=> Lazy initialization of "static" fields should be "synchronized"

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java
When using LanguageTool within an OSGi bundle, the dictionaries were failing to load. This is due to the same issues as when they are contained within a JAR file - the URI returned isn't a file URI so fails to load.
The fix here is to handle OSGi bundle loading (protocol of `bundle`) the same as JAR files. Tests out ok :ok_hand:
=> Handle OSGi bundled dictionaries to copy to temporary directories

languagetool-commandline/pom.xml, languagetool-core/pom.xml, languagetool-dev/pom.xml, languagetool-server/pom.xml, languagetool-standalone/pom.xml, languagetool-tools/pom.xml, pom.xml
Enforce [dependency convergence](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) in parent pom. Runs during `validate` phase, which is the default for the plugin.
Changes needed to get convergence passing:
- downgrade `slf4j.version` from 1.7.9 to 1.7.6 so that it lines up with dependencies
- only used for slf4j-nop, so I figured version doesn't matter
- exclude `morfologik-polish` from `morfologik-speller`
- this was a bug in morfologik that will be fixed soon, see https://github.com/morfologik/morfologik-stemming/pull/78
- pull guava, commons-lang, junit up to parent dependencyManagement to resolve most convergence issues
- add special dependencyManagement to `languagetool-dev` because there are so many more conflicts there than any other package
See …
=> Enforce DependencyConvergence in parent pom

languagetool-office-extension/src/main/assembly/oxt.xml, languagetool-wikipedia/src/main/assembly/zip.xml
"[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /third-party-licenses"
=> Removed starting slash to resolve Maven error when packaging on Windows.

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-GB/grammar.xml
These maybe more appropriate for a en-GB en-US bitext 
first floor - floor counting is different
hoover is a brand name, maybe the rule should be reversed.
=> Remove rules that are not appropriate for en-GB

languagetool-office-extension/src/main/resources/description.xml
Noticed this in a warning from LibreOffice on trying to update LanguageTool
=> fix xlink attribute

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
The short description had “esiste” instead of “existe”, which is an embarrassingly prominent typo. I detected it while using the LibreOffice extension.
=> Fix typo in a Spanish rule description

languagetool-standalone/src/main/java/org/languagetool/gui/LanguageManagerDialog.java
config can never be null here. This fixes a warning from FindBugs.
=> languagetool-standalone: Remove unneeded null check

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
I've added a new <category id="HILFESTELLUNG_KOMMASETZUNG" name="Hilefestellung für Kommasetzung">. It includes some rules to approve the commas in German texts. I've tried to develop some rules witch are as general as possible. I tested it on some large Texts of me. The rules don't find every missing comma, but wrong matches are very few.
I choose a new category because the category "PUNCTUATION" is very large and for user it is difficult to change  the Properties within. For further development I vote for moving all rules for comma placement into the new category.
I commented out the two existing rulegroups "KOMMA_VOR_INFINITIVGRUPPE" and "SUBJUNKTION_KOMMA", because they overlap with the new rules.
=> Add new Rules to German grammar.xml

languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java
- Extend the pattern rule test to make sure that the short message
(<short> in the grammar XML file), if any, is actually shorter than the
other error message (<message>).
- Leave the test initially deactivated (@Ignore).
=> #8 Extend pattern rule test for short messages

languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/hunspell/sv_SE.aff
Matches found during Swedish spell checking included period (.) if at the end of a sentence. This commit fixes that.
Not sure if the intention of including it was to allow for abbreviations such as "t.ex.", but this change does not seem to affect that. Mostly since they were not handled correctly even before this change.
=> [sv] Avoid including . in match

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx
Added 'Tag', 'Jahrestag', 'Spieltag' to the German segmentation rules for keeping together e.g. 20. Tag, 40. Jahrestag, 9. Spieltag.
=> Update segmentation rules for the German language

languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/QuestionWhitespaceRule.java
Suggest "unbreakable space" instead of "thin unbreakable space" before colon (:) according to the "Lexique des règles typographiques en usage à l'Imprimerie nationale" (p.149).
=> Standards of typography (rules of Imprimerie Nationale)

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx
Added a missing backslash in an afterbreak regex.
=> Fix an exception rule for English in the SRX file

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Validity extension of gender and number agreement rules in French.
Not only at the beginning of a sentence, but also after a punctuation mark.
=> Lo fr 171229

languagetool-core/src/main/resources/org/languagetool/rules/false-friends.htm, languagetool-core/src/main/resources/org/languagetool/rules/print-ff.xsl
Hey,
This PR is a tentative solution for the issue #58, labeled as "easy fix".  It doesn't remove the possibility of accessing to the `false-friends.xml`, but it adds a new file (`false-friends.htm`) that allows to filter by language, attaching a parameter to the URL in this way: `false-friends.htm?lang=en`. If there is no parameter provided, it shows all the elements.
Please tell me if this fit into the idea.
=> Add HTML file for allowing to filter false friends by language (issue #58)

languagetool-gui-commons/src/main/java/org/languagetool/gui/ConfigurationDialog.java, languagetool-standalone/CHANGES.md
Fixes issue #908 
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree that this project and the …
=> Stop dispositioning of vertical scrolls when expanding the checkbox

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Hello.
I added some redundancy rules to the English grammar.xml
The rules I wrote are:
correcting PIN Number -> PIN ('N' stands for 'number')
correcting ISBN Number -> ISBN ('N' stands for 'number')
correcting LCD Display -> LCD ('D' stands for 'display')
I tested this by changing grammar.xml and restarting "languagetool.jar", and It worked.
=> [en] added some redundancy rules

.gitignore, languagetool-core/src/main/java/org/languagetool/rules/AbstractDateCheckFilter.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
I extended AbstractDateCheckFilter to default to the current year when no other value is given.
There are two new XML rules (DATUM_WOCHENTAG_OHNE_JAHR for German and DATE_WEEKDAY_WITHOUT_YEAR for English) that make use of this.
They should match dates where no year is specified and check if the weekday is correct (just like the other rule).
=> [de/en] added rule for date checks with missing year

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/OldSpellingRule.java
I fixed a bug where OldSpellingRule would only test the first match w.r.t. inflections and add all other matches without any checks, causing false positives.
=> [de] fixed false positives in old spelling rule

languagetool-core/src/main/java/org/languagetool/rules/AbstractDateCheckFilter.java, languagetool-core/src/main/java/org/languagetool/rules/AbstractNewYearDateFilter.java, languagetool-core/src/main/java/org/languagetool/rules/TestHackHelper.java, languagetool-core/src/main/java/org/languagetool/rules/YMDDateHelper.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/DateCheckFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/DateFilterHelper.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/NewYearDateFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/YMDNewYearDateFilter.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/DateCheckFilter.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/DateFilterHelper.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/NewYearDateFilter.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/YMDDateCheckFilter.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/YMDNewYearDateFilter.java, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
I added a new rule that only matches dates in the past year as long as it is currently January and suggests correcting the year part of the date to the new year.
=> [de/en] Added check for correct year shortly after New Year's

languagetool-core/src/main/java/org/languagetool/rules/AbstractFutureDateFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/FutureDateFilter.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/FutureDateFilter.java, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Sentences like 
> I created a pull request on July 26 2028.
will now be flagged. The new rule detects future dates in combination with verbs in past tense.
=> [de/en] Added check for future dates with verbs in past tense

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
I added a rule for dates in DD.MM.YYYY format containing spaces to UNGUELTIGES_DATUM.
=> [de] marked DD.MM.YYYY dates with spaces inbetween as an error

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx, languagetool-language-modules/de/src/test/java/org/languagetool/tokenizers/de/GermanSRXSentenceTokenizerTest.java
Fixed an issue where in multiple languages, e-mail addresses like John.Smith@example.com (with an uppercase letter after a dot) would be split up into multiple sentences by the tokenizer.
I added a new ruleset for all languages with high priority. It contains one rule to prevents this.
=> Added tokenizer rule to not split up e-mail addresses.

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Edited rules so October 1st/2nd/3rd/4th etc. match and can be corrected.
No exact validation of ordinal numbers takes place though, as there is already a rule for that.
=> [en] Added ordinal number support to DATE_WEEKDAY_WITHOUT_YEAR rule

languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineOptions.java, languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineParser.java, languagetool-commandline/src/main/java/org/languagetool/commandline/Main.java, languagetool-core/src/main/java/org/languagetool/language/LanguageIdentifier.java, languagetool-dev/src/test/java/org/languagetool/dev/eval/LanguageDetectionEval.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/Server.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-standalone/src/test/java/org/languagetool/language/LanguageIdentifierTest.java
I added optional support for language identification using the model available [here](https://fasttext.cc/docs/en/language-identification.html). Integration is done by starting the fasttext executable and communicating via stdin/stdout. When an error is encountered, we immediately fall back to the old approach based on character n-grams. Configuration is done via command line arguments for the CLI version or in configuration file for the server version.
=> Added fasttext as an option for language identification

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/LineExpander.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/ProhibitedCompoundRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/ProhibitedCompoundRuleTest.java
HunspellRule.isMissspelled ignored words in ignoredWords, e.g. additions to spelling.txt
ProhibitedCompoundRule depended on this function and thus would not suggest corrections
for these words
Added Urberliner and some other words to spelling.txt, Uhr/ur confusion to ProhibitedCompoundRule
=> fixed inconsistency with HunspellRule.isMisspelled, added prohibited compounds to german

languagetool-wikipedia/src/main/resources/org/languagetool/resource/dev/SimpleWikiConfiguration.xml
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation and update the code that generates new DOI links.
Cheers!
=> Hyperlink DOIs to preferred resolver

languagetool-server/scripts/database/migrations/20181010_extend_access_limits_reason_column_size.sql, languagetool-server/src/main/java/org/languagetool/server/ErrorRequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/RequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/Server.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/ErrorRequestLimiterTest.java, languagetool-server/src/test/java/org/languagetool/server/RequestLimiterTest.java
bigger per-ip limit
try to distinguish users by fingerprints and use smaller per-user limit
fingerprints: HTTP request headers -> User-Agent, Accept-Language, Referer
configure via: ipFingerprintFactor
1 is default behavior, n allows access by n users from the same IP using different clients
=> RequestLimiter with fingerprints

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleMatcherTest.java
interpreted \1, \2, ... in input text as match references (as used in rule messages)
could lead to array index out of bounds exceptions, artifacts, ...
now tracking already replaced text to avoid this recursion
=> fixed error in PatternRuleMatcher

languagetool-core/src/main/resources/org/languagetool/rules/false-friends.html
This fixes several error messages like the following one from LGTM:
Variable xhttp is used like a local variable,
but is missing a declaration.
=> Add missing variable declarations for JavaScript code

languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineOptions.java, languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineParser.java, languagetool-commandline/src/main/java/org/languagetool/commandline/Main.java, languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/dumpcheck/SentenceSourceChecker.java
Added option `neuralNetworkModel` allows providing a base directory of saved neural network models.
Rules listed by the new `Language.getRelevantNeuralNetworkModels` should expect any exported models they require to be found there.
=> added new option and rule category for rules relying on neural networks

languagetool-server/src/main/java/org/languagetool/server/DatabaseAccessLimitLogEntry.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseCheckErrorLogEntry.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseCheckLogEntry.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseMiscLogEntry.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseRuleMatchLogEntry.java
fixes errors when SQL strict mode is enabled and a field value exceeds the maximum configured length
=> added trimming for varchar fields to database logging code

languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineTools.java, languagetool-core/src/main/java/org/languagetool/DetectedLanguage.java, languagetool-core/src/main/java/org/languagetool/language/LanguageIdentifier.java, languagetool-core/src/main/java/org/languagetool/tools/RuleMatchesAsJsonSerializer.java, languagetool-core/src/test/java/org/languagetool/tools/RuleMatchesAsJsonSerializerTest.java, languagetool-http-client/src/test/java/org/languagetool/remote/RemoteLanguageToolIntegrationTest.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/java/org/languagetool/server/V2TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/HTTPServerTest.java, languagetool-server/src/test/java/org/languagetool/server/TextCheckerTest.java, languagetool-standalone/CHANGES.md, languagetool-standalone/src/test/java/org/languagetool/language/LanguageIdentifierTest.java
Not falling back to English anymore when confidence of language detection is low;
instead, including confidence of language detection model in response, so that
clients can decide if corrections should be ignored / marked as speculative
=> Added confidence value to detected language field

languagetool-core/pom.xml, languagetool-core/src/main/java/org/languagetool/UserConfig.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/suggestions_ordering/SuggestionsOrderer.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/suggestions_ordering/SuggestionsOrdererConfig.java, languagetool-core/src/test/java/org/languagetool/rules/spelling/morfologik/suggestions_ordering/SuggestionsOrdererTest.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Implemented simple A/B-Testing scheme, first test: SuggestionsOrderer
Assignment via textSessionId: even/odd -> A/B
Results implicitly found in existing check_log / corrections tables
Added abTest option to HTTPServerConfig, disables / specifies a test to run
Added textSessionId, abTest property to UserConfig as additional information,
but explicitly ignored in .equals/.hashCode -> invariant to e.g. PipelinePool
=> A/B Test for Suggestions ordering

languagetool-core/src/main/java/org/languagetool/language/CommonWords.java
Should fix this:
```
2018-12-20 23:11:33 +0100 ERROR o.l.l.LanguageIdentifier Disabling fasttext language identification, got error for text: Thank you for su
java.lang.ArrayIndexOutOfBoundsException: 11
at java.base/java.util.ArrayList.add(ArrayList.java:468)
at java.base/java.util.ArrayList.add(ArrayList.java:480)
at org.languagetool.language.CommonWords.<init>(CommonWords.java:63)
at org.languagetool.language.LanguageIdentifier.detectLanguage(LanguageIdentifier.java:182)
at org.languagetool.server.TextChecker.detectLanguageOfString(TextChecker.java:458)
at org.languagetool.server.V2TextChecker.getLanguage(V2TextChecker.java:106)
at org.languagetool.server.TextChecker.checkText(TextChecker.java:204)
at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:113)
at …
```
=> Fixed exception caused by concurrent modification of list in CommonWords

languagetool-server/src/main/java/org/languagetool/server/ErrorRequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/RequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/ErrorRequestLimiterTest.java
Fix limits being imposed on users in e.g. a classroom environment where multiple users are behind identical browsers / IP addresses.
=> Added textSessionId to fingerprint used by RequestLimiter

languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Skips requests if an error occurred recently while querying the server
Configured via hiddenMatchesServerFailTimeout in config file; disabled by setting a negative value
Should prevent high load / hangups when hidden matches server is down,
as even small request timeouts add up to slow the server down heavily
=> Implemented simple health check logic for hidden matches server

languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Came up when e.g. ngrams were missing / PipelinePool.createPipeline failed with an exception
=> fixed NPE in PipelinePool.returnPipeline

languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Made logging of rule matches to database configurable,
since enabling it creates heavy write load for database
=> New option skipLoggingRuleMatches in server config

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/CompoundAwareHunspellRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java
Now ranking generated compounds below suggestions by Morfologik,
since they are often low-quality; automatically tested on user data,
should provide an improvement of four percentage points in accuracy for the first suggestion
Evaluation tool will follow in a later commit
=> [de] Improved some suggestions by GermanSpellerRule

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Correct word would be „Ahoj-Brause“ (see https://de.wikipedia.org/wiki/Ahoj)
=> [de] prohibit „Ahoi-Brause“

languagetool-core/src/main/java/org/languagetool/rules/WrongWordInContextRule.java
triggered by errors in words with '$' or '\' in them
cause: use of String::replaceFirst
solution: transform all user input and messages with Matcher.quoteReplacement
=> Fixed RuntimeException in WrongWordInContextRule

languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpeller.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java
Speller.findReplacements output changes when the same object is used multiple times
fix: create new Speller object every time in MorfologikSpeller.getSuggestions
=> Workaround for potential bug in morfologik

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
Common name marked as error in American, Canadian and Australian English.
@MikeUnwalla ok for you?
=> [en] add 'Rebecca'

languagetool-core/src/main/java/org/languagetool/rules/spelling/suggestions/XGBoostSuggestionsOrderer.java
Fixes error mentioned in https://github.com/languagetool-org/languagetool/pull/1458#issuecomment-471619124
=> Added workaround for XGBoost on 32 bit architectures

languagetool-core/src/main/java/org/languagetool/rules/spelling/suggestions/XGBoostSuggestionsOrderer.java
Exception / error message comes from static block in XGBoostJNI; class loaded because of call to XGBoost.loadModel
No way to avoid any error message but to prevent this code from executing under Windows at the moment
=> Fix for #1461

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
@MikeUnwalla I added a few words that our addon users often add to their personal dictionary.
Jira = popular task management software by Atlassian
Christy = name
deliverable = https://en.wikipedia.org/wiki/Deliverable
Deloitte = name of big consulting company
UX = common abbreviation of "User Experience"
dev = common abbreviation of "Developer" or "Development" ("He is a good web dev")
flyers = for some reason not in the american english dict
Liam = common person name
KPIs = plural of KPI (key performance indicator)
Vijay = common person name
summative = https://dictionary.cambridge.org/dictionary/english/summative
fintech = like biotech but for the finance industry (https://en.wikipedia.org/wiki/Financial_technology)
Let me know what you think. Thanks!
=> [en] add words to english dictionary

languagetool-server/pom.xml, languagetool-server/src/main/java/org/languagetool/server/ApiV2.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServer.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Enable via `prometheusMonitoring=true` in configuration file
Configure port via `prometheusPort`, defaults to 9301.
For now, counts HTTP requests & responses (by code), some errors and check statistics (total, time, size).
Also exposes some JVM metrics.
=> Added simple Prometheus monitoring

languagetool-server/src/main/java/org/languagetool/server/ResultExtender.java
Discarding authentification parameters in forwarded requests;
cause errors as hidden matches server does not have a database configured
=> Fix for requests to hidden matches server

languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/tagset.txt
The link to the original POS tags was outdated and redirected to a 404 page.
=> [ca] Update tagset documentation

languagetool-http-client/src/test/java/org/languagetool/remote/RemoteResultTest.java, languagetool-http-client/src/test/java/org/languagetool/remote/RemoteRuleMatchTest.java, languagetool-http-client/src/test/java/org/languagetool/remote/RemoteServerTest.java
Hi,
I've analysed your codebase and seen some gaps in the coverage of:
- org.languagetool.remote.RemoteResult (100% of now lines covered)
- org.languagetool.remote.RemoteRuleMatch (100% of lines now covered)
- org.languagetool.remote.RemoteServer (86.67% lines now covered; was 80%)
I've written the tests for these functions with the help of [Diffblue Cover](https://www.diffblue.com/products).
Hopefully, these tests will help you detect regressions caused by future code changes.
=> Add unit tests for org.languagetool.remote.RemoteResult, RemoteRuleMatch and RemoteServer

languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java
It would be useful if the `RegexPatternRule` class was public.
Our project adds rules to a `LanguageTool` instance programmatically. The `PatternRule` class is public and its tokens can use regular expressions, but we have a large library of regexes that cover multiple words and don't work as tokens, and we'd have to rewrite these expressions to use them in this model.
Using a `RegexPatternRule` solves this problem nicely, and it would be useful to import it directly rather than duplicating it, which raises licensing concerns, or resorting to reflection to gain access.
=> Make RegexPatternRule class public

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling_en-US.txt
* POS-tagged `pre-order` and `preorder` as verb and noun
* added `pre-order` to the dictionary of all English variants
* added `preorder` only to the AmE
* generate a better suggestion for `eCommerce` (currently only "commerce" is suggested)
* added two popular software products (`Magento` and `Wix`) to the dictionary
* added `mechatronic(s)` to the dictionary, after receiving user feedback (POS was already there)
@MikeUnwalla what do you think?
=> [en] improve dictionary and suggestions

README.md
In this PR I've added another community-contributed dockerfile for LanguageTool:
https://github.com/Erikvl87/docker-languagetool
The Docker Hub image can be found here: https://hub.docker.com/r/erikvl87/languagetool
In the past I've been using silvio's version, but for the following reasons I've created my own repository containing a LanguageTool Dockerfile. I wanted to:
- Push individual LanguageTool versions to Docker Hub so you are able to pin on a certain version
- [Run the LanguageTool unit tests using travis-ci](https://travis-ci.org/Erikvl87/docker-languagetool) for every container image before pushing an image to Docker Hub to guaranty a working image
- Be able to use the [HttpServerConfig](https://languagetool.org/development/api/org/languagetool/server/HTTPServerConfig.html) …
=> Include another community-contributed Dockerfile

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
use of SequenceInputStream for spelling.txt files could case errors when a file missed a newline on the last line
now inserting a stream with a comment + newline in between to avoid joining the first and last lines of separate files
=> fixed bug in GermanSpellerRule

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
Adding "mami" and "papi" to the Spanish dictionary since they are officially listed in the "Diccionario de la lengua española"
https://dle.rae.es/?id=O6KVLaO
https://dle.rae.es/?id=RnOaO3e
=> [es] add 'mami' and 'papi'

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
What's in this PR:
1. Add NN as POS for "follow" (see https://en.wiktionary.org/wiki/follow and https://www.merriam-webster.com/dictionary/follow) "a follow up" is now caught by `CA_FOLLOW_UP` which also offers a suggestion. (this would close https://github.com/languagetool-org/languagetool/issues/1468)
2. Add NN as POS for "recharge" (see https://en.wiktionary.org/wiki/recharge and https://en.wiktionary.org/wiki/recharge)
3. Improve A_INFINITIVE by adding antipatterns
4. In those antipatterns are now "thank" and "google" for which I created special rules
5. Added "merge" as an antipattern to `A_INFINITIVE` to prevent some false alarms in common tech speak: "Can you have a look at the merge request?"
@MikeUnwalla let me know what you think. Thanks!
=> [en] partially address #1812

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt
Hey @MikeUnwalla,
I saw many false positives caused by "a/the cancel". 
Webster and Oxford lists it as a noun:
https://www.lexico.com/en/definition/cancel
https://www.merriam-webster.com/dictionary/cancel
Apparently there's no plural form of "cancel". Do I need to add the uncountable POS here?
What is the difference between `NN:U` and `NN:UN`?
=> [en] add POS for cancel

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
My suggestion for #1944 
* Collected false alarms reported by users and regression test and added them to the rule (btw: none of those false alarms is happening on the ATD website)
* Added a false positive where "According to his friend" is not detected
* Disabled the affected sub rule which got too complex (at least for me)
* Started a new rule that is less aggressive (it will find fewer errors, but still the most common ones)
@TiagoSantos81 My goal is not to disrespect your work. I'm just trying to find a good compromise.
=> [en] rework ATD_VERBS_TO_COLLOCATION

languagetool-core/src/main/java/org/languagetool/tools/StringTools.java, languagetool-core/src/test/java/org/languagetool/tools/StringToolsTest.java
See https://en.wikipedia.org/wiki/Zero-width_space
Currently, every zero-width-space is creating an UNKNOWN token.
The LT browser add-on and many rich text editor libraries make heavy use of ZWS characters to work around certain issues.
Technically ZWS is a space. Other languages like JavaScript are already treating it as one.
Here's an example showing that the rule `LETS_LET` gets confused by ZWS (second sentence contains a ZWS before "do"):
=> treat zero-width-space also as white space 

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
"Cum Laude" can be used without "Summa" etc.
See https://en.wikipedia.org/wiki/Latin_honors
> cum laude, meaning "with praise". This honor is typically awarded to graduates in the top 20%, top 25%, or top 30% of their class, depending on the institution.[2][3]
=> [en] improve antipattern for PROFANITY

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
See #2033
It now accepts every type of apostrophe (even the ones that technically aren't one)
=> [en] unify use of apostrophes

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@danielnaber Ich habe die Regel "DE_AGREEMENT" etwas niedriger priorisiert, weil sie andere Regeln unterdrückt hat:
Hier wäre die Regel "MONTAGS" hilfreicher:
Hier gibt es anscheinend keine Regel für die Kleinschreibung von "recht machen" (habe ich hinzugefügt):
Macht das Sinn? Die "CONFUSION_RULE" hat jetzt dieselbe Prio wie "DE_AGREEMENT".
=> [de] improve DE_AGREEMENT by lowering its prio

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java
e.g. should always suggestion conversion for miles per hour instead of
just miles
previous code would return multiple matches, which one would be shown to users
wasn't clear-cut
=> fix #2087: use longest match for unit conversion

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternTokenBuilder.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternTokenTest.java
It seems that `.negate()` works only for POS tokens (e.g. `new PatternTokenBuilder().posRegex("NN.*?").negate().build()`). This fix should enable negation for "text" tokens (e.g. `new PatternTokenBuilder().tokenRegex("an?|the").negate().build()`).
=> PatternTokenBuilder: minor fix. 

languagetool-core/src/main/java/org/languagetool/rules/CommaWhitespaceRule.java, languagetool-core/src/main/resources/org/languagetool/MessagesBundle.properties, languagetool-core/src/test/java/org/languagetool/rules/CommaWhitespaceRuleTest.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
a simple fix suggestion that checks that no quote is surrounded by whitespaces on both sides. Very minor class-local refactoring. All tests pass on build.
=> fix for the issue #2001: quote within spaces

languagetool-core/src/main/java/org/languagetool/rules/spelling/SpellingCheckRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java
ConcurrentModificationException in
SpellingCheckRule.updateIgnoredWordDictionary
probably caused by multiple calls to init()
=> Possible fix for ConcurrentModificationException

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/AmericanEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
Introduced for BERTSuggestionRanking
Allows existing rules to be replaced by a RemoteRule that wraps them
Fixes issues with altLanguages
BERTSuggestionRanking now activated for MORFOLOGIK_RULE_EN_* (i.e. all
variants of English)
=> Added Language.getRemoteEnhancedRules

languagetool-core/pom.xml
bumped grpc version
added dependency on javax.annotation-api, missing in Java 9+
=> fix compilation error in generated grpc code

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java
use setSuggestedReplacementObjects in BERTSuggestionRanking
call extendSuggestions on matches from instances of TextLevelRule and RemoteRule
=> apply extendSuggestions to TextLevelRule, RemoteRule matches

languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java, languagetool-language-modules/ar/src/main/resources/org/languagetool/rules/ar/grammar.xml
Fix rules after https://github.com/languagetool-org/languagetool/commit/9a4f1e36c5d9a15056d656ddfe102da7fc84159c  and https://github.com/languagetool-org/languagetool/issues/2511#issuecomment-592162654
=> [ar] Fix rules after #9a4f1e3 

languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java
PatternRuleTest now (as of 9a4f1e36c5) separately checks each sentence,
but computes expected position from <marker> on the whole text
Need to adjust offsets of RuleMatch objects accordingly (relative to whole text),
else examples with multiple sentences will fail
=> fix match offset positions in PattenRuleTest

languagetool-core/src/test/java/org/languagetool/rules/patterns/AbstractPatternRuleTest.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java
replaces fail/asserts so that test doesn't fail on first error
-> list errors for all rules in a single run
=> Use ErrorCollector in PatternRuleTest

languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java
See https://forum.languagetool.org/t/testrules-ignore-there-were-10-errors/5433
=> fixed messages for test failures in PatternRuleTest

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/EnglishWordRepeatBeginningRule.java
If several sentences start with determiner - it is a correct case.
=> Grazie migration: Add exceptions for EnglishWordRepeatBeginningRule

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
Because of different IDs user have two same categories.
=> Grazie migration: Change US_SPECIFIC_TYPOS to TYPOS

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/ResultCache.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleResult.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Caching for rules that extend RemoteRule
Special execution semantics (batched, asynchronous, at the start, then collected with timeout) require different logic
per-rule cache, adjust match positions , check for success before caching
=> Remote rule cache

languagetool-core/src/main/java/org/languagetool/rules/AbstractDashRule.java, languagetool-language-modules/br/src/main/java/org/languagetool/rules/br/BretonCompoundRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanCompoundRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/SwissCompoundRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/CompoundRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/EnglishDashRule.java, languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/CompoundRule.java, languagetool-language-modules/ga/src/main/java/org/languagetool/rules/ga/CompoundRule.java, languagetool-language-modules/nl/src/main/java/org/languagetool/rules/nl/CompoundRule.java, languagetool-language-modules/pl/src/main/java/org/languagetool/rules/pl/CompoundRule.java, languagetool-language-modules/pl/src/main/java/org/languagetool/rules/pl/DashRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PostReformPortugueseCompoundRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PostReformPortugueseDashRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PreReformPortugueseCompoundRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PreReformPortugueseDashRule.java, languagetool-language-modules/ro/src/main/java/org/languagetool/rules/ro/CompoundRule.java, languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/RussianCompoundRule.java, languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/RussianDashRule.java, languagetool-language-modules/sk/src/main/java/org/languagetool/rules/sk/CompoundRule.java, languagetool-language-modules/sv/src/main/java/org/languagetool/rules/sv/CompoundRule.java
Some rules use too much static memory, even if not used. I made them lazy, so if the user disables them, they will not waste memory.
=> Grazie migration: Make compounds rules lazy

languagetool-core/src/main/java/org/languagetool/rules/Rule.java
Each DisambiguationPatternRule create a new category, which produce a 400KB waste only for English.
=> Grazie migration: Fix thousands duplications of MISC category in rules

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Minor fix of spelling mistake in `Readability: Three nouns in a row` rule
=> Fix for example of `Readability: Three nouns in a row` rule in English

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Add a rule for sentences beginning with common English modal verbs followed by common personal pronouns for the rule group QUESTION_MARK.
I avoided using the generic modal (MD) part of speech (postag), because there are several modal verbs that cause false matches. For example, "May we all do well." is not a question.
Likewise, I avoided using the generic PRP postag, because there are several pronouns that cause false matches in the pattern. For example, "Do them a favor." is not a question.
The original piece of text I wanted to be marked as incorrect in an email conversation was, "Can you help me."
=> Add a rule to the group QUESTION_MARK for common MD+PRP

languagetool-language-modules/pl/src/main/resources/org/languagetool/rules/pl/grammar.xml
This patch fixes broken links detected in #2729 (except of 2)
Links are updated to the same page with new URL schema or to another page describe the same rule. Every link was manually reviewed.
For following two links I cannot find an equivalent:
```
FOUND BROKEN URL [http://slowniki.gazeta.pl/pl/kondycja]
FOUND BROKEN URL [http://sjp.pwn.pl/haslo.php?id=63498]
```
I want to ask @dpelle to run his script again and check if I didn't leave any broken link more :)
=> [pl] Update broken links

languagetool-commandline/src/main/java/org/languagetool/commandline/Main.java, languagetool-core/src/main/java/org/languagetool/AnalyzedTokenReadings.java, languagetool-core/src/main/java/org/languagetool/rules/neuralnetwork/NeuralNetworkRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java, languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/CheckCallable.java, languagetool-language-modules/ro/src/test/java/org/languagetool/tagging/ro/AbstractRomanianTaggerTest.java, languagetool-language-modules/uk/src/test/java/org/languagetool/rules/uk/MorfologikUkrainianSpellerRuleTest.java, languagetool-language-modules/uk/src/test/java/org/languagetool/tagging/disambiguation/uk/UkrainianDisambiguationRuleTest.java, languagetool-office-extension/src/main/java/org/languagetool/openoffice/LanguageToolMenus.java, languagetool-office-extension/src/main/java/org/languagetool/openoffice/MessageHandler.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/index/Searcher.java
There is no need to use `toString()` on string concatenation or in `.format()`, as it is automatically called by the compiler/implementation.
=> Remove redundant .toString()

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-dev/src/main/java/org/languagetool/dev/SentenceChecker.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/AggregatedNgramToLucene.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/ConfusionSetOccurrenceLookup.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/TextIndexCreator.java, languagetool-dev/src/main/java/org/languagetool/dev/diff/LightRuleMatchParser.java, languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/HttpApiSentenceChecker.java, languagetool-dev/src/main/java/org/languagetool/dev/wiktionary/HomophoneExtractor.java, languagetool-dev/src/test/java/org/languagetool/dev/FrequencyIndexCreatorTest.java, languagetool-standalone/src/main/java/org/languagetool/dev/RuleCreator.java, languagetool-standalone/src/test/java/org/languagetool/TranslationTest.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/RareWordsFinder.java
Fixes #2202
The reason was: Scanner behavior is different with maven in Windows, and `Scanner(File)` had been replaced globally by `Files.readAllLines`.
However, there are still failed tests on windows, but would be handled separately.
=> Fix HunspellRuleTest on Windows

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/tagset.txt
The existing URL is not found.
Also, the URL could be https://catalog.ldc.upenn.edu/docs/LDC95T7/cl93.html
=> Correct URL to Penn Treebank tagset

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
* disabled some rules that have a very low acceptance  of less than 5% (show suggestions → apply suggestion). We can enable them again once we have a "picky" mode
* added words to the dictionary so that they are available to the spell checker
* improved the suggestions of some anglicism rules by offering a plural form
* added antipatterns based on common proper nouns or idioms
cc @jaumeortola @vkyfox
=> [fr] disable and rework some anglicism rules 

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/resources/org/languagetool/MessagesBundle_en.properties, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
deleted by automatic update
now included in code as constants
caused all requests to be registered as success in monitoring
but no matches to be added
=> fixed missing messages for AI rules

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
sub-IDs could contain characters illegal in rule IDs
replace all illegal characters with underscores
also: prioritise all AI_* rules instead of only explicitly listed
ones (with old names)
=> fix IDs created by GRPCSubRule

languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/ResultExtender.java, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
new configuration option: hiddenMatchesServerFall
mark as down after N consecutive failures
improved monitoring for hidden matches: Counter
languagetool_hidden_matches_server_requests_total with 'status' label
=> implemented 'fall' option for hidden matches

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
Many false alarm reports for AI_MISSING_THE for cases that would be covered by UPPERCASE_SENTENCE_START, so re-prioritize. 
Suggested by @palasso
=> re-prioritised rules to avoid false alarms

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Ob ihr die Pluralversion wollt, könnt ihr selbst entscheiden.
=> Volksband statt Volksbank

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/ResultCache.java, languagetool-core/src/main/java/org/languagetool/UserConfig.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleConfig.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleResult.java, languagetool-core/src/test/java/org/languagetool/rules/GRPCRuleTest.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/BertResortingBugTest.java
Separate cache, matches are stored by rule, so we can deal with request failures, empty results, fallback results, etc.
Refactored offset adjustment - now done out of the rule, works with AnnotatedText
=> Caching for remote rule results

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Hello,
The rule currently doesn't work for Gb, as it suggests replacing it by Gb (works for GB).
=> [fr] Update byte rule for lower case Mb

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Das habe ich durch einen Fehler gefunden, denn das Nomen war falsch. Die Regel hat das richtig erkannt.
=> Blumenkran statt Blumenkrans

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
Logging otherwise affects command line output
We should consider directing all logging to stderr; right now, a Logback configuration exists only for tests and languagetool-server.
=> only log remote check time if remote rules active

languagetool-core/src/main/java/org/languagetool/chunking/ChunkTaggedToken.java
If an English or German module is loaded with a different classloader than Core, you will get an IllegalAccessError.
=> Make constructor of ChunkTaggedToken public

languagetool-core/src/main/java/org/languagetool/chunking/ChunkTaggedToken.java
If an English or German module is loaded with a different classloader than Core, you will get an IllegalAccessError.
=> Make methods of ChunkTaggedToken public

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Ich habe den type="style" zur Regel COMME_PAR_EXEMPLE hinzugefügt. Das ist ein Test, ob das funktioniert – diesen Type würde ich gerne für ein paar Regeln vergeben, damit wir im frz. Demo-Text auch was blau unterstrichen haben :)
=> [fr] COMME_PAR_EXEMPLE -> type="style"

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-GB/grammar.xml
Spotted a period where there should be a question mark.
=> [en] fix missing '?' in en-GB ANYMORE

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
IDs not hard-coded anymore in getRelevantRemoteRules
instead load all rules with AI_* as ID
require description and message to be provided by remote server
=> fix sub-IDs of GRPCRule, automatically load rules

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
Das fixt übrigens einen Loop. 'Birdsong' existiert definitiv auch im Plural und ich finde keine Hinweise darauf, dass es im AmE falsch ist.
=> [en] add 'birdsongs' to spelling.txt

pom.xml
As developer I migrated and company internal library to use Junit 5. Junit 5 runs some tests faster and in the end some  test code is easier to read and write. For example tests with exceptions do not need a _Rule_ but a simple Lambda will do. Also Junit 5 new features open a ton of new test features that make it easier to write tests.
As an inbetween I used junit 4.13 to find deprecations and change the tests first. Then I moved to 5 without using a compatability layer very easily. 
Languagetool is a bit more complex. If you are interested into moving to 5 this might be an interesting step in between. 
I ran the build on both Java 8 and 11 and it succeeded.
=> Use junit 4.13. Allows for smoother migration path to 5

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
GRPCRule and BERTSuggestionRanking return matches with Rules whose IDs don't match the original rule,
this lead to some bugs. Now you can disable the execution of the rule as a whole (by setting disabledRules to the ID of the base rule) or exclude specific matches (by setting disabledRules to the respective IDs).
There are still issues with enabledOnly left to be fixed later
=> Fix interactions of disabledRules and RemoteRule implementations

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/MultiThreadedJLanguageTool.java
and unify "paragraph end" behavior between base and multithreaded implementations
=> MultiThreadedJLanguageTool: avoid overhead when analyzing just one sentence

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/det_a.txt
Added "utilisable", "utilisation" and "utilised" corresponding to the British spelling of the equivalent words already present with the "-ize" ending.
=> [en] Update det_a.txt: add british spelling of words with "utiliz*" root

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
"Kur" wird von der Regel nicht erkannt, weswegen ich es eintrage.
=> Kurgewinn statt Kursgewinn

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Adapted the rule so it doesn't cause FPs for language groups and meetings
=> [fr] fix GENTILES (FB groups and meetings)

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
+ Duplikatk "Abgangsgel" entfernt
+ /S bei Wörtern mit der Endung Gel ergänzt
+ https://www.duden.de/rechtschreibung/gleich_konvergent_einfoermig / https://www.dwds.de/wb/gleichgro%C3%9F hinter dem Wort "gleichgroß" verschoben
Grüße Dallun511
=> Ergänzungen und Optimierungen

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/XmlRuleDisambiguator.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternTokenTest.java
don't even run rules that can't possibly match, judging by their token strings/regexps
to determine that, parse simple yet most frequent regexps that have just |?[] in them, extract all possible values from them
and use that set for faster PatternToken.isStringTokenMatched and to build index of rules by word form in XmlRuleDisambiguator
=> speed up XmlRuleDisambiguator

languagetool-core/src/main/java/org/languagetool/rules/UppercaseSentenceStartRule.java
To resolve the ReCAPTCHA <-> reCAPTCHA loop ([#3755](https://github.com/languagetool-org/languagetool/issues/3755))
=> [en] add "reCAPTCHA" as exception in UpperCaseSentenceStartRule

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
The rule IT_IS_DEPENDING_ON must be prioritized over PROGRESSIVE_VERBS in order for this experiment to work.
=> [en] prioritize DEPENDING over PROGRESSIVE

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Correctly spotted by user, as addressed in [#3766](https://github.com/languagetool-org/languagetool/issues/3766)
=> [fr] fix incorrect message for AUX_ETRE_VCONJ

languagetool-core/src/main/java/org/languagetool/InputSentence.java, languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/ml/MLServerProto.java, languagetool-core/src/main/proto/ml_server.proto, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java, languagetool-server/src/main/java/org/languagetool/server/Pipeline.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Allow server-side decision about partial rule rollout for remote rule
Enable reconfiguration of remote rules to avoid strict timeouts, e.g. for regression tests
=> Remote rule rollout and regression test stabilty

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java
For me, this results in ~10% English text checking speedup.
=> call sentence.getText only when it's needed to speed up the analysis

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Sebastian discovered this loop:
tiefgehend <-> tief gehend
I fixed it in grammar.xml so it doesn't clash with lt_recommendation_premium. I also fixed a few recommendations I didn't deem correct (not a good correction: tiefgekühlt --> tief gekühlt) and generally followed "official" recommendations. We might want to think about an even more coherent approach in the future (_tiefsitzend, tiefgehend, tiefgreifend_ have different official recommendations, but we are free to disagree...)
=> [de] fix EMPFOHLENE_GETRENNTSCHREIBUNG[6]

languagetool-core/src/main/java/org/languagetool/tools/ContextTools.java
don't replace/mark in entire text only to extract a tiny substring afterwards
=> speedup command line error reporting on large texts

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/MultiThreadedJLanguageTool.java
precompute them just once for all sentences, not for each rule afresh
use this data to speedup text-level match anchoring
This gives me some 5-10% speedup for English
=> decrease the number of line/column calculations

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java
=> store possible regexp values in an array instead of TreeMap

languagetool-core/src/main/java/org/languagetool/rules/patterns/XMLRuleHandler.java
For English, this reduces the number of those instance by a factor of 3, saving a bit more than 1 MB
=> save memory by avoiding duplicate PosToken instances

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://de.wikipedia.org/wiki/Entf%C3%BChrungsversicherung
Diese Versicherung existiert und sollte deswegen aufgenommen werden.
=> Add Word Lösegeldversicherung

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/RuleMatch.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
add new RuleMatch.setLazySuggestedReplacements API for that
For single-threaded analysis of AmericanEnglish without requesting suggestions, this gives ~40-45% analysis speedup.
=> MorfologikSpellerRule: calculate suggestions only when they're needed

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java
No memory saving so far due to object alignment, but I plan to remove more fields
=> remove unnecessary PatternToken.referenceString field

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/tools/Tools.java
to avoid calling `ignoreRule` for each rule in each `check` invocation, often for each sentence
and to avoid filtering out picky rules by tag on each `check` call
=> JLanguageTool: cache active rules

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
This came up because of the German demo text on languagetool.org.
=> [de] make message for German "article before date" clearer

languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java, languagetool-core/src/main/java/org/languagetool/tagging/ManualTagger.java, languagetool-core/src/main/java/org/languagetool/tools/MostlySingularMultiMap.java
don't waste space on arrays of length 1
For English, this saves a bit more than 1MB
=> ManualSynthesizer/ManualTagger: reduce memory overhead

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
[Im Diff](https://internal1.languagetool.org/regression-tests/via-http/2020-11-26/de-DE/result_grammar_GLEICHBEHANDLUNG[1].html) wird klar, dass "(m/w)" sinnvoll sein kann, wenn es sich nicht um eine Stellenausschreibung handelt.
Die Message habe ich auch etwas weniger präskriptiv gemacht, damit niemand sie als moralistisch empfindet.
=> [de] make message for GLEICHBEHANDLUNG more cautious and user-friendly

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Before this rule can be activated, the diff must be FP-free.
=> [de] temp_off DER_ERSTE to fix FPs

languagetool-commandline/src/main/java/org/languagetool/commandline/CommandLineTools.java
to speed up the result printing
For me, this speeds up `Main -l de-DE` by ~45%
=> CommandLineTools: calculate expensive lazy suggestions in parallel

languagetool-core/src/main/java/org/languagetool/rules/AbstractCompoundRule.java
Minor, unlikely to result in an obvious performance improvement (except maybe if just this rule is run on huge texts), but it just felt wrong to see this in CPU snapshots.
=> AbstractCompoundRule: avoid locking overhead in a single-threaded queue

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
differentiate using prefix: AI_EN/AI_DE
special case for now: AI_HYDRA_LEO
=> implemented loading gRPC rules for German

languagetool-core/src/main/java/org/languagetool/rules/patterns/StringMatcher.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/StringMatcherTest.java, languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
This speeds up my `Main -l en` by 5-10% and decreases memory usage a bit
=> StringMatcher.getPossibleRegexpValues: support more regexp constructs

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRulePerformer.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java
So that if matching is optimized, both places profit from that.
Interestingly, this also seems to unexpectedly result in some small performance improvement (~5% in `Main -l en`).
This branch contains several small commits in case you find that easier to review. They have no historical significance and can be squashed before merging into master.
=> Unify matching logic in PatternRuleMatcher and DisambiguationPatternRuleReplacer

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/det_a.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/det_an.txt
1. Added several missing /ju-/ words to `det_a.txt`
2. Removed some words from `det_a.txt` and `det_an.txt` whose inclusion seems moot or incorrect (not 100% confident)
3. Fixed a few seeming minor issues (not 100% confident)
=> [en] Various improvements to EN_A_VS_AN determiner rule

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
Needs to be undone because of [these FPs](https://internal1.languagetool.org/regression-tests/via-http/2020-12-10/de-DE/result_java_DE_AGREEMENT.html)
=> [de] revert disambiguation changes because of FPs

languagetool-core/src/main/java/org/languagetool/ShortDescriptionProvider.java, languagetool-standalone/src/test/java/org/languagetool/ShortDescriptionProviderTest.java
use a single concurrent map with all language descriptions computed on-demand,
instead of two racy non-synchronized collections
this fixes a flaky CCE from internals of HashMap accessed from multiple threads
=> make ShortDescriptionProvider thread-safer and shorter

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/OldSpellingRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/tagging/de/GermanTagger.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AmericanReplaceRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/BritishReplaceRule.java, languagetool-language-modules/ru/src/main/java/org/languagetool/language/Russian.java, languagetool-language-modules/ru/src/main/java/org/languagetool/tagging/disambiguation/ru/RussianHybridDisambiguator.java, languagetool-language-modules/ru/src/main/java/org/languagetool/tagging/ru/RussianTagger.java, languagetool-language-modules/ru/src/test/java/org/languagetool/tagging/ru/RussianTaggerTest.java
make some expensive fields lazy, so that they'll be loaded later, hopefully even in parallel
this improves startup time a bit,
and the IDE responsiveness when LT needs to be initialized in the background to highlight a file
=> [en,de,ru] speed up language and JLanguageTool initialization

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
I discovered this error when attempting to debug why LT was not properly
flagging the phrase "as if it'll means something" against the
MD_BASEFORM[2] rule.
I validated that the behavior doesn't cause any incorrect behavior by
testing the patched version of the disambiguator against the gutenberg
extracts corpus and comparing the flagged rules to the unpatched
version. I then manually verified the tagged output (`-t`) was correct
for all instances of the word "it'll" in the Alice in Wonderland
extract.
=> [en] Add "it" to "'ll" disambiguation

languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/StringMatcher.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/Substrings.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/StringMatcherTest.java
use them to speed up token text matching and regexp rules
~20% speedup in my `Main -l de`
=> StringMatcher: extract substrings from regexp that any matching text must contain

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/MultiThreadedJLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractTokenBasedRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RuleSet.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/XmlRuleDisambiguator.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/RuleSetTest.java
extract RuleSet out of XmlRuleDisambiguator, support lemma hints there, use it in JLanguageTool.check as well
~5% speedup on `Main -l en` and `Main -l de`; ~10% speedup in IntelliJ-specific English setup (1 thread, no spellchecker and `NoopChunker`)
=> don't invoke pattern rules with hints inapplicable to a sentence

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/CompoundAwareHunspellRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/spelling/hunspell/HunspellRuleTest.java
don't let exceptions or races cause it to be invoked multiple times,
resulting e.g. in uncontrolled growth of antipatterns
=> ensure HunspellRule.init is called at most once

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
Draft, possibly pending whether the rule should be set to `picky` or `en-US/CA`-only or something of that sort.
[Google Books Ngram Viewer data](https://books.google.com/ngrams/graph?content=have_INF+a+shower%2C+take_INF+a+shower&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t3%3B%2Chave_INF%20a%20shower%3B%2Cc0%3B%2Cs0%3B%3Bhave%20a%20shower%3B%2Cc0%3B%3Bhad%20a%20shower%3B%2Cc0%3B%3Bhaving%20a%20shower%3B%2Cc0%3B%3Bhas%20a%20shower%3B%2Cc0%3B.t3%3B%2Ctake_INF%20a%20shower%3B%2Cc0%3B%2Cs0%3B%3Btake%20a%20shower%3B%2Cc0%3B%3Btook%20a%20shower%3B%2Cc0%3B%3Btaking%20a%20shower%3B%2Cc0%3B%3Btaken%20a%20shower%3B%2Cc0%3B%3Btakes%20a%20shower%3B%2Cc0#t3%3B%2Chave_INF%20a%20shower%3B%2Cc0%3B%2Cs0%3B%3Bhave%20a%20shower%3B%2Cc0%3B%3Bhad%20a%20shower%3B%2Cc0%3B%3Bhaving%20a%20show …
=> [en] add rule HAVE_A_SHOWER

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/UnitConversionRule.java
fixes languagetooler-gmbh/languagetool-premium#2173
uncommonly used, so we don't want to suggest it
previously: hack, added as non-metric; leads to conversions from e.g.
dm3 to liter
=> remove decimeters from UnitConversionRule

languagetool-core/src/main/java/org/languagetool/AnalyzedSentence.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRulePerformer.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractTokenBasedRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RuleSet.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/AbstractPatternRulePerformerTest.java
track token indices by lemma/token text in AnalyzedSentence
if a pattern has a token with token/lemma hints and fixed offset from the start,
use these indices to narrow down the search space
7-10% speedup in `Main -l en` for me
=> PatternToken rules: match only from likely tokens if possible

languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleFilters.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java, languagetool-core/src/test/java/org/languagetool/rules/DemoRemoteRuleFilterTest.java, languagetool-core/src/test/java/org/languagetool/rules/GRPCRuleTest.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleFilterTest.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleFiltersTest.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/AbstractPatternRuleTest.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java, languagetool-core/src/test/resources/org/languagetool/rules/xx/remote-rule-filters.xml, languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/EnglishRemoteRuleFilterTest.java
using pattern rule syntax, in new file remote-rule-filters.xml
allow excluding matches from remote rules that have corresponding matches from rules in remote-rule-filters.xml
=> filters for remote rule results

languagetool-core/src/main/java/org/languagetool/rules/patterns/StringMatcher.java, languagetool-language-modules/de/src/main/java/org/languagetool/chunking/TokenPredicate.java
and use StringMatcher for further speedup
Some 7% speedup for me on `Main -l de`
#4168
=> [de] compile regexps in TokenPredicate just once, not on every call 

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Alternativensuche kennt das LanguageTool nicht, nur die falschen Wörter.
Siehe  #4243
=> Add Alternativensuche/N

languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleResult.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java
introduced by 250298d04af59d05d7b731efff686f6328d32f33
cached results were overwritten with empty list
need to distinguish in RemoteRuleResult.matchesForSentence between:
- not processed (null)
- processed but no matches (empty list)
- actual matches
=> fix bug in remote rule caching

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Rohrlöffel/NS statt Rührlöffel/NS
=> Add Rohrlöffel/NS

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Anti-patterns for AI suggestions:
- Uncommenting a previously commented anti-pattern for `MISSING_TO` (send him peace ➡️ send him to peace)
- Writing a new anti-pattern for `MISSING_IT` to never suggest inserting `it` before an `its` (Its been a long time ➡️ It Its been a long time)
=> Missing to missing it antipatterns

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
=> Add Gartenpump/S

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java, languagetool-core/src/main/java/org/languagetool/rules/CommaWhitespaceRule.java, languagetool-core/src/main/resources/org/languagetool/MessagesBundle.properties
WIP draft for review. Writing up some of my quick thoughts on messages while starting to implement some changes (see also https://forum.languagetool.org/t/en-guidelines-rules-for-messages/5350 from 1 year ago by Mike – if this is a better fit for the forum or the wiki, I can move it there):
1. Straightforward (i.e. simple syntactic structure), concise messages respect users' time.¹ Along with constrained vocabulary (reduce variants like `is deemed as`, `can be regarded as` → `can be considered`), it also makes it easier for non-native (ESL) speakers to understand them.
2. Avoid redundancy (`Consider an alternative.`, `Consider a replacement.`, `Double-check`), especially if we don't have any alternatives to suggest. Deictics (or indexicals) like `here`, or self-reference (e.g. `in formal …
=> [en] improve many messages

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Jusque, jusque à le et jusque aux sont des expressions fautives.
=> [fr] jusque

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
* Increase priority of `TO_TOO` to 1
When the user writes `to` but instead should write `too` causes issues for the replacement of prepositions head in HydraLEO as it suggests a different preposition instead of `too` while there is already an XML rule for that purpose.
* Code style improvements
- Group together the rules that need a higher priority than HydraLEO.
- Minor spacing modifications so that lines look more as columns.
- Re-order some (~15) RuleIDs according to their priority.
=> Increase TO_TOO priority to be higher than HydraLEO and code style improvements

languagetool-office-extension/src/main/resources/description.xml
The name, 'LanguageTool', was missing in Galician.
=> Added Galician

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
allow updating rule IDs used in matches without changing server configuration
rule ID from configuration only used for metrics
=> use rule IDs provided by remote server

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Schwimmerbereich/S
Schwimmerbereiche/NS
https://github.com/languagetool-org/languagetool/pull/4756
Hier sind falschen Wörter, die akzeptiert werden.
=> Add Nicht/Schwimmerbereich

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Revision of  \<message\> elements.
Shortening of \<short\> elements.
type for all categories (http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues)
Guillemets («»), instead of (' ").
There are no changes in the rules.
Added myself as contributor.
=> [gl] Clean-up; category types

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
Where I come from, 'etc.' needs a period mid-sentence, which LT editor misses. 
However, the rule has a lot of hits; I'll have to look more into the specifics of 'etc.' punctuation but I think most of what the rule detects is accurate.
=> [en] etc. punctuation

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Because of confusion in branches, this PR replaces this one : [https://github.com/languagetool-org/languagetool/pull/4727](url)
All feedbacks from Udo have been taken into account, except for "CF = Clubo de Futbol", for which I don't find a solution for the moment
=> Rm6 punctuation on cf

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
Genitiv-s bei Bodygas MAS-Form hinzugefügt.
=> Fix Genitiv-Form von Bodyguard

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/EnglishWordRepeatBeginningRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/EnglishWordRepeatBeginningRuleTest.java
Added feature to suggest different adverbs, when successive sentences start with the same adverb.
*Example*
Also, added a relative test case.
=> [en] Add adverb suggestions to EnglishWordRepeatBeginningRule (#4950)

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Clippings ('apocopes') were improved and can now be used.
Corrected two instances of degrees (were º)
Removed ¿ and ç
=> [gl]  Clippings - Improved and activated

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
@jaumeortola, when you have a minute (not urgent), could you look at this rule?
I was trying to port the WORD_CONTAINS_UNDERSCORE rule from English to French (TIRET_BAS). The main difference being that the underscore is not a token boundary in French. I thought I had adapted everything, but I'm getting a test failure I can't understand. I've run through a few possible solutions, but I cannot identify the problem.
Do you see what's going wrong? Hopefully I just oversaw something really simple...
=> [fr] add TIRET_BAS (WORD_CONTAINS_UNDERSCORE)

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Added a new rule for acronyms, which do not inflect for plural.
Removed rule about 'puntual', already set to off a long time ago: new meaning is now accepted in DRAG.
=> [gl] added Acronyms - Plural; removed Puntual

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
The rule was capturing 'acronyms' with just one uppercase letter, such as 'As', 'Os'. Fixed.
=> [gl] fixed capturing acronyms

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx
I use the LanguageTool SRX rules in a separate project, [srx-languagetool-ruby](https://github.com/amake/srx-languagetool-ruby). Thanks for providing such a comprehensive resource.
One point I find lacking about the existing rules is that there is no entry for Chinese. However the existing Japanese rules work perfectly well for both languages, so I would like to propose this small tweak to the mapping rules.
(I surmise that LanguageTool uses something different to segment Chinese, so I understand if you don't want to add a bunch of data that you don't need. But I figured this is small enough to be acceptable.)
=> Add mapping for Chinese to SRX rules

languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java
Make distinguishing temporarily denied requests (because of limits) and permanently blocked/forbidden requests easier.
Don't merge yet, wait for add-ons to adapt and show the correct error message.
=> [WIP] send HTTP code 429 instead of 403 for rate limiting

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
The two most common cases of misspelling. It is still limited to Homo but it doesn't list species, allowing for future additions as well as humorous uses.
=> [gl] binomial nomenclature

languagetool-core/src/main/java/org/languagetool/rules/IncorrectExample.java, languagetool-core/src/main/java/org/languagetool/rules/Rule.java
~1MB for en+de languages loaded
=> a more memory-efficient storage for examples and corrections

languagetool-core/src/main/java/org/languagetool/language/FastText.java, languagetool-core/src/main/java/org/languagetool/rules/RuleMatch.java, languagetool-core/src/test/java/org/languagetool/language/FasttextTest.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Buffering might have led to mix-ups in language detection
Laziness for suggestions can result in ignoring timeouts and incorrect metrics
=> No buffering for fasttext, compute suggestions in correct thread

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
Comma style rules have -50 priorities so I add HydraLEO missing comma rule ID to -51.
=> Have HydraLEO missing commas lower than comma style rules

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Die Mehrzahl wird nicht als Fehler erkannt.
Die Einzahl wird erkannt.
=> Rechtswale/NS statt Rechtswahle/NS

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
Old improvements that were never activated:
BE_PART_AGREEMENT_2
SV_AGREEMENT_NEG_QS
US_ONE_ENTITY[1] → picky
=> [en] activate improvements + picky tag

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
This rule will avoid FPs by the SPELLER_RULE and other rules, e.g. VIELZAHL_PLUS_SINGULAR[4]:
> von zahlreichen **Amateurfotograf***innen
current FP: Möglicher Tippfehler: Müsste dieses Wort im Plural stehen? → Amateurfotografen
=> [de] improved SUB_INNEN

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
Takes care of FPs:
> Warum muss **jeder Englisch** lernen?
Eliminates also TPs where the suggestion makes no sense (suggests plural, should be singular):
> **Jeder Kind** vergisst mal seinen Turnbeutel.
→ Jeder Kinder
Test results: 
[result_java_DE_AGREEMENT.zip](https://github.com/languagetool-org/languagetool/files/7019914/result_java_DE_AGREEMENT.zip)
=> [de] test AP against "jeder" FPs

languagetool-language-modules/de/pom.xml
build works fine because dependency is already part of other modules,
but gets marked as error in IntelliJ
=> add dependency to languagetool-language-modules/de

languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleConfig.java, languagetool-language-modules/de/src/main/java/org/languagetool/language/AustrianGerman.java, languagetool-language-modules/de/src/main/java/org/languagetool/language/GermanyGerman.java, languagetool-language-modules/de/src/main/java/org/languagetool/language/SwissGerman.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/AmericanEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/AustralianEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/BritishEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/CanadianEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/NewZealandEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/SouthAfricanEnglish.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/EnglishRemoteRuleSuppressMisspelledTest.java, languagetool-language-modules/es/src/main/java/org/languagetool/language/Spanish.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
add options to RemoteRule to filter out matches (`suppressMisspelledMatch`) or suggestions with misspellings (`suppressMisspelledSuggestions`)
allow application to only selected rule IDs via regex
added getDefaultSpellingRule() to Language
=> suppress misspelled for RemoteRules

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/DumontsHunspellDictionary.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/Hunspell.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellDictionary.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/RareWordsFinder.java
Users of IntelliJ IDEA currently have [problems](https://youtrack.jetbrains.com/issue/IDEA-251286) with `dumonts.hunspell.bindings.HunspellLibrary`. I want to introduce the ability of changing the default Hunspell library to a [pure-java version](https://javadoc.io/doc/org.apache.lucene/lucene-analyzers-common/latest/index.html) of Apache Lucene or any other (to support 32-bit platform for example).
Also, I'm not sure about `Hunspell::add` method, it doesn't seem to have been used anywhere.
=> Add ability to change Hunspell library in runtime

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
corrected small details + adding an AP for any use with 'plus' which is confusing, after reviewing today's diff, it appears that 90% of FP results are 'plus' results
- _depuis ce jour, il a plus d'argent_ 
could both mean :
- - _depuis ce jour, il n'a plus du tout d'argent_ 
- - _depuis ce jour, il a encore plus d'argent_
=> Rm69 p v pas corrections

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
I've seen that the app was correcting some uses of "avérer" with AVERE(premium1) instead of SAVERER_FAUX(open source), and some cases were not covered
I commented SAVERER_FAUX(os), SAVERER_VRAI(os) , AVERE(premium1) until the new merged rulegroup has been confirmed by night diff
=> [fr] add AVERER

languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java, languagetool-core/src/main/java/org/languagetool/tagging/ManualTagger.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/MultiWordChunker.java, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/removed.txt
Editing manually tab-separated files is annoying and frequently a waste of time because of errors and confusions. 
I suggest allowing both tabs and semicolons. It is not "beautiful", but it can be useful. In the future, we can replace all tabs with semicolons in all files.
=> allow tab or semicolon in files: multiword.txt, added.txt, removed.txt

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
@udomai 
@s-burst 
I have no clue if I'm doing this correctly, so I'm opening a PR with a super simple test AP.
There were a few disable contexts for 'thou', and even at the threshold that it's currently at, the rule suggests 'is' in this sentence:
> Some scholars rely on John 8:57: "thou are not yet fifty years old", making the earliest possible year for Jesus's birth c. 18 BC.
I have a lot more APs I want to write, one of them being to ignore things in quotes. 
So, this example will be subsumed into that anyway. But it is a test AP for now.
If this looks correct, please merge and I will add the rest. Thanks!
=> [en] add one simple AP to HYDRA_LEO_ARE_IS as a test

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling_en-GB.txt
Add 'freestanding' to spelling_en-GB.tx for Premium [3489](https://github.com/languagetooler-gmbh/languagetool-premium/issues/3489)
=> [en] add 'freestanding' to en-GB dict

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/tools/LtThreadPoolExecutor.java, languagetool-core/src/main/java/org/languagetool/tools/LtThreadPoolFactory.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/java/org/languagetool/server/UnavailableException.java
ThreadPoolExecutor only spawns threads beyond core pool if queue is full;
this never happened with our configuration
added maxTextCheckerThreads, textCheckerQueueSize
=> fixed thread pool configuration, new options

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/tagset.txt
Examples for Determiner contain two "an". First one would probably be just "a".
=> Typo fix in tagset for DT examples

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleLoader.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationRuleLoader.java
Custom PasswordAuthenticator [disturbs](https://youtrack.jetbrains.com/issue/IDEA-276949) IntelliJ IDEA proxy authentication process. We need a way to turn it off.
=> Add ability to prevent PasswordAuthenticator usage while loading rules

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleMetrics.java
use nanoTime uniformly
some errors from remote rules contain TimeoutException in stack trace, still log as errors
=> improve logging and timeout handling for remote rules

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
- made PROFANITY picky
- added rule GOOD_FLUCK
- added rules for 'retarded' and 'redskin' (part of PROFANITY, so picky as well)
- changed suggestion for [10] from 'Afro-American' (dated, not used anymore) to 'African American'
- turned off rules for 'illegal immigrant', 'bite me', and 'yankee' (they don't really make sense imo, but I didn't consult Grafana)
=> [en] improve PROFANITY

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
Now there are two HydraLEO missing comma models and they all start with `AI_HYDRA_LEO_MISSING_COMMA` . This PR checks whether the id starts with this string.
=> Set priority for all HL MCOMMA models

languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleFilters.java, languagetool-core/src/main/resources/org/languagetool/rules/remote-rules.xsd, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleFiltersTest.java, languagetool-core/src/test/resources/org/languagetool/rules/xx/remote-rule-filters.xml
Allow remote rule filters to match multiple rule IDs by treating their IDs as regular expressions
=> treat remote rule filters rule IDs as regexps

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleMetrics.java
to avoid requiring this dependency during JLanguageTool classloading,
with the goal to avoid bundling resilience4j with IntelliJ after updating to the new LanguageTool versions
=> JLanguageTool: move CallNotPermittedException dependency to RemoteRuleMetrics

languagetool-core/src/main/java/org/languagetool/rules/DictionarySpellMatchFilter.java, languagetool-server/src/test/java/org/languagetool/server/DictionarySpellMatchFilterTest.java
if only part of an accepted phrase was marked as a spelling error,
it wouldn't be filtered out by DictionarySpellMatchFilter
=> fix: partial matches of accepted phrases

languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleFilters.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleMetrics.java
load remote rule filters for SimpleGerman from .../de/remote-rule-filters.xml
track remote rule timeouts as timeouts in metrics
=> fix some errors and logging for remote rules

languagetool-language-modules/zh/pom.xml, languagetool-language-modules/zh/src/main/java/org/languagetool/tokenizers/zh/ChineseWordTokenizer.java, languagetool-language-modules/zh/src/main/resources/org/languagetool/rules/zh/grammar.xml, languagetool-language-modules/zh/src/test/java/org/languagetool/tagging/zh/ChineseTaggerTest.java, languagetool-language-modules/zh/src/test/java/org/languagetool/tokenizers/zh/ChineseWordTokenizerTest.java, pom.xml
1. Upgrade HanLP to version 1.8.2
2. Enable POS tagging function to get more accurate result.
3. Updated test cases.
=> (zh-CN) Hanlp v1.8.2 upgrade

languagetool-office-extension/src/main/resources/Addons.xcu
...which doesn't match the static structure of `officecfg/registry/schema/org/openoffice/Office/Addons.xcs` of OpenOffice.org-based projects and e.g. causes
> warn:configmgr:...:...:configmgr/source/xcuparser.cxx:159: bad set node <prop> member in "file:///.../.config/libreoffice/4/user/uno_packages/cache/uno_packages/....tmp_/LanguageTool-5.6.oxt/Addons.xcu"
on stderr during startup of LibreOffice debug builds
=> Remove spurious "Title" prop

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCPostProcessing.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRuleMatchFilter.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleConfig.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleMetrics.java, languagetool-core/src/main/java/org/languagetool/rules/Rule.java, languagetool-core/src/main/java/org/languagetool/rules/ml/MLServerProto.java, languagetool-core/src/main/java/org/languagetool/rules/ml/PostProcessingServerGrpc.java, languagetool-core/src/main/java/org/languagetool/tools/RuleMatchesAsJsonSerializer.java, languagetool-core/src/main/proto/ml_server.proto, languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java, languagetool-language-modules/es/src/main/java/org/languagetool/language/Spanish.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java
Implemented GRPCPostProcessing class
match filter that can transform computed matches 
allows e.g. resorting suggestions based on language models
=> Add new interface for external post-processing of matches

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
I didn't find a possibility to replace the whole suggestion list with a different list, so I added them to the top of the list instead.
=> [de] add "löchen" to GermanSpellerRule.java

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Evtl. als Ergänzung für AN_FUER_SICH.
In OpenThesaurus wird 'an und für sich' als umgangssprachlich angegeben.
AN_FUER_SICH[1] könnte evtl. so abgeändert werden, dass es sich auf die korrekte Schreibweise beschränkt (ohne Alternativvorschläge) und diese Regel hier könnte eine stilistische Ergänzung sein.
Macht das Sinn?
=> [de] improve AN_FUER_SICH

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Die neue Regel soll Fehler wie diesen erkennen:
> Weitere Informationen, Kontaktstellen und finden Betroffene hier.
In den Commits "v1" und "v2" habe ich den Marker unterschiedlich gesetzt, denn ich bin mir in diesem Fall nicht sicher, ob die Angabe einer `suggestion` sinnvoll ist.
Insbesondere bei der Kategorisierung, `id` und `name` bitte ich um Unterstützung, da ich noch nicht so vertraut mit dem „Regelwerk“ bin.
=> [de] rule suggestion: ENUM_SUB_UND_VER

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternTestTools.java
This is needed for IntelliJ that now inspects the pattern rules to see whether they need chunk tags. IntelliJ disables the chunker for English for being too expensive for an IDE, and it performs this analysis to avoid introducing false positives as a result.
=> make PatternToken.getExceptionList non-nullable and public

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRuleAntiPatterns1.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/VerbAgreementRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/VerbAgreementRuleTest.java
The antipatterns were tested against the German Tatoeba dataset, as well as ~100k other German sentences to make sure they don't cause any new false negatives.
=> Add antipatterns to German agreement and verb agreement rules.

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Ich habe die Korrekturen von Udo eingearbeitet und basierend auf dem Diff von heute noch ein paar antipattern ergänzt. Außerdem habe ich die Regeln für alle Adjektive, die auch adverbial gebraucht werden können, auf `default="off"` gesetzt.
=> [de] improve EINE_ORIGINAL_RECHNUNG_TEST

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
@udomai: Ergänzung eines Antipatterns für Fälle wie "Wobei standardmäßig jede unterstützte Sprache enthalten ist" und von entsprechenden untouched examples.
=> [de] improve INDEFINITPRONOMEN_ALS_SUBJEKT

languagetool-language-modules/es/src/main/java/org/languagetool/language/Spanish.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
French and Spanish spellcheckers have a priority of -100 so HydraLEO should have a lower priority.
=> Change priority of HydraLEO for FR and ES to be lower of the spellchecker

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: Ich habe MIR_DIR wie besprochen umgeschrieben und zwei APs ergänzt (das zweite ist für FPs wie "Erlaube mir dir mitzuteilen"). Nun sollte die Regel bei "Dazu fehlt mir dir Kraft" nicht mehr anschlagen. Als nächstes würde ich eine Regel schreiben, die für diesen Fall "mir die" vorschlägt.
=> [de] add APs for MIR_DIR

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
@udomai: Im SentenceSourceChecker schlägt so für "Dazu fehlt mir dir Kraft" nur noch "VERWECHSLUNG_MIR_DIR_MIR_DIE" und nicht mehr "MIR_DIR" und "CONFUSION_RULE_MIR_MIT_NEU" zu.
=> [de] prioritize VERWECHSLUNG_MIR_DIR_MIR_DIE over MIR_DIR

languagetool-core/src/main/java/org/languagetool/rules/patterns/Unifier.java
This speeds up `Main -l de` for me by ~10%
=> don't compute expensive historical readings during feature unification

languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java
The redisDatabase property already exists and works fine, it’s just missing from the known properties.
When deploying languagetool in a cluster with a shared redis database, this can be useful to avoid key conflicts
=> fix: add redisDatabase to known properties

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@udomai:
Additions to existing subrules & new subrules for the following cases:
- Invalid days ≤31 (i.e. april, june, september, november) written in numbers and with points; I wanted to include cases such as 29.2.2001 as well, but the corresponding subrule does not find them - do you have any idea why?
- Invalid days > 31 (Nació el 32 de enero)
- Invalid days > 31 written in numbers (Nació el 32/02/1989); I did not include dates without a year since this created too many Fps
-  Invalid months >12; to be discussed: should the American way of writing dates (month/day/year) be highlighted as an error?
See also issue 6829: https://github.com/languagetool-org/languagetool/issues/6729
=> [es] improve NUMBER_DAYS_MONTH

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
Addition of some antipatterns based on Matomo results. Subrule [8] now only includes cases where the month or day is smaller than 100 (09/50/2000 --> 09/05/2000) because there were too many FPs (phone numbers etc.). 
See also: https://github.com/languagetool-org/languagetool/issues/6729
=> [es] add APs NUMBER_DAYS_MONTH

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRulePerformer.java
this gives me 5-10% improvement in running `Main` with `de` language
=> perform the unification lazily, only when cheaper matching has fully succeeded

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/det_a.txt
"Ultra High-Definition TV"
- https://en.wikipedia.org/wiki/Ultra-high-definition_television
=> Correct 'a' for "UHD" + "UHDTV" (#4360)

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola: I finally had time to improve the rule for finding errors such as „malo amigo“ (see also https://github.com/languagetool-org/languagetool/pull/6689/files):
- I included the use of a coma as a second suggestion
- I exlcuded upper case „Bueno“ and „Malo“ 
- I removed all superfluous antipatterns
What do you think? Is the rule ready to go or should I still improve it?
Thank you for your feedback!
=> [es] add improved MALO_AMIGO_MAL_AMIGO

languagetool-language-modules/el/src/main/java/org/languagetool/rules/el/GreekWordRepeatBeginningRule.java, languagetool-language-modules/el/src/test/java/org/languagetool/rules/el/GreekWordRepeatBeginningRuleTest.java
Based on the Greek syntax, two or more successive sentences can start with the same article. Until now, the method isException() in GreekWordRepeatBeginningRule.java takes into consideration only definite articles. Hence, I added all the indefinite articles and a related test case.
=> Greek word repeat beginning rule

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
As discussed, it makes little to no sense that a simple character count should trigger a rule when Dutch word formation allows for longish compounds.
=> [nl][LANG_WOORD] Disable rule with many false positives

languagetool-language-modules/nl/src/main/resources/org/languagetool/resource/nl/disambiguation.xml, languagetool-language-modules/nl/src/main/resources/org/languagetool/resource/nl/spelling/ignore.txt, languagetool-language-modules/nl/src/main/resources/org/languagetool/resource/nl/spelling/spelling.txt
* I added a generic disambiguation rule that allows spelling of numbers that are followed by a letter (e.g., 2022b or 100k)
* I went through the most common words that our Dutch users add to their dictionaries, mostly anglicisms used in marketing and dev speech – I guess the Dutch are using a lot of English terms like we Germans
Please check and confirm @LanguageTool-AS
=> [nl] add spelling

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
These are the 2 sub-rules that had the worst acceptance since INSPECIFIEK has been disabled.
=> [nl][VAAG] Disable 2 sub-rules with highest disable rates

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
@St-ac-y I have added another antipattern here because the word "menos" wasn't being tagged as an adverb ("RG"), but as a noun, which ended up creating false alarms. Hopefully, this will fix it now.
=> [pt] New antipattern added to MAIS_MAS rule to fix FAs

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Commonly used word describing products that are using electronic paper, especially when it's possible to write on it.
https://www.google.com/search?q=%22E-Ink%22+site%3A*.de
https://de.wikipedia.org/wiki/Elektronisches_Papier
=> [de] add "E-Ink" to spelling.txt

languagetool-core/src/main/java/org/languagetool/markup/AnnotatedTextBuilder.java, languagetool-language-modules/en/src/test/java/org/languagetool/JLanguageToolTest.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/MorfologikAmericanSpellerRuleTest.java
Hidden characters \u202d \u202C \u00AD (soft hyphen) are treated as markup.
=> Improve annotated text

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@danielnaber: @tiff hatte vorgeschlagen, die Formen in ignore.txt statt in spelling.txt zu ergänzen.  (siehe: https://github.com/languagetool-org/languagetool/commit/f6968dc4ff7c3b97caeaa9c7ea61c40745fa1cc5#r79649970). In der added.txt und do-not-synthesize.txt habe ich sie drin gelassen. Ist das so okay?
=> [de] 'temp_off' EUERM_EUERN and add euerer/s/m/n euerm euern

languagetool-core/src/main/resources/org/languagetool/resource/disambiguation-global.xml
ODS (spreadsheet) already existed, but not the other common Open Document formats.
=> Add "odt" + "odf" + "odp" to filename extensions

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
"Ich möchte unseren Kunden jedwede Art des Netzwerkens ans Herz legen." Receives already the correct POS tag, but is not recognized by the spell checker.
=> [de] add "Netzwerkens" to spelling.txt

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/tagset.txt
In the French XML file, some PoS mentions are quite hazy:
- M nonfin
- M fin
These actually refers to tokens tagged with "Marker" PoS, nonfin (non-final) for commas, colon and semicolon, and fin (final) for dots. This commit adds a comment to the tag set file, to avoid confusion.
=> [fr] comment in the tagset.fr file (Marker tag, in MISC).

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
correct typo for chapôs (plural)
=> [fr] Dictionary changes/additions

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Entscheidung für "Cum-Ex" basierend auf der gängigeren Schreibweise (z.B. die [Zeit](https://www.zeit.de/politik/deutschland/2022-08/cum-ex-olaf-scholz-ausschuss-faq?utm_referrer=https%3A%2F%2Fwww.google.com%2F), die [Tagesschau ](https://www.tagesschau.de/investigativ/wdr/cum-ex-171.html)und die [Süddeutsche](https://www.sueddeutsche.de/thema/Cum-Ex), der Einschätzung als "Eigenname" und der Häufigkeit der Treffer im Vergleich (https://corpora.uni-leipzig.de/de/res?corpusId=deu_news_2021&word=Cum-Ex). 
Kategorie von Grammatik zu Style geändert.
=> Luisa cum ex

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
Feedback from a user on Twitter shows that "cryptoactif" gets a suggestion → "cryptojuif". 
The word "cryptoactif" is recent (related to all the new vocabulary around cryptocurrencies) and need to be added to the dictionary files.
=> [fr] Word "cryptoactif" gets FP and bad suggestion

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace_anglicism.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace_picky.txt
Quite many words in [replace_anglisicm.txt](C:\Users\steib\IdeaProjects\languagetool\languagetool-language-modules\fr\src\main\resources\org\languagetool\rules\fr\replace_anglicism.txt) and[ replace.txt](C:\Users\steib\IdeaProjects\languagetool\languagetool-language-modules\fr\src\main\resources\org\languagetool\rules\fr\replace.txt) are to be considered picky. To do so, a new file is needed, created in this pull request.
=> [fr] Creating replace_picky file

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-CH/grammar.xml
Da grammal.xml de-CH OS ist, sollte die Regel schon beim User sein (wurde gestern activated), im Editor (wenn de-CH eingestellt ist) greift jedoch noch die bestehende Regel WAEHRUNGSANGABEN_KOMMA für de-DE. Daher wurde jetzt die Prio im German.java hochgesetzt für die de-CH Regel.
=> [de] rule prio change

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/DumontsHunspellDictionary.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/Hunspell.java, pom.xml
Updates the dependency on https://gitlab.com/dumonts/hunspell-java to the newly released 2.0.0
Removes the redundant re-implementation of `spell`, `suggest` and `add` methods.
relates to #7045
=> Update dumonts/hunspell to 2.1.1

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-DE-AT/grammar.xml
Regel WAEHRUNGSANGABEN_KOMMA aus grammar-premium4 entfernt und zu grammar de-DE-AT Open Source hinzugefügt, um Konflikte mit WAEHRUNGSANGABEN_CHF in grammar de-CH zu vermeiden.
=> [de] moved rule from grammar-premium4 to grammar de-DE-AT OS

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
As explained in [his issue](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4820), and an exception is added to remote-rule-filters.xml.
=> [fr] AI_FR_HYDRA_LEO_MISSING_COMMA adding an exception to the filter

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Wenn Partizipien (wie "wegdelegiert") im spelling.txt als Adjektive deklariert werden, kann es zu vielen FPs bzw. falschen suggestions kommen (wie [hier](https://regression.languagetoolplus.com/via-http/2022-12-05/de-DE/result_grammar-premium2_WORDEN_GEWORDEN_UNTERSCHIED[4].html)) - ist es ok, wenn ich in solchen Fällen einfach das "/A" im spelling entferne?
=> [de] is PA1

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
After adding Salammbô in dictionary files, nightly diff showed through AGREEMENT_POSTPONED_ADJ that obviously Salammbô is both the name of the book (masculine) _and_ the name of the character (feminine).
This commit makes Salammbô **Z e s** to avoid trouble.
=> [fr] Salammbô Z e s

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
Ich habe WAR_WAHR höher priorisiert als KOMMA_ZWISCHEN_HAUPT_UND_NEBENSATZ, um derartige Fälle zu vermeiden: 
"Das ist höchst wahrscheinlich **war**."
=> _ist - war_ scheint, als wären 2 Verben im Satz, daher schlägt die Komma-Regel an, sobald _wahr_ korrigiert ist, fällt die Komma-Regel weg (schlägt korrekterweise nicht mehr an), stattdessen schlägt (ebenfalls korrekterweise) HÖCHST_WAHRSCHEINLICH an.
=> [de] rule added

languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-standalone/src/test/java/org/languagetool/LanguageTest.java
Allow using shared JLanguageTool instances from rules for various purposes.
@jaumeortola Can you see if this works for you? And if so, switch the other places where this is already done to use the new method?
=> feat(core): added createDefaultJLanguageTool to Language

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Modified APs to avoid some of the FNs (https://internal1.languagetool.org/regression-tests/via-http/2023-01-19/de-DE/result_grammar_FEHLERHAFTES_KOMMA_ALLG[1].html)
=> Improve fehlerhaftes komma allg

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
Prio change rückgängig (weil im diff alle rausgefallen sind) (rule ist wieder temp_off zum erneuten Testen)
=> [de] deleted

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://www.freiepresse.de/blaulicht-meldungen/neumark-vorfahrtsfehler-hoher-sachschaden-artikel11900801 https://www.ostsee-zeitung.de/lokales/vorpommern-ruegen/ruegen/vorfahrtsfehler-autos-kollidieren-bei-samtens-auf-ruegen-AOFHAO5JXFJI3ETLHMYLODERUU.html https://www.rnd.de/panorama/nach-vorfahrtsfehler-vier-menschen-schwer-verletzt-S3RURW2VKAKK2HHSXHLQULDYSY.html
=> [de] add "Vorfahrtsfehler" to spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Alternate form of "Vorfahrtstraße" https://www.duden.de/rechtschreibung/Vorfahrtsstrasze
=> [de] add "Vorfahrtsstraße" to spelling.txt

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola @maphjo after reviewing the nightly diff, default="temp_off" has been removed from EX_ALTO_CARGO rule
=> [es] removed temp_off from rule ex alto cargo

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola the rule has been removed from the OS repository (grammar.xml)
=> [es] removed rule NO_SEPARADO

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Writing antipatterns for AI_FR_HYDRA_LEO_MISSING_COMMA to fix:
-  [[fr] Non necessary comma#5042](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5042)
- [[fr] Comma#5057](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5057)
=> [fr] remote-rule-filters

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
> in dem Fall ist es besser, in `GermanSpellerRule.getOnlySuggestions()` eine entsprechende Zeile hinzuzufügen
https://github.com/languagetool-org/languagetool/commit/c846f22126f6daf1b3d57485e6b7c098bf20778b#r101629775
=> [de] added words to a different file

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Concludes low-hanging fruit for `REPLACEMENT_VERB_FORM`
[#115](https://github.com/languagetooler-gmbh/LECToR/issues/115)
=> [en] AI antipatterns - 03/02/2023

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Removed the comma from this rule since formal emails often contain comma > new line.
=> [nl] improved rule EINDE_KOMMA

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Rule overlapped with MITS_TENZIJ. This word is too common to suggest otherwise.
=> [nl] disabled rule TENZIJ

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Unpopular rule, this is commonly used. Also no good alternative suggestions available
=> [nl] disabled rule WAT_BETREFT

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, this is used too often in formal context to suggest alternatives
=> [nl] disabled rule DOOR_MIDDEL_VAN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, this is used too often in formal context to suggest alternatives
=> [nl] disabled rule AAN_DE_HAND_VAN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, this is used too often in formal context to suggest alternatives
=> [nl] disabled rule OP_BASIS_VAN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, this is used too often in formal context to suggest alternatives
=> [nl] disabled rule OP_HET_GEBIED_VAN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, still very common to use in professional context. Unpopular rule
=> [nl] disabled rule WERKZAAM_ZIJN

languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
To fix the FR part of https://github.com/languagetooler-gmbh/languagetool-premium/issues/5220
The rule shows **grammalecte_gv1__imp_verbe_groupe3_d__b2_** in Editor and Grafana but "grammalecte" at the beginning never appears in this file (looks like a prefix).
@jaumeortola please advise if something is wrong here, thanks!
=> Grammalecte

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-DE-AT/grammar.xml
https://regression.languagetoolplus.com/via-http/2023-03-16/de-DE/result_grammar_ANREDE_KOMMA_2[1].html
=> [de] removed UNKNOWN

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
I'm not sure why the sentence __<example correction="">Movie <marker>film</marker> seen in theaters in the United States runs at 24 frames per second, which is sufficient to create the illusion of continuous movement.</example>__
is not picked up by this AP:
```
<rule>
<pattern>
<token chunk="B-NP-singular"/>
<marker>
<and>
<token chunk="E-NP-singular"/>
<token postag="NN:UN"/>
</and>
</marker>
</pattern>
<example correction="">We are gearing to win some Court cases, but the <marker>case</marker> is dragging on.</example>
<example correction="">His <marker>composition</marker> is by far the best of all.</example>
<example correction="">How are you getting along with your <marker>study</marker>?</example>
</rule>
```
__movie__ is chunked as `B-NP-singular` and __film__ is chunked as …
=> [en] added APs for AI_EN_LECTOR_REPLACEMENT_NOUN_NUMBER

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/UnitConversionRuleTest.java
Fix problems with regexes matching negative numbers because of use of the word boundary meta-character
Addresses the problem outlined here: https://forum.languagetool.org/t/temperature/8881
=> fix[core]: match negative numbers in AbstractUnitConversionRule

languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Make filtering out matches of rules when the matched word is in the dictionary of a user the default behavior.
=> feat(core): enable filterDictionaryMatches by default

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5459
First batch migration for untagged style rules from grammar.xml to style.xml.
This first batch contains the rules that we consider 100% style related.
- Total rules migrated: 15
- New IDs and Names created for rules that were separated from a rulegroup
=> [fr] Style migration batch1

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To fix [[fr]: Bug in CONFUSION_ORTHOGRAPHIQUE[7] (Solutionner)#5592](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5592)
- CONFUSION_ORTHOGRAPHIQUE[7] is now RESOUDRE_OU_SOLUTIONNER in Style file.
- Removing spurious postag=".*" (probable culprit of the apparition of brackets in suggestion box in some cases).
- Slight change of suggestion sentence.
=> [fr] RESOUDRE_OU_SOLUTIONNER

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
New style category created for "Foreign_terms" tag (tag not implemented yet, but will be available soon)
Before this commit, we had 2 Anglicism categories:
- CAT_ANGLICISMES_PICKY
- CAT_ANGLICISMES which included pure anglicisms, calques and partially adapted loanwords
Now we have 3:
- CAT_ANGLICISMES_PICKY (remains untouched)
- CAT_ANGLICISMES which now includes only calques and partially adapted loanwords
- CAT_ANGLICISMES_FOREIGN_TERMS includes only pure anglicisms, and therefore can be later tagged with "Foreign_terms"
=> [fr] CAT_ANGLICISMES_Reorganized

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Closes languagetooler-gmbh/languagetool-premium#5572.
- when replacing incorrect prepositions, the corrected forms were not taking into account obligatory contractions;
- as such, 'com a' was being corrected to 'a a', instead of 'à';
- the solution required many different rules, as the substitutions here are not trivial (a + a = à, but a + o = ao), and this was further complicated by special forms of the 'com' preposition ('comigo', 'conosco', etc.).
I do still have some questions, though, so bear with me:
* the suggestions frequently include a lot more than what is to be corrected, e.g. `habituar-me com a` -> `habituar-me à`; when writing rules, I've changed those to simply `com a` -> `à`, but this could have been part of a broader policy – is it?
* there's behaviour for the 'com calma' …
=> [pt] Modify pt grammar to address issue #5572

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- closes languagetooler-gmbh/languagetool-premium#5538;
- really simple initial version taking care only of clearly ungrammatical epistemic modal double infinitives;
- e.g. 'ele dever ter ido embora', ~'poder ter chovido mais cedo'~
- methinks it's safe to assume these are typos.
=> [pt] Add DOUBLE_INFINITIVE rulegroup

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address week 2 in: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5596
- 24 likely unimprovable temp_off rules deleted
- 1 temp_off remains in temp_off but will have an issue opened for improvement
- 1 temp_off is now active
- 1 temp_off rule has been moved to style, has been assigned an ID "FILER_PARTIR" + name and is now activate (new AP added for "filer un mauvais coton")
=> [fr] Temp_off/Off rules week 2

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- prevent flags from adverbs starting with 'de';
- add any number of potential adverbs before the actual verbal argument;
- add inflected="yes" so we get more forms.
Just something I saw the other day using the editor and thought it could benefit from a quick improvement.
=> [pt] Improve CONSISTE_DE_BR grammar rule

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/DumontsHunspellDictionary.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/Hunspell.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellDictionary.java
It changes HunspellDictionary interface to add  `HunspellDictionary#isClosed` method to indicate a status of implementation of  `HunspellDictionary`. Hunspell class will check its status. When it is closed status, Hunspell class invalidate cache and create new object. Otherwise, user cause a JVM crash (segmentation fault) by  accessing to freed JNA object. 
Here is an issue on a user project, OmegaT that report crash when reloading a session.
https://sourceforge.net/p/omegat/bugs/1182/
A log message from JVM is here
https://gist.github.com/mohad12211/fe2ebfd71469b876c41a32e84c661e12
=> fix: crash when closing and getting hunspell object

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- issue was affecting performance of grammar rule `AGENTE_BR` (cf. [here](https://analytics.languagetoolplus.com/matomo/index.php?module=Widgetize&action=iframe&secondaryDimension=eventName&moduleToWidgetize=Events&actionToWidgetize=getAction&idSite=18&period=day&date=yesterday&flat=1&filter_column=label&show_dimensions=1&filter_pattern=AGENTE_BR));
- made it slightly less aggressive, but not too much so, hopefully.
=> [pt] Fix A_PREPOSITION rule 6 in disambiguator

languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRule.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationRuleHandler.java, languagetool-core/src/main/resources/org/languagetool/resource/disambiguation.xsd, languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/disambiguation.xml, languagetool-language-modules/ca/src/test/java/org/languagetool/JLanguageToolTest.java
An easy way of adding chunk tags from disambiguation.xml.
This will be very useful for all Romance languages.
`action="addchunk"` will be similar to `action="add"` but the tag will be added to the chunk tags.
=> disambiguation: add chunktags

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5766
Style rules have been reviewed and the new `general` tone tag has been applied where it's compatible (mostly replacing the “clarity” tone tag)
General tone tag count: 90 (including a few rulegroups)
Example of rules that have been tagged as general:
- Rules related to conventions, Kwh, Kelvin, Knot, etc.
- FR repeated words which include things like "C'est pour le <marker>b b</marker> de Caroline."
- Some rules addressing completely incorrect structures and can be found in the `"CAT_ANGLICISMES" name="Anglicismes (calques, emprunts directs, etc.)"` category and `id="CAT_REGIONALISMES"`
- Some rules from `id="CAT_REGLES_DE_BASE`
Additionally, the rule FILER_PARTIR has been deleted due to bad results in …
=> [fr] Style general tone tag applied

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of:https://github.com/languagetooler-gmbh/languagetool-premium/issues/5842
More details in https://docs.google.com/spreadsheets/d/18ZEBC_s8MxBW4HwIi_TIoRfLU2UM8ih8Kwg4Gr4H3I0/edit?usp=sharing
Moving Premium **grammar** rules to OS **style** rules
- PONCTUATION_DOUBLE
- POINT_MAIS
- VIRGULE_EXPRESSIONS_FIGEES
PR for Premium:
https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/667
=> [fr] OS from Premium grammar -> style rules migration

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of:https://github.com/languagetooler-gmbh/languagetool-premium/issues/5842
More details in https://docs.google.com/spreadsheets/d/18ZEBC_s8MxBW4HwIi_TIoRfLU2UM8ih8Kwg4Gr4H3I0/edit?usp=sharing
Moving Premium **grammar** rules to OS **style** rules
- TIRET ([⚠️](https://emojipedia.org/fr/symbole-d-avertissement/)now **TIRET_LONG**) subrules 12,17,18 about "tiret long"
Moving Premium **grammar** rules to OS **grammar** rules
- TIRET all other subrules
PR for Premium:
https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/668
=> [fr] OS from Premium grammar -> style AND grammar rules migration

languagetool-core/src/main/java/org/languagetool/rules/UppercaseSentenceStartRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/UppercaseSentenceStartRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/UppercaseSentenceStartRuleTest.java
- pt-BR introduces dialogue with dash chars, so we need to check if the first char after a sentence-initial dash is uppercase;
- add hyphen, n-dash, and m-dash to `UppercaseSentenceStartRule` logic *only if* the locale is Portuguese (must add all three because the rule to convert them to m-dashes is (and should be) `picky`);
- we recognise other locales may not want that behaviour, so that's PT-only, which requires some goofy logic, but I always prefer goofiness to repeating strings, where applicable;
- add a PT test class for this, and add a couple of tests to EN just to be sure everything is as it should be.
=> [pt] Require upcasing after initial dashes

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- add an explicit `academic` tag to them;
- improve the message – no need for explicit mention of 'PhD', just say 'theses or dissertations', that should be enough.
Not sure if these rules also shouldn't be tagged as `scientific`.
=> [pt] Improve tagging and messages for PhD rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
... started as an improvement to `paragrafo`, but the `dê`/`dá` errors from the annotation task gave me so much anxiety I simply had to do something about them, so here it is.
I tried using only very frequent collocations of 'dar' so as to restrict the matches to very likely cases, looks like it works, very few FPs.
=> [pt] Improve missing diacritic detection in dê/dá

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
Der Ist-Zustand:
> SoSe 2024 [true-negative]
> **WiSe** 2024 [false-positive]
Ich habe direkt beide hinzugefügt, nur um sicherzugehen.
Falls das nicht allgemein bekannt ist:
SoSe = Sommersemester, WiSe = Wintersemester
=> [de] add SoSe/WiSe to spelling ignorelist

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/style.xml
[#5050](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5050)
[#5047](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5047)
Deleted URLs were either:
- Overriding the **intended** [languagetool.org/insights/](https://languagetool.org/insights/) URL (conflict)
- Leading to 404s/broken
=> [en] update URLs/resolve conflicts

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Addressing a couple of temp disables for stuff like `que de jeito nenhum`. Technically those should be surrounded by commas but that's a different problem.
=> [pt] Add APs to ACCENTUATED_PARONYMS_DE

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
Fixes for sub-rules 4 and 5 were trivial, just avoiding initialisms.
The fix for rules 7 and 8 are more about restricting the matching of reflexive verbs.
Closes languagetooler-gmbh/languagetool-premium#5920.
=> [pt] Improve `INFORMAL_2SG_BR`

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5043
4 rules have been linked to blog posts, one of the rules already had an blog article url, but the new blog article seems to fit better.
Typo in rule ID fixed
=> [fr] Rule linking OS CW22

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Adding instructions for OS contributors to use tone_tags, as per https://github.com/languagetooler-gmbh/languagetool-premium/issues/5761.
=> [fr] Adding instruction on Tone_Tags and WG to OS style file

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5986
Added AP to the AI_ES_HYDRA_LEO_CP_QUIEN_QUIENTILDE rule.
@jaumeortola please, merge if it is correct. This is my first AP for such rules 🙈
=> [es] added AP to remote rule

languagetool-language-modules/sv/src/main/java/org/languagetool/language/Swedish.java, languagetool-language-modules/sv/src/main/java/org/languagetool/rules/sv/WordCoherencyRule.java
Adding the WordCoherencyRule class for Swedish to start using the pairs in /sv/coherency.txt.
=> [sv] Adding the WordCoherencyRule for Swedish

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- keep rule 2 as `temp_off`, but I've added an AP that should fix it;
- for rule 6, results seem encouraging: https://regression.languagetoolplus.com/via-http/2023-07-21/pt-BR_full/result_grammar_ACCENTUATED_PARONYMS_DA%5B6%5D.html
=> [pt] Enable working ACCENTUATED_PARONYMS_DA rules

languagetool-language-modules/fr/src/main/java/org/languagetool/language/BelgianFrench.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/CanadianFrench.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/SwissFrench.java, languagetool-language-modules/fr/src/main/resources/META-INF/org/languagetool/language-module.properties
The new variants (fr-CH, fr-BE, fr-CA) extend the default variant (fr, fr-FR) with disabled and enabled rules by default.
=> [fr] new French variants: CH, BE, CA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, Pedro and Susana,
I found out that the rule already existed, but it was from 2020?
So, I have rewritten it to make it simpler and added there a subrule to deal with my previous pull request which I am going to delete.
The results of this subrule were zero (no hits).
[2.txt](https://github.com/languagetool-org/languagetool/files/12153100/2.txt)
Thanks!
=> [pt] Rewrote and enhanced rule ID:FAZER_USO_DE-USAR-RECORRER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
An antipattern.
Depends on #9031
=> [pt-PT] Added AP to rule ID:PASSAR_TEMPO_DECORRER_TEMPO

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://de.wiktionary.org/wiki/R%C3%BCckkunft
=> [de] add "Rückkunft" to spelling

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of: https://github.com/languagetooler-gmbh/task-force-french/issues/33.
→ Anglicisms replacement rules should be moved to Style. This is the PR for OS.
<html>
<head>
</head>
<body>
Old name | New name | Other change
-- | -- | --
FAKE_NEWS | ANGLICISME_FAKE_NEWS |  
MEDIA |   |  
PAS_DE_TRAIT_UNION | ANGLICISME_SEX_TOY |  
TRAIT_UNION | ANGLICISME_MOBILE_HOME |  
HEURES |   | Message changed
HEURES |   | Message changed
HEURES |   | Message changed
TITRE_M |   | Message changed
</body>
</html>
- MEDIA wasn't moved, since the rule really concerns the word media in French.
- HEURES subrules were not moved, and the error message was modified from `<message>Cette écriture peut être considérée comme un anglicisme.</message>` to `<message>Cette notation correspond à l'usage dans …
=> [fr] anglicisms cleanup

languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/BrazilianPortugueseSimpleReplaceRuleTest.java
Tests will fail if these stop matching for whatever reason.
=> [pt] Add BrazilianPortugueseSimpleReplaceRuleTest

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
=> [pt-PT] Added AP to rule ID:FORMAL_T-V_DISTINCTION

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
An antipattern to fix a ton of false positives:
BEFORE:
```
Portuguese (Portugal): 110 total matches
Portuguese (Portugal): 599999 total sentences considered
```
AFTER:
```
Portuguese (Portugal): 98 total matches
Portuguese (Portugal): 599999 total sentences considered
```
=> [pt-PT] Added AP to rule ID:SIMPLIFICAR_À_VERBO_DE

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of https://github.com/languagetooler-gmbh/task-force-french/issues/41
After checking off → temp_off rules in diff:
Removed rules: 
- HIGH_TECH
- TRAIL
- EXCLUSIF_A
- FORM
- EMETTRE_UN_RECU
=> [fr] Cleanup on anglicisms after diff

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of https://github.com/languagetooler-gmbh/task-force-french/issues/50
- **123 rules removed** (target words that are now in main dictionnaries Larousse and/or Robert)
- Category CAT_ANGLICISMES_FOREIGN_TERMS **renamed** CAT_CALQUES (technically it's all calques rules)
- Addition of picky tag to categories CAT_CALQUES and CAT_ANGLICISMES_FOREIGN_TERMS
- **Deletion** of category ANGLICISMS_PICKY, **content of that category moved** to CAT_CALQUES or CAT_ANGLICISMES_FOREIGN_TERMS (both of them being picky now)
=> [fr] cleanup anglicisms

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
What it says on the tin; just replacing some inconsistent `"` and `'` with `&quot;` for a more polished feel for the end user.
Relates to languagetooler-gmbh/languagetool-premium#5956
=> [pt] Replace quotes in all XML files

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/BrazilianPortugueseReplaceRule.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
The original message was a little janky. 'Em português de Portugal' is ungrammatical.
=> [pt] Fix message for PT/BR replace rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
I've finally got fed up with all the `profa` and `dra` in the logs. This should address it. The list of abbreviations is relatively small and unambiguous, to keep things simple. A good candidate for a picky typography rule.
We can, in the future, add sister rules for stuff like `Engo.`, but I feel those will be much rarer anyway.
---
There are other abbreviations that might require the superscript in some situations, but there is very limited support for other superscript characters in most fonts (despite some [Unicode support](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts), though do note the caveat with regards to their size and position). I'd steer clear of adding support for those more obscure cases for now.
=> [pt] Add ABREVIATURAS_FEMININAS_COM_SOBRESCRITO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wikipedia.txt
Simple rule to detect incorrect 'encima' and replace with 'em cima'. Since the verb 'encimar' is technically a thing, we're not quite so aggressive here, but I think these rules should take care of the vast majority of hits anyway.
=> [pt] Add ENCIMA_LOCUCAO rule

languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/CheckCallable.java
This seems a better alternative to https://github.com/languagetool-org/languagetool/pull/9167
This way we can use this method for different purposes, and we can keep the default parameters.
=> checkallable: use default parameters when parameters is empty

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Related to: https://github.com/languagetooler-gmbh/task-force-french/issues/43
- ESPACE_UNITES some FPs have been fixed, mostly related to postal codes
- TOTALEMENT rule moved to style (temp_off removed)
=> [fr] ESPACE_UNITES improved

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
[Results](https://internal1.languagetool.org/regression-tests/via-http/2023-08-25/pt-BR/result_grammar_ABREVIATURAS_FEMININAS_COM_SOBRESCRITO%5B1%5D.html) are solid.
=> [pt] Enable ABREVIATURAS_FEMININAS_COM_SOBRESCRITO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
This is one of those things that's really stigmatised in pt-BR for some reason, so it'd be nice to cover at least the most obvious cases.
Deciding when the `mim` stands for a 1SG subject and when it doesn't is not that trivial, so there might be a handful of false negatives to iron out later, but for now I think what we have here should introduce more TPs than FPs.
Since this is formality-agnostic, we're not transforming 'pra' into 'para'.
=> [pt] Add PARA_MIM_FAZER rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
=> [pt] Added AP to rule ID:PHD_TESE_PROCURAR_PROVAR_PROVARA

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
An offshoot from the recent agreement issues. These appear to be frequently disabled by users, and indeed using the masculine there actually _sounds_ off to me, so I think we should make it `picky` and let users decide.
=> [pt] Add DUAS_MILHOES and AS_MILHARES_DE_PESSOAS rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Per latest [diff](https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR/), no FPs on either rule.
=> [pt] Enable MILHARES_DE_PESSOAS and DUAS_MILHÕES rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Logic and AP updates based on [diff results](https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR/):
- remove adj/pctp that are also nouns (and a couple of other words separately due to disambiguation issues);
- add a bunch of examples for testing.
=> [pt] Improve performance of MELHOR_EDUCADO and MAIS_BEM_MELHORES

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Per [nightlies](https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR_full/index.html), no FPs.
=> [pt] Enable CONCORDANCIA_SOBRESCRITO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
[No FPs](https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR_full/result_grammar_PER_CAPTA%5B1%5D.html), looks ready.
=> [pt] Enable PER_CAPTA rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Kelvin rule has no hits, centigrade one has [no FPs](https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR_full/result_style_GRAU_CENTIGRADO%5B1%5D.html).
=> [pt] Enable new scientific rules

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
@jaumeortola Added AP to solve this issue.
=> [es] added AP to AI_ES_HYDRA_LEO_MISSING_COMMA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
No FPs, per nightlies (below), but I thought we might also improve the agreement only of determiners adjacent to the expressions. Not handling adjectives and other stuff requiring more complex logic, as it doesn't look those will be very frequent.
https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR_full/result_style_PESO_MOLECULAR%5B1%5D.html
https://regression.languagetoolplus.com/via-http/2023-09-01/pt-BR_full/result_style_NUMERO_DE_AVOGADRO%5B1%5D.html
=> [pt] Improve agreement of new scientific rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- `EM_MEADO`;
- `MELHOR_EDUCADO`;
- `MAIS_BEM_MELHORES`;
- improve pattern of `CONC_NUM_GEN_O_SUAS`;
- improve pattern of `NUMERO_DE_MOLS`, `PESO_MOLECULAR`, and `SEM_ABRIGO`.
`PARA_MIM_FAZER` is still not ready for primetime.
=> [pt] Enable rules for w36 deployment

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
DICO ADD
- these words are entering the new Robert Edition
- words are added with variations if needed
```
phytochimique
Brindisi
guideline
Idir (prénom)
touchpad
espresso
flash-mob
MerciApp
bader
badant
klettes (Belgian word)
instagrammable
greenwashing (est maintenant dans le dico)
vélorution
bibimbap
nutri-score
flexoffice
```
=> [fr] Adding new words entering dics in 2023-24

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/replace.txt
1st commit: eventually, I decided not to add it to the `recommendation.csv`, but  added _Vermögensteuer_ to `ignore.txt`, so both variants (_Vermögenssteuer_ and _Vermögensteuer_) are accepted by the speller but only _Vermögenssteuer_ will be suggested (see comments [here](https://github.com/languagetool-org/languagetool/pull/9252))
=> Improvements

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
Addition to dictionary files 
Even if the word "_pédosexuels_" isn't in the main dictionaries (Larousse, Robert, TLFi) the Cordial has [an entry for it ](https://www.cordial.fr/dictionnaire/definition/p%C3%A9dosexuel.php#:~:text=D%C3%A9finition%20de%20p%C3%A9dosexuel&text=Personne%20qui%20manifeste%20une%20attirance%20sexuelle%20pour%20les%20enfants.). Also  the suggestion displayed by LT convey a social judgement that's not acceptable. 
See https://twitter.com/Vince_NXi/status/1700148798985519264
=> [fr] Dics addition

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @susanaboatto  and @p-goulart 
I was looking at the nightly results and there were several false positives, so I have fixed them.
Here is the fix.
In the next nightly results, I will see if the FPs are all gone and if so, I will remove the temp_off.
Thanks!
=> [pt] Fixed FPs in rule ID:TOMAR_ASSUMIR

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- Improved due to [very bad performance](https://internal1.languagetool.org/grafana/d/BY_CNDHGz/rule-events-analysis?orgId=1&from=now-30d&to=now&var-rule_id=POST-IT&var-language=pt)
- Changed suggestions to include the actual brand name (Post-it), and a more popular alternative ("lembrete" as opposed to the former choice, "papel adesivo")
- Marked as "picky" because `post-it` as a common noun is becoming popularized.
=> [pt] improve POST-IT

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/verbs.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- update disambiguator for weird poder/podar suggestions;
- add 'acontencer' and 'ocorrer' to non-impersonal verbs entity.
Only changed examples in sub-rule 1, so leaving that as it is. Adding `temp_off` only to the new sub-rule.
=> [pt] Update NON_IMPERSONAL_VERBS[2]

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
The disable contexts for this rule are always something to do with some named entity, so I've decided to merge the APs into a blanket block of the rule before anything starting with a capital letter. Let's see.
=> [pt] Broaden AP for CONC_NUM_GEN_O_SUAS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Here is an antipattern.
In a 900 000-sentence check, it didn't remove a single hit.
This raises the question:
`<token inflected='yes' regexp='no'>ser</token> `
Should it accept all verbs, or just verb “ser” and others we may find?
https://github.com/languagetool-org/languagetool/issues/9299
Thanks!
=> [pt] Added antipattern to rule ID:LINKING_VERB_PREDICATE_AGREEMENT

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
The FPs from the nightly should be taken care of. I ran this on the usual corpus and I think the results are okay – in every case, either the commas or the replacement with 'eu' should fix it.
(I'm also experimenting with giving sub-rules more descriptive IDs. Let's see how this works.)
=> [pt] Update PARA_MIM_FAZER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- also minor updates to cover newly uncovered rules
---
Diff is very encouraging, other than the issue with unification discovered for rules 13[ABC].
=> [pt] Fix unification in new agreement sub-rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Originally, I thought of updating `CRASE_CONFUSION`, but that rule relies on an entity containing verbs that 'require crasis', and there could be unintended consequences if we added 'sair' there, since it's really intransitive. It's a simple rule and a little stricter.
=> [pt] Add SAIR_AS_RUAS rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
We've improved the [nightly results](https://internal1.languagetool.org/regression-tests/via-http/2023-09-15/pt-BR/result_grammar_PARA_MIM_FAZER_GERAL%5B4%5D.html) and I think this rule should be ready for production.
=> [pt] Enable PARA_MIM_FAZER

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- Enable subrule in CONFUSAO_À_HÁ
- Enable IMIGRAR_PARA and EMIGRAR_DE
- Add disambiguation rule for tão to avoid confusion (rule should be expanded at some point)
- Make TOMAR_ASSUMIR goal specific
=> [pt] enable rules, add disambiguation rule for "tão", make TOMAR_ASSUMIR goal specific

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
cf. [this Slack thread](https://languagetooler.slack.com/archives/C046J7G16CT/p1695109089110239?thread_ts=1695021479.084599&cid=C046J7G16CT)
=> [pt] Add URL_INICIAL rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- Casually noticed false positives in this rule; this fixes some of them;
- removed comments from rule;
- made this rule goal-specific due to its generality. It [has _many_ opens and not enough applies (plus high disable rates)](https://internal1.languagetool.org/grafana/d/BY_CNDHGz/rule-events-analysis?orgId=1&from=now-30d&to=now&var-rule_id=CIENT%C3%8DFICO_FAZER_EFETUAR_REALIZAR_CONDUZIR_CONCRETIZAR_ELABORAR&var-language=pt)
=> [pt] clean up/add exceptions to CIENTÍFICO_FAZER_EFETUAR_REALIZAR_CONDUZIR_CONCRETIZAR_ELABORAR; make it goal-specific

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
As we can see in the [diffs](https://internal1.languagetool.org/regression-tests/via-http/2023-09-19/pt-BR/result_grammar_URL_INICIAL%5B1%5D.html), many of them already begin with capital letters, and I think it's best to restrict this rule to lowercase URLs.
=> [pt] Improve URL_INICIAL

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
The same AP for two rules that suggest “pôr” wrongly.
=> [pt] Added the same AP to two rules to fix the wrong suggestion "pôr"

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Also minor change made to account  for `quanto $NOUN`. That's the only FP left, so I think we can take this online.
=> [pt] Enable new sub-rules of GENERAL_VERB_AGREEMENT_ERRORS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
This enhancement fixes false positives that have been around for a very long time, and I should have done it before.
But it is better late, than never.
❤️ ❤️ ❤️ ❤️ ❤️
=> [pt-PT] Improved antipattern in rule ID:POSSESSIVE_WITHOUT_ARTICLE

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace.txt
For some reason, the rule CONFUSION_CE_L_ON isn't working, the rule can be handled in the replace.txt.
=> [fr] CONFUSION_CE_L_ON deleted and added to replace.txt

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, Pedro and Susana,
Here is a simple rule which I came up with while revising my thesis.
I tried to replace:
`<token regexp='yes'>a|para</token>`
with:
`<token/>`
just to see the difference, but it only had two hits and only one was a real positive.
Here are the results:
```
Portuguese (Portugal): 1 total matches
```
[_2.txt](https://github.com/languagetool-org/languagetool/files/12732193/_2.txt)
Thanks!
=> [pt] Added rule ID:PARA_SER_MELHORADA_A_MELHORAR

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Fix that pesky thing with `pg.`. Ignore `pg` as `petagram`, instead assume it means 'page', in which case we suggest `p.`, `pp.`, `pág.`, or `págs.` (I don't like the latter two, but apparently they're also correct?)
=> [pt] Add ABREVIATURA_DE_PAGINA_PG

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
gGEC takes away the match, gives a correct suggestion, but the message is not helpful and it is marked as a spelling error, when in fact it is just the recommended spelling. The xml style rule has a good apply rate in grafana and there is no data on matomo so no disables (last 30 days).  
[Grafana 30 days view ](https://internal1.languagetool.org/grafana/d/j4ReLa87z/rule-events-summary-with-types?orgId=1&var-rule_id=VON_SEITEN_RECOMMENDATION&var-language=All&var-rule_category=All&var-rule_type=All&var-filename=All&var-rule_tags=All&var-tone_tags=All&var-minOpen=0&from=now-30d&to=now)
=> [de] changed prio over gGEC

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
- Trying to address [this error](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6083).
- It appears the disambiguator is generating non-existent postags (`D.+`, `R.+`) due to an overlapping of postags in the rule pattern:
```
<pattern>
<marker>
<unify>
<feature id="gender"/>
<feature id="number"/>
<token postag="D.+" postag_regexp="yes"/>
<unify-ignore>
<token postag="R.+" postag_regexp="yes"/>
</unify-ignore>
<token postag="A.+" postag_regexp="yes"><exception>bem</exception></token>
</unify>
</marker>
</pattern>
```
- As we can see, `mesmo` and `conforme` appear twice in the disambiguator because they include more than one postag from the pattern; the antipattern added tries to fix this.
=> [pt] antipattern added to DNA[2] (#6083)

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is a new academic rule.
```
Portuguese (Portugal): 5 total matches
```
[_5.txt](https://github.com/languagetool-org/languagetool/files/12774624/_5.txt)
=> [pt] Added rule ID:SER_SIGNIFICATIVO

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To fix: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6321
- Some subrules from PAS_DE_VIRGULE have been moved to style as they were recommendations.
- Deleted "off" rules from the rulegroup 
- Deleted subrules 14 and 47 because they had a big gap of disables compared to the other subrules
Feedback board issue:
- Subrule 47 deleted
- Subrule 53 will now be a style recommendation (even though this won't fix the loop issue)
=> [fr] PAS_DE_VIRGULE rework

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace.txt
This simple rule didn't work the first time I tried to implement it, I'm giving it another try to see if it was a temporary bug.
=> [fr] CONFUSION_CE_L_ON_SELON retry

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/6467
- Adding 100 names (politicians, authors, footballer players, etc.) from African continent. 
- Adding also 15 languages
=> [fr] Francophonie/Afrique dic additions

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Dear Susana and Pedro,
Here is another rule.
The results are:
```
Portuguese (Portugal): 5 total matches
```
[_2.txt](https://github.com/languagetool-org/languagetool/files/12802013/_2.txt)
Thanks!
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
=> [pt] Added rule ID:DE_FORA_EXTERNO_DE_DENTRO_INTERNO

languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
To fix https://github.com/languagetooler-gmbh/languagetool-premium/issues/6467.
Adding around 1000 names mainly from French-speaking countries, as requested [here.](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6467#issuecomment-1748957334)
=> [all] Francophonie additions

languagetool-http-client/src/main/java/org/languagetool/remote/SentenceAnnotator.java
@AzadehSafakish: this should work.
@jaumeortola, already updated this [on Confluence](https://languagetooler.atlassian.net/wiki/spaces/DEV/pages/2134016018/SentenceAnnotator+instructions). Needed because we want to add the annotator's name to the output but the `userName` is used for something else.
=> Add annotatorName to SentenceAnnotaor cfg

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have removed the "temp_off":
https://internal1.languagetool.org/regression-tests/via-http/2023-10-06/pt-BR/result_style_DE_FORA_EXTERNO_DE_DENTRO_INTERNO%5B2%5D.html
Thanks!
=> [pt] Removed "temp_off" from rule ID:DE_FORA_EXTERNO_DE_DENTRO_INTERNO

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6436
Related to premium PR: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/1052
- TOMBER_EN_AMOUR duplicate removed (ANGLICISME_TOMBEE_EN_AMOUR remains)
- URL from removed premium CHARGE added to ETRE_EN_CHARGE
=> [fr] OVERLAP_OS_fix

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The disambiguator fix I have done yesterday made possible to improve this rule.
However, in 900 000 sentences, this improvement only gave one extra hit.
Ahhhhh… I forgot to mention it yesterday, but `TESTRULES PT` gives disambiguator warnings:
```
*** WARNING: The Portuguese rule: TAO_ADV[1], token [1], contains an empty string "" that is marked as regular expression.
*** WARNING: The Portuguese rule: TAO_ADV[1] (POS tag), token [1], contains "V.+" that is not marked as regular expression but probably is one.
*** WARNING: The Portuguese rule: FILTER_PROPER_NAMES[3], token [1], contains duplicated non case sensitive disjunction part (monte) within "Monte|bairro|café|concurso|curso|designaç?o|designado|designados|estilo|festival|filme|fundo|furac?o|galard?o|género|gên …
```
=> [pt] Improved rule ID:TOMAR_ASSUMIR

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Adding AP to PAS_DE_VIRGULE_STYLE and VIRG_NON_TROUVEE for `Un jour je m’en irai, sans en avoir tout dit`
(book by Jean D'Ormesson) see https://github.com/languagetooler-gmbh/languagetool-premium/issues/5240
=> [fr] AP in PAS_DE_VIRGULE_STYLE and VIRG_NON_TROUVEE

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
Heya, @p-goulart and @susanaboatto 
I have fixed the warnings in the disambiguator while using `TESTRULES PT`.
=> [pt] Fixed warnings in disambiguation.xml

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have completely improved/rewritten this rule.
Now it is a lot more flexible than it was with fewer false positives.
This is what I have been doing for the past three days, basically.
```
Portuguese (Portugal): 1201 total matches
```
[_54.txt](https://github.com/languagetool-org/languagetool/files/12922747/_54.txt)
=> [pt] Improved/rewritten rule ID:COLOCAÇÃO_ADVÉRBIO

languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- changed priority of COLOCAÇÃO_ADVÉRBIO based on [these results](https://internal1.languagetool.org/regression-tests/via-http/2023-10-18/pt-BR/) and the removal of some more important matches (like crase errors), I'm changing the priority of this rule
- [This rule](https://internal1.languagetool.org/regression-tests/via-http/2023-10-18/pt-BR/result_style_INIMIGO_ADVERS%C3%81RIO_ALIADO_OPONENTE%5B2%5D.html) also seems to match more FNs than TPs, so I will temp it off for now and ask Marco to review it
=> [pt] change priority of COLOCAÇÃO_ADVÉRBIO, temp off INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
=> [de] add gGEC APs

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
Here is an AP to remove false positives.
=> [pt] Added antipattern to rule ID:GENERAL_VERB_AGREEMENT_ERRORS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
It removes false positives.
=> [pt] Added exception to rule ID:ESTA_ESTÁ

languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
For this Grammalecte check run, will close https://github.com/languagetooler-gmbh/recurring-issues/issues/10
Deactivation of rule g2__conf_de_du_d__b1_a1_1, replaced by xml rule [DE_DU_D](https://github.com/languagetool-org/languagetool/pull/9497)
=> [fr] Grammalecte deactivation

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/compounds.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
=> [de] 24.10.

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/UpperCaseNgramRule.java
This caused many unnecessary allocations when new instances of the rule are frequently created
=> fix[en]: run expensive initalizations only once in UpperCaseNgramRule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Here is a new rule.
It only had one hit in 900 000 sentences, and the hit seems inconclusive but a valid structure for the rule (well triggered).
```
Portuguese (Portugal): 1 total matches
```
[6.txt](https://github.com/languagetool-org/languagetool/files/13198030/6.txt)
=> [pt] Added rule ID:CONFUSÃO_AO_OU

languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
To address: https://github.com/languagetooler-gmbh/recurring-issues/issues/17
This time, it also includes rules with less impact.
eepi_écriture_épicène_pluriel_er_ère
eepi_écriture_épicène_tous_toutes
eepi_écriture_épicène_pluriel_eux_euses
eepi_écriture_épicène_pluriel_eur_divers
For example:performeur·se·s >> “Écriture épicène dystypographique et imprononçable. À des fins de lisibilité, il est préférable d’éviter l’abus de graphies épicènes trop complexes.” and recommends "performeurs et performeuses"
g2__bs_avoir_été_chez__b1_a1_1
Style for “avoir été chez” but offers 0 suggestion, we can have a rule for that.
g2__bs_pour_ne_pas_que__b1_a1_1
Style for “pour ne pas que” but offers 0 suggestion, we can have a rule for that.
g2__bs_silence_assourdissant__b1_a1_1
“Silence assourdissant”, …
=> Grammalecte disables 2

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
The results are the same as before:
```
Portuguese (Portugal): 4 total matches
```
[2.txt](https://github.com/languagetool-org/languagetool/files/13246210/2.txt)
=> [pt] Rewrote rule ID:MUITO_FRIO

languagetool-language-modules/en/src/main/java/org/languagetool/tagging/en/EnglishHybridDisambiguator.java, languagetool-language-modules/en/src/test/java/org/languagetool/tokenizers/en/TokenizeMultiwordsTest.java
This way, we don't need to tokenize the phrases or add antipatterns to the speller. 
This does not seem to have any noticeable effect on speed. Do you have some way to test it better,  @fabrichter? We can test it on a server. But similar things are already done in other languages.
=> [en] add ignore_spelling to multiwords in global_spelling.txt

languagetool-http-client/src/main/java/org/languagetool/remote/CorrectionLoopFinderApi.java
Fix for error ErrorRateTooHigh, so that the code doesn't break but keeps going:
```
An exception occurred: java.lang.RuntimeException: Got error: Error: ErrorRateTooHigh is reached by a single sentence after rule: GERMAN_SPELLER_RULE the whole text contains 32 words this sentence has 22 matches
- HTTP response code 400
Exception in thread "main" java.lang.NullPointerException
```
Test sentence: `hey everyone we planned a „moto woche“ so we gonna dress up every day in different costumes it would be great if all of you would join us.` (this english sentence was by accident in the german data set and caused the error)
=> improve CorrectionLoopFinderApi

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java
as discussed – removal of `isOnlyPluralNoun`
=> [de] removing isOnlyPluralNoun from as a condition for non-infix-s

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of  https://github.com/languagetooler-gmbh/languagetool-premium/issues/6602.
- The recommendations for _Nouvel An_ are unclear (most sources recommend uppercase, see [Larousse](https://www.larousse.fr/dictionnaires/francais/Saint-Sylvestre/186735), but the _Académie Française_ [uses lowercase](https://www.dictionnaire-academie.fr/article/A9F0578)), and so does the [TLF/CNRTL](http://stella.atilf.fr/Dendien/scripts/tlfiv5/search.exe?23;s=1019470875;cat=1;m=nouvel+an;). Therefore, the rule is created in Style and not Grammar. We need to monitor the apply/disable rate of that rule in the future even more carefully than usual.
- Saint-XXX is handled through feminine determiner _la_ which should naturally avoid FP on masculine uses of "saint Jean, Saint André" etc. as a regular …
=> [fr] FETE_SAINT and NOUVEL_AN rules creations

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
We saw that some matches previously handled by some XML rules are now diverted by gGEC rules.
This example `Cette année, Avril a été chaud.` is from rulegroup id="MOIS" name="mois de l’année" (src/main/resources/org/languagetool/rules/fr/grammar.xml).
It's now AI_FR_GGEC_REPLACEMENT_ORTHOGRAPHY_UPPE handling it. That's not conveniant, as the xml rules have antipatterns already (see second screen shot about Mai 68).
**This PR lowers the prio of AI_FR_GGEC_REPLACEMENT_ORTHOGRAPHY.**
=> [fr] AI_FR_GGEC_REPLACEMENT_ORTHOGRAPHY prio change in French.java

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here are the whole results:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-06/pt-BR_full/result_style_QUALQUER_QUE_SEJA%5B1%5D.html
I have removed the two false positives in this pull request:
```
<example>Maria é uma pessoa muito espontânea; explode por qualquer que seja o motivo.</example>
<example>...heiro que mais me remete à minha mãe é o do perfume dela: sempre forte, com presença e notas doces (qualquer que seja o do momento... rs).</example>
```
=> [pt] Fixed 2 FPs and removed "temp_off" from rule ID:QUALQUER_QUE_SEJA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have removed the “temp_off”.
I removed the false positives reported by Susana in the previous week or so, and I can't focus right now to see if there are any additional enhancements required.
Here is the total results:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-06/pt-BR_full/result_style_INIMIGO_ADVERS%C3%81RIO_ALIADO_OPONENTE%5B1%5D.html
https://internal1.languagetool.org/regression-tests/via-http/2023-11-06/pt-BR_full/result_style_INIMIGO_ADVERS%C3%81RIO_ALIADO_OPONENTE%5B2%5D.html
Any feedback is welcome!
Thanks!
=> [pt] Removed "temp_off" from rule ID:INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
A brand-new rule for pt-PT.
Follow the discussion here:
https://github.com/languagetool-org/languagetool/issues/9622
Thanks!
=> [pt-PT] Added rule ID:SIMPLIFICAR_A_SER_PP_A_INF

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here comes an advanced rule with very little impact, as in 900 000 sentences it only had one hit.
```
Portuguese (Portugal): 1 total matches
```
[3.txt](https://github.com/languagetool-org/languagetool/files/13323853/3.txt)
=> [pt] Added rule ID:REMOÇÃO_SUBSTANTIVO_APÓS_MESMO

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/added.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/removed.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- Based on [these](https://[analytics.languagetoolplus.com/matomo/index.php?module=Widgetize&action=iframe&secondaryDimension=eventName&moduleToWidgetize=Events&actionToWidgetize=getAction&idSite=18&date=yesterday&flat=1&filter_column=label&show_dimensions=1&period=month&filter_pattern=UPPERCASE_AFTER_COMMA](https://analytics.languagetoolplus.com/matomo/index.php?module=Widgetize&action=iframe&secondaryDimension=eventName&moduleToWidgetize=Events&actionToWidgetize=getAction&idSite=18&date=yesterday&flat=1&filter_column=label&show_dimensions=1&period=month&filter_pattern=UPPERCASE_AFTER_COMMA)) Matomo findings;
- Antipattern added to address website sections (e.g., "Minhas compras", "Notificações", etc);
- Message improved.
=> [pt] improve UPPERCASE_AFTER_COMMA

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
To fix [[fr] Onomatopée Ding Dong#5583](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5583)
Onomatop are behaving as normal nouns (see https://dictionnaire.lerobert.com/guide/interjections-et-typographie.). 
PoS tag **I** (interjection) is perfect (tested on dare-dare and mama-mia, that are already in multiwords.txt).
=> [fr] Dictionary additions onomatopoeias

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/CompoundAwareHunspellRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
This saves about 2 seconds for me on the speller rule initialization
=> GermanSpellerRule: load the heavy Morfologik only when it's needed

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
These antipatterns remove several FPs.
I hope soon to remove “temp_off” from rule ID:COLOCACAO_ADVÉRBIO_VERBO_ANTES and from other rules.
Currently, I am fixing FPs in the rules.
Thanks!
=> [pt] Added antipatterns to rule ID:COLOCAÇÃO_ADVÉRBIO and rule ID:COLOCACAO_ADVÉRBIO_VERBO_ANTES

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
Only one hit in the nightly results:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-23/pt-BR_full/result_grammar_PELO_QUAL_PELA_QUAL%5B1%5D.html
=> [pt] Removed "temp_off" from rule ID:PELO_QUAL_PELA_QUAL

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
All the six hits seem valid to me:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-23/pt-BR_full/result_style_QUASE_QUE_PRONOME%5B1%5D.html
=> [pt] Removed "temp_off" from rule ID:QUASE_QUE_PRONOME

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The four hits seem valid:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-23/pt-BR_full/result_style_MUITO_FRIO%5B1%5D.html
=> [pt] Removed "temp_off" from rule ID:MUITO_FRIO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Only one result, and it seems valid to me:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-23/pt-BR_full/result_style_REMO%C3%87%C3%83O_SUBSTANTIVO_AP%C3%93S_MESMO%5B1%5D.html
=> [pt] Removed "temp_off" from rule ID:REMOÇÃO_SUBSTANTIVO_APÓS_MESMO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Zero hits in the nightly results.
=> [pt] Removed "temp_off" from rule ID:CONFUSÃO_AO_OU

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
During the weekend, I am going to dedicate some time to removing “temp_off” from some rules.
This one, for example, had zero hits in the nightly results.
=> [pt] Removed "temp_off" from rule ID:ESTAR_NO_ECRA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- Based on loop findings like:
> LOOP by GENERAL_GENDER_AGREEMENT_ERRORS[11]/GENERAL_GENDER_AGREEMENT_ERRORS[2]: todos as => todos os
> De todos as personalidades que construíram a história de Amapá, esse ilustre cidadão foi um visionário que, entre outras coisas, construiu a prefeitura, casas e foi dono de engenho, tem toda a minha admiração, não sei por qual razão ficou “plantado” nas terras em que fez geminar como lugar produtivo.
and
> LOOP by GENERAL_NUMBER_AGREEMENT_ERRORS[2]/GENERAL_NUMBER_AGREEMENT_ERRORS[9]: outros cara => outro cara
> Por que ele não faz video mostrando os outros cara que dão em cima dela?
- For now only adding masculine plural errors to see if nothing crazy appears in the diff results. Should everything be fine, I'll adapt these rules to match other …
=> [pt] add rulegroup CONCORDANCIA_DETERMINANTES_MASCULINOS for multiple determiner errors

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- Based on issue #8946
- A_PREPOSITION[6] was generating the wrong tag in the disambiguator. Fixed this;
- Other disambiguation changes are indentation-related;
- Corrects agreement error in `É proibido a entrada de pessoas não autorizadas`.
=> [pt] add rule CONCORDANCIA_SER_GENERO, add exception to A_PREPOSITION

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Based on GEMA errors:
- `A_TRAVES_ATRAVÉS_CONFUSAO`: should be the simplest; I don't suppose 'a traves' is a phrase people need often;
- `EM_CASE_EM_CASO_CONFUSAO`: this is slightly more annoying, since 'case' is a single word, but I still think the sub-rules here are straightforward enough;
- `OUVE_HOUVE_CONFUSAO`: the most difficult of the lot; both 'ouve' and 'houve' are valid and frequent verb forms; their contexts are quite different, though, so I hope the sub-rules here take care of it; we'll definitely need to see what it does on the corpus.
=> [pt] Add a few confusion rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Simple rule. Occasionally captured by agreement rules, but I feel like in this case it'd be better handled as an orthographic issue.
=> [pt] Add CONFUSAO_EU_SAI_SAÍ

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
It only has 5 hits in pt-PT, and they all look fine to me:
https://internal1.languagetool.org/regression-tests/via-http/2023-11-27/pt-PT_full/result_style_SIMPLIFICAR_A_SER_PP_A_INF%5B1%5D.html
Thanks!
=> [pt-PT] Removed "temp_off" from rule ID:SIMPLIFICAR_A_SER_PP_A_INF

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have rewritten this rule.
Now it is stricter, it has around half of the hits of the previous version, but they are more accurate.
The antipatterns were very complex to create, and it might have this or that false positive, but it is impossible right now for me to look at each one of the 200+ hits and fix one by one.
This was the best I could do in two or three days, just almost entirely dedicated to it.
😛 😋 ❤️ 
```
Portuguese (Portugal): 262 total matches
```
[53.txt](https://github.com/languagetool-org/languagetool/files/13502054/53.txt)
=> [pt] Rewrote completely rule ID:SIMPLIFICAR_QUE_E_TEM_TÊM

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6700
Simple APs, maybe too wide scope, but we want to make sure the FP won't appear again in another form.
=> [fr] SOUHAITER-AI_AP

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
0 hits in the nightly diff.
I forgot that there were two rules (pela → pelo & pelo →pela) and the other week I only removed the “temp_off” from one of them.
=> [pt] Removed "temp_off" from rule ID:PELA_QUAL_PELO_QUAL

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
I have added an antipattern to fix some false positives.
What is wrong with this rule for being “temp_off” besides the huge number of hits? Maybe using “picky” would fix it?
```
Portuguese (Portugal): 1709 total matches
```
[5.txt](https://github.com/languagetool-org/languagetool/files/13537537/5.txt)
=> [pt-PT] Added AP to rule ID:TODOS_FOLLOWED_BY_NOUN_SINGULAR

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
This rule can't become much better than already is.
I have removed a FP and the “temp_off”.
https://internal1.languagetool.org/regression-tests/via-http/2023-12-02/pt-BR_full/result_grammar_IR_CONTRACTION_NOUN%5B1%5D.html
❤️ ❤️ ❤️ ❤️
=> [pt] Added exceptions and removed "temp_off" from rule ID:IR_CONTRACTION_NOUN

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To address the looping issue: https://github.com/languagetooler-gmbh/task-force-french/issues/90
But also GEMA 23D gGEC FPs, so: https://github.com/languagetooler-gmbh/task-force-french/issues/85
- AI_FR_GGEC_REPLACEMENT_NOUN_FORM.*: AP added in remote-rule-filter to avoid FPs and loops with grammalecte_g3__gn_couleurs_invariables__b1_a1_1 and ACCORD_COULEUR[1] on, for example, "Elle avait les yeux marron"
AP tested and working :) it's actually the pattern from XML ACCORD_COULEUR[1], I only changed the token from the marker from plural to singular (`[JN].* p` to `[JN].* s`)
=> [fr] couleur_invariable-AI-AP

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseUnitConversionRule.java, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/PortugueseUnitConversionRuleTest.java
@susanaboatto I had to change the default spellings of the units to `pt-BR`, but also made some changes to the messages so they're less awkward.
---
@danielnaber there is an issue with this rule in that it fails to parse composite expressions like `2.3cm x 2.3cm`. In `pt-BR`, this appears as a frequent `temp_disable` context, and I believe that's also a reason why its apply rate is so low. The same seems to be true in other locales that have a unit conversion rule implemented.
It's prob. not a huge issue right now, so I'm just adding a simple hotfix to get rid of same-unit conversions, which takes care of many of the squaring/cubing FPs. But we might want to rethink the unit conversion rule, esp. for complex dimensions (2.5 x 2.3 x 6.9 cm).
=> [pt] Add minor fix to UNIDADES_METRICAS

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseWordRepeatRule.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/PortugueseWordRepeatRuleTest.java
For cases like:
This is wrong, but not because of repetition, but because there's a comma missing.
=> [pt] Improve recognition of reduplicated adverbs

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/verbs.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
For nightlies:
- remove verbs `crer` and `acreditar`, as their usage pattern is too complex and it just yields too many FPs; we may need a separate rule for 'crer', 'acreditar', 'achar', 'pensar';
- remove verbs 'negar' and 'sugerir', since they simply *mean* different things with subjunctive and indicative subclauses;
- fix the 'elar' issue by adding `inflected="true"`;
- update examples to match the new verb list.
=> [pt] Improve ESPERA_QUE_INDICATIVO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Lots of 'nesse case, o cliente...' I hate this word with a passion, but whatever, the users win 😭 Now it'll only work with `em case de`.
=> [pt] Pare back EM_CASE_DE

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
- split it, so we also have SUBT_SOBRECOMUM_MASCULINO, which takes care of nouns used in the 'wrong' gender but that make reference to animate entities;
- improve the disambiguator slightly to never lose the determiner tag of "a" before a feminine singular noun;
- add entities for commonly misused nouns wrt gender (can be expanded);
- comment out one example in pt-PT/style that's been affected by the recent change of the disambiguator (@marcoagpinto, you may need to have a look at this).
=> [pt] Improve DET_FEM_MAS_A_O grammar rule

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of 
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6825
<html>
<body>
Default="off":
REP_GENERAL
SNAP
WISE
OVERSIZE
VG
SECRETAIRE_EXECUTIF
BLIND
Removed:
GAME_DESIGNER ([now in Larousse](https://www.larousse.fr/dictionnaires/francais/game_designer/188599))
=> [fr] Cleanup style rules 0 % apply, >100 open last 5 months

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
False alarms removed based on [diff results](https://internal1.languagetool.org/regression-tests/via-http/2023-12-06/pt-BR/result_grammar_ELISAO_VERBAL_SEM_ENCLITICO%5B1%5D.html).
I will create an issue to fix other problems found, namely:
- Add a suggestion to include the simple future instead of the infinitive for `estrá` and `responsabilizá` as a typo: `tudo estrá nos conformes. → tudo estará nos conformes` // `O comprecar.com.br não se responsabilizá pelos anúncios constantes de seu site`
- Replace `=` with hyphen: `executá=lo → executá-lo`
- Add confusion pair rule for viuvá vs. viuva: `viuvá de Vasco Lourenço de Almada`
- Create confusion pair rule for atê vs. até
- Create rule to fix wrong use of en dash for verbs
- Fix missing hyphen before pronouns
=> [pt] add exceptions to ELISAO_VERBAL_SEM_ENCLITICO and INFINITIVE_NOUN

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
This is very restrictive, which I think for now is okay. It shouldn't trigger **unless** the hyphen/dash is preceded by a space.
=> [pt] Add NUMERO_NEGATIVO_SINAL_DE_MENOS

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/datetime.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- add the mirror image to sub-rule 3, meaning: if we see bad spacing around a hyphen/en dash, we will suggest an em dash with spaces **and** the hyphen/en-dash with spaces stripped from around it; (currently we only suggest the em dash);
- make sure the sub-rule 4 works as intended, add some more examples. This is the one we'll use for user options.
=> [pt] Update DASH_RULE for user options

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address: https://github.com/languagetooler-gmbh/task-force-french/issues/90
This will probably be the final commit for the above issue. We'll re-run the loop-finder once [this](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6746) actually takes effect.
- AGREEMENT_POSTPONED_ADJ exception added to the already existing list of exceptions
- QUI_VCONJ[5] exception added
GENTILE[12], [17] and [1] OFF due to FPs (https://internal1.languagetool.org/grafana/d/O09LTDNMz/rule-events-summary?orgId=1&var-rule_id=GENTILE&var-language=fr&var-rule_category=All&var-minOpen=0)
- TRES[8] AP added with example
=> [fr] Loop-fix-various

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/5459
Moving style rules that was still living in grammar.xml.
=> Fr/grammar style/cleanup impostors

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/style.xml
https://regression.languagetoolplus.com/via-http/2023-12-14/de-DE/result_style_F_ANSTATT_PH_2%5B1%5D.html
https://regression.languagetoolplus.com/via-http/2023-12-14/de-DE/result_style_F_ANSTATT_PH_2%5B2%5D.html
=> [de] changed prio + set default temp_off

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Quick fix to detect missing crase in `Casa a venda`, etc.
=> [pt] add rule to CRASE_CONFUSION_2

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
[Nightlies](https://internal1.languagetool.org/regression-tests/via-http/2023-12-13/pt-BR/result_grammar_NUMERO_NEGATIVO_SINAL_DE_MENOS%5B1%5D.html) look very good, I see no reason not to have this live.
=> [pt] Enable NUMERO_NEGATIVO_SINAL_DE_MENOS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
There was an obsolete spelling rule in Premium that caused an error in tests. Fixed here: https://github.com/languagetooler-gmbh/languagetool-premium-modules/commit/a475f7f2fdbd335b56370dcb225cf14d5448438e
=> [pt] enable PT_MULTITOKEN_SPELLING_TWO

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/messages.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Based on the nightlies. For one, the blank `<token/>` was allowing for a lot of stuff, so I limited it to the usual state separators, and that's worked well.
We still have an issue with stuff like:
> a senadora Heloísa Helena (AL)
Our rule currently thinks 'Helena' is a toponym and suggests `Helena–AL`. This isn't _that bad_ per se, but the more I think about it the more I think we need to have a DB of city names...
=> [pt] Fix SEPARADORES_DE_ESTADO rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
=> [pt] Improved rule ID:CONFUSÃO_APROXIMA_A_PRÓXIMA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Not much of an enhancement, basically better wording for what the rule does, and it only underlines “hás” and not “hás vezes”.
=> [pt] Improved rule ID:HÁS_VEZES

languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
Their [official name](https://en.wikipedia.org/wiki/Mötley_Crüe) *does* have metal umlauts, it's not just a decoration.
=> Fix Mötley Crüe in global spelling

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/chars.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
As discussed previously:
- for some reason the `&deg;` (and similar) entities don't work as expected exclusively in the `disambiguation.xml` file 😠 
- so I have:
- added comments to the relevant entity file to make that clear;
- replaced the entities with the *literal* characters in affected `disambiguation.xml` rules (the relevant one causing failures here was the `ignore_spelling` sub-rule of `DEGREES`);
- added comments to the affected rules in `disambiguation.xml` so we know what the characters are (it's really difficult to reliably see the difference between `ºᵒ°`...
- also done:
- added tokeniser and speller tests to make 100% sure we're doing what we must.
I'll make another PR in a moment with a rule that upcases `°c` to `°C` (it was a rule that we (a) needed, and (b) was useful to …
=> [pt] Fix DEGREE disambiguation rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya, @susanaboatto  and @p-goulart ,
No hits in the nightly diffs:
ARREAR_ARRIAR
no hits
CONFUSÃO_APROXIMA_A_PRÓXIMA
no hits
CONFUSÃO_ASSERTO_ACERTO_DE_CONTAS
no hits
HÁS_VEZES
no hits
=> [pt] Removed "temp_off" from rules

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/OldSpellingRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/OldSpellingRuleTest.java
https://regression.languagetoolplus.com/via-http/2023-12-15/de-DE/result_java_OLD_SPELLING.html
Note: please do not merge (to merge after premium deploy)
=> [de] try to ignore words added as exception

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/6825
**SEARCH** **off**
- usually in a Google-related context
- SEO |search| engine optimization
**SPLIT off **
- is a city
- is a function
- is an app
- is a sport move
**CART off**
- bouton Add to |cart|
- hide speller matches for carte, cartes
**PRIX_DEMANDE**
- adding an exception for "prix demandé par|pour"
=> [fr] Cleanup Style rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
I'd completely forgotten about this rule... Well, here's a fix. If the nightlies come back clean we should be able to enable it.
=> [pt] Tweak ABREVIATURA_DE_PAGINA_PG

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/chars.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
Prob. still not perfect, but first let's get rid of the low-hanging fruit FPs:
- make a systematic distinction between temperature scales (which require a space *before* the degree sign) and cardinal points (which require the space between the degree and the abbreviation):
- `90 °F` but `90° N`, 'noventa graus Fahrenheit' but 'noventa graus ao norte'.
- improve, somewhat, the recognition for coordinates like `90° 45′ 22″`, using the prime/double prime characters for angular minutes/seconds, but this may require some more tinkering (and potentially also different tokenisation, which I'm not keen on...);
- crucially, I've added `o` to the ordinal/degree detection rule – the nightly corpus reveals many instances of `100o` clearly indicating degrees; once this is working, the …
=> [pt] Improve degree sign and ordinal indicator detection rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
A few tweaks based on nightlies.
The Brazilian state separator rule results look really good now that we are validating the actual toponyms, so I'm enabling it.
=> [pt] Check dash/abbrev. rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
A formal rule:
https://www.infopedia.pt/dicionarios/lingua-portuguesa/Terceiro+Mundo?express=terceiro%20mundo
“conjunto dos países blah blah”
=> [pt] Added rule ID:PAÍSES_DO_TERCEIRO_MUNDO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
I have enhanced the rule and instead of one hit it now has two.
```
Portuguese (Portugal): 2 total matches
Portuguese (Portugal): 811129 total sentences considered
```
[1.txt](https://github.com/languagetool-org/languagetool/files/13782139/1.txt)
=> [pt-PT] Improved rule ID:PÔR_FIM_À_VIDA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
I have enhanced the rule.
It is now a lot more powerful.
```
Portuguese (Portugal): 55 total matches
Portuguese (Portugal): 811129 total sentences considered
```
[1.txt](https://github.com/languagetool-org/languagetool/files/13790062/1.txt)
=> [pt-PT] Improved rule ID:ALUGAR_CASA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have moved the “ERROS DE TRADUÇÃO” category from inside style.xml into grammar.xml, just like it happens in the main PT file.
Also, there was a category with an AO45 rule whose rule I moved to inside the main category AO45 and turned the rule off because it needs to be rewritten.
Somewhere during the week, I must also create a “SHORTEN IT” category in the style.xml.
This is all regarding pt-PT.
Thanks!
Happy New Year!
=> [pt-PT] Moved category from grammar.xml to style.xml, and AO45 category to inside the real AO45 category

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/en_NZ.info, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/MorfologikNewZealandSpellerRuleTest.java
The encoding was wrong. It was not much relevant because there are few words with diacritics in English (only foreign terms). 
I don't know if there will be some undesired effects after this change. Do we need more testing?
The encoding was changed here: https://github.com/languagetool-org/languagetool/commit/8bb96ad05b0060158a93504337eb2dcfcecaa15f, but it was probably wrong.
=> [en] change the encoding of NZ spelling dictionary

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
Heya again,
This one should be straightforward.
https://www.soportugues.com.br/secoes/FAQresposta.php?id=390
https://dicionario.priberam.org/altifalante
```
Title: <plaintext>
1.) Line 1, column 33, Rule ID: AUTO-FALANTE[1] [temp_off]
Message: Possível confusão de termos.
Suggestion: altifalantes; alto-falantes
Rule source: /org/languagetool/rules/pt/pt-PT/grammar.xml
ou só ficava o fio (que liga os auto falantes nas portas) exposto ?
^^^^^^^^^^^^^                      
Title: <plaintext>
1.) Line 1, column 1, Rule ID: AUTO-FALANTE[1] [temp_off]
Message: Possível confusão de termos.
Suggestion: Altifalantes; Alto-falantes
Rule source: /org/languagetool/rules/pt/pt-PT/grammar.xml
Auto-falantes e televisores "jumbotron" foram postos ao longo de ambos os lados norte e sul para fazer com que …
```
=> [pt-PT] Rewrote and moved to confused words, rule ID:AUTO-FALANTE

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/ignore.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/multiwords.txt, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/SpellingCheckRuleTest.java
routine dictionary additions; PRing because I'm not sure why local mvn tests fail
=> [en] add words 1/03

languagetool-core/src/main/java/org/languagetool/tools/RuleMatchesAsJsonSerializer.java, languagetool-language-modules/nl/src/main/java/org/languagetool/rules/nl/CompoundAcceptor.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/V2TextChecker.java
Load rule confidence from am external file. This is limited to one confidence per match/rule, even though the match might have more than one suggestion. They will all end up with the same confidence and the client needs to interpret that...
=> External file for rule confidence

languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/MultiWordChunker.java, languagetool-core/src/main/java/org/languagetool/tools/StringTools.java, languagetool-core/src/test/java/org/languagetool/tagging/disambiguation/MultiWordChunkerTest.java, languagetool-core/src/test/java/org/languagetool/tools/StringToolsTest.java, languagetool-language-modules/ca/src/main/java/org/languagetool/tagging/disambiguation/ca/CatalanHybridDisambiguator.java, languagetool-language-modules/de/src/main/java/org/languagetool/tagging/disambiguation/rules/de/GermanRuleDisambiguator.java, languagetool-language-modules/en/src/main/java/org/languagetool/tagging/en/EnglishHybridDisambiguator.java, languagetool-language-modules/es/src/main/java/org/languagetool/tagging/disambiguation/es/SpanishHybridDisambiguator.java, languagetool-language-modules/fr/src/main/java/org/languagetool/tagging/disambiguation/fr/FrenchHybridDisambiguator.java, languagetool-language-modules/pt/src/main/java/org/languagetool/tagging/disambiguation/pt/PortugueseHybridDisambiguator.java, languagetool-language-modules/pt/src/main/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizer.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/dialect_alternations.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/multiwords.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java, pom.xml
I've been having a look at the nightly results and making some changes to our dictionaries, and I think it is time to enable it, with `v0.12` of the Portuguese dictionary binaries.
---
@jaumeortola, in order to get the letter case to work properly (without needing to add all manner of weird variants to `multiwords.txt`), I made a change to the `MultiWordChunk` class. Now, in addition to checking `Upcased tokens`, we also check `Titlecased Tokens`. To get this to work well, I added a new `StringTools` method. The new tests should make the intention here clear, but do ask.
⚠️ The lists of titlecasing exceptions were done sort of slapdash, so please review them and approve once you have. @AzadehSafakish, @St-ac-y, @LucieSteib, @mark-baas: specifically, check the word lists in the …
=> [pt] Enable multi-token spell-checking

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
https://regression.languagetoolplus.com/via-http/2024-01-10/de-DE/result_grammar_LEERZEICHEN_NACH_VOR_ANFUEHRUNGSZEICHEN%5B5%5D.html
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6898
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6866
=> [de] removed symbol (FPs in diff) + added gGEC APs

languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java
This can be quite drastic, but it seems to be the desired outcome: remove all matches with misspelled suggestions.
=> Remove misspelled ai suggestions

languagetool-language-modules/pt/src/main/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizer.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
Specifically, the use of a simple whitespace as a thousands separator was not super consistent. It worked only when numbers were either followed by a space or EoS. Which meant stuff like `1 000.25` or `1 000%` was nott working.
I have updated it, which should be one of the final chapters in the ordinal abbreviation saga. Added a couple of tokeniser tests to boot.
=> [pt] Improve number tokenisation

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
@jaumeortola: Adding the subrule 21 from SI_TILDE_PREMIUM with its antipatterns as antipattern to AI_ES_HYDRA_LEO_CP_SITILDE_SI hopefully fixes the loop between LOOP by AI_ES_HYDRA_LEO_CP_SITILDE_SI and SI_TILDE_PREMIUM[21] of our issue [6652](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6652)
=> [es] add rule AI_ES_HYDRA_LEO_CP_SITILDE_SI

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
The number tokenisation works, the [changes](https://internal1.languagetool.org/regression-tests/via-http/2024-01-17/pt-BR/result_grammar_ORDINAL_ABBREVIATION%5B1%5D.html) look good. I think we can finally enable.
=> [pt] Enable ORDINAL_ABBREVIATION

languagetool-language-modules/nl/src/main/resources/org/languagetool/resource/nl/disambiguation.xml
It keeps on causing issues. Probably start and end are not detected using the postags, but by code.
=> remove START and END trick

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/compounds.txt
Requesting your review on this, as I changed `<token regexp="yes" chunk_re="I-NP-.*">colou?red</token>` to `<token regexp="yes" postag="JJ">colou?red</token>`. 
For some reason, our chunker chunks `coloured` as `B-VP` in the sentence _The cream coloured jumper looked particularly smart._
Not sure if `JJ` instead of `I-NP-.*` is going to have any unintended consequences...
=> [en] amended hyphenated compound rule cream-colored

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
@jaumeortola Espero que esta correción sencilla resuelva el loop entre AI_ES_HYDRA_LEO_CP_QUIEN_TILDE_QUIEN y INTERROGATIVAS_INDIRECTAS[1] del [issue 6652](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6652).
Tuve que añadir la rule id porque solo existía la regla opuesta (AI_ES_HYDRA_LEO_CP_QUIEN_QUIENTILDE) en el remote-rule-filters.xml. 
Acerca de esta regla:  siguiendo la lógica que aplicamos la semana pasada, el <token> en el <antipattern> de AI_ES_HYDRA_LEO_CP_QUIEN_QUIENTILDE no debería llevar tilde, no?
=> [es] fix LOOP by AI_ES_HYDRA_LEO_CP_QUIEN_TILDE_QUIEN/INTERROGATIVAS_INDIRECTAS[1]

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
For [english-pos-dict #3](https://github.com/languagetool-org/english-pos-dict/issues/3).
Specifically, in response to [this comment](https://github.com/languagetool-org/english-pos-dict/issues/3#issuecomment-1911041883).
The comma postag has been removed, however `postag=","` appears over 100 times in OS grammar.xml alone.
PR'ing because I'm not entirely sure if I've done this correctly...
=> [en] add rule for comma postag

languagetool-language-modules/fr/src/test/java/org/languagetool/rules/fr/MorfologikFrenchSpellerRuleTest.java
Not very substantial changes, but I reworked the tests in the process of cleaning up the French dictionary compilation scripts. Spoke to @LucieSteib and we decided to go for a less strict approach to the suggestion ordering (but always limiting them to **5**).
The reorganised tests will also make it easier for the French team to test recompiled dictionary versions. (But note this PR doesn't change the FR POS dict dependency, despite the branch name 🥴).
=> [fr] Update speller tests

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
After Slack discussion with the FR Data team, turns out this subrule is a style change.
Also the link was a 404 error, now fixed.
=> [fr] PART_OU_PAR_3 grammar to style

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To address and close: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7050
2 APs added, 1 pattern and 1 example modified.
=> [fr] A_ACCENT_A and A_ACCENT AP added

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
From the gGEC loop task. We already have `CONFUSÃO_AONDE_ONDE`, and gGEC seems to handle these cases well enough.
=> [pt] Disable AONDE_BR

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wrongWordInContext.txt
As per [Slack thread](https://languagetooler.slack.com/archives/C058BK14VND/p1707983331009219).
=> [pt] Remove entender/intender pair from wrongWordInContext

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/tagging/pt/PortugueseTagger.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tagging/pt/PortugueseTaggerTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
- cases like 'Jiu-Jitsu' were not being accepted (e.g. [here](https://regression.languagetoolplus.com/via-http/2024-02-17/pt-BR/result_java_MORFOLOGIK_RULE_PT_BR.html));
- this became clear due to changes made to the multitoken rule [here](https://github.com/languagetool-org/languagetool/commit/14d79a0cd0f92f3b74ae0ba5a332b73a54595554);
- the tagger and tokeniser have been changed to account for valid titlecasing of hyphenated compounds, by making sure we only mark a token as mixedCase when *at least one* of its components is mixedCase; since both 'Jiu' and 'Jitsu' start with an uppercase letter, they are not mixed and, therefore, valid;
- the speller also had to be changed to accept such words, since we cannot impact the titlecasing rules of tokens that contain only hyphens (the …
=> [pt] Add hotfix for titlecasing of hyphenated compounds

languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/AbstractDisambiguator.java, languagetool-language-modules/ca/src/main/java/org/languagetool/rules/ca/OblidarseSugestionsFilter.java, languagetool-language-modules/ca/src/main/java/org/languagetool/tagging/disambiguation/ca/CatalanHybridDisambiguator.java, languagetool-language-modules/ca/src/main/resources/org/languagetool/rules/ca/replace_multiwords.txt, languagetool-language-modules/es/src/main/java/org/languagetool/tagging/disambiguation/es/SpanishHybridDisambiguator.java, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
New version of https://github.com/languagetool-org/languagetool/pull/10320
This code can be easily shared by other languages, even to ignore Spanish words in English.
=> [es,ca] ignore English words

languagetool-core/src/main/java/org/languagetool/rules/AbstractDateCheckWithSuggestionsFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/DateCheckFilter.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/DateCheckFilterTest.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanTest.java
Please look at the suggestions and the new message.  @Luisa-LT 
We could remove one dot here: 
`<example correction="Montag., 2015-09-28|Mi., 2015-09-30">Ein Termin am <marker>Mi., 2015-09-28</marker>.</example>`
=> [de] suggestions for wrong dates

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/style.xml
We've got a complaint that this warning in a JetBrains IDE seems too harsch for an optional stylistic issue. They also note that the example correction "she is going to all the parks" doesn't sound convincingly nicer. So we propose to make it more explicit that the goal of this warning is conciseness and to add a shorter example (which would then be used by the IDE) which seems to sound nicer.
=> en ALL_OF_THE: soften the message, make the shortest example less controversial, make the rule work at the sentence start

languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/added.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/spelling.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
For `email`, I'm just adding a very specific grammar rule specifically telling people to add a hyphen there, since our suggestions were maybe getting in the way:
Since this is the most frequent addition, maybe it's worth being very explicit..?
---
For `stories`, I assume that's the Instagram thing... I think we should just support it. Adding it here as a hotfix since it's in our top 10 for the past month.
---
For `EAD`, I'm not adding speller support, since it is wrong, but I am adding a super simple grammar rule to suggest `EaD` when specifically referring to 'ensino a distância`, which has higher priority than the speller.
---
=> [pt] Add spelling hotfixes

languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
The Académie themselves defined howwe should spell their name, and considering their pickyness, we should not accept or suggest the version with Française capitalized. 
See the corresponding point in https://www.academie-francaise.fr/questions-de-langue#48_strong-em-majuscules-em-strong
> 3. Majuscules dans les noms d’organismes et d’institutions,
> 
> Les noms des organismes (organismes d’État, organismes culturels et éducatifs, etc.), lorsqu’il en existe plusieurs de leur espèce, ne prennent pas de majuscule ; c’est le nom propre ou le nom de spécialisation qui les accompagne éventuellement qui la prend : le conseil général d’Île-de-France, la cour d’appel de Versailles, la mairie de Paris, l’académie de Toulouse, le ministère de la Culture, le lycée Fénelon, la bibliothèque Mazarine. …
=> [fr] Removal Académie Française

languagetool-rpm-package/src/main/resources/server.properties.sample, languagetool-server/src/main/java/org/languagetool/server/Server.java
aef6779ac838 CHANGELOG was mentioning .languagetool.cfg
so I assume it's a typo
bd64e2e4bc55 the typo is there since the feature was added
=> [code] fixed typo in the --help and examples

languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/BrazilianPortugueseSimpleReplaceRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/PortugueseBarbarismRuleTest.java
As per [Slack](https://languagetooler.slack.com/archives/C046J7G16CT/p1710236175180829), adding tests to make sure the Portuguese replacements rule is not triggered when expressions are marked as 'exceptions' upstream.
=> [pt] Add tests for simple replacement exceptions fix

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
If the suggestion only changes the casing of the original, then adapt the message and other attributes of the rule or the match.
For testing, we could build a fake match and test it.
=> [fr] message for ggec rules that change only the casing

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7072
- Adding missing APs from some categories in the remote-rule-filter
- 2 gGEC IDs with picky added to French.java (quotation marks + si on >> si l'on)
=> [fr] AI_FR_GGEC_PICKY_TEST

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
Reverting changes in French.java from https://github.com/languagetool-org/languagetool/commit/461a66c0be43b7df05d430e75babfc6c109bf73c to fix an error, will re-apply the changes once fully fixed.
=> [fr] revert-email-changes

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/ignore.txt
Mostly from https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/26561185/substances-perfluoroalkylees-et-polyfluoroalkylees
Masculine statement from https://dictionnaire.lerobert.com/definition/pfas is probably wrong
Adding @LucieSteib as reviewer to double-check or add more related words if necessary
=> [fr] PFAS_dict_addition

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseEnclisisFilter.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseProclisisFilter.java, languagetool-language-modules/pt/src/main/java/org/languagetool/tagging/pt/PortugueseTagger.java, languagetool-language-modules/pt/src/main/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizer.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/PortugueseWordRepeatRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tagging/pt/PortugueseTaggerTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java, pom.xml
⚠️ This change **requires** the [portuguese-pos-dict](https://github.com/languagetool-org/portuguese-pos-dict) dependency to be `v0.13` or later!
This PR adds POS tags to the `pt` tagset for enclitic pronouns.
Let's use `diz-me` ('tell me') to illustrate the changes.
|was|will be|
|---|---|
|three tokens (`diz`, `-`, `me`)|a single token (`diz-me`)|
|each token tagged separately|tagged as `dizer[VMM02S0:PP1CSO00]`|
- dictionary suggestions consider whole word forms (e.g. `ama-se` <=> `amasse`);
- forms that only appear in derived environments are no longer accepted by the dictionary in isolation (e.g. `amá` and `lo` from `amá-lo` should now both be flagged as spelling errors);
- working with mesoclitics is made significantly easier (e.g. `fá-lo-á` doesn't require **five** tokens, …
=> [pt] Use new POS tagging schema

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
I removed the “temp_off” from this rule.
https://internal1.languagetool.org/regression-tests/via-http/2024-04-08/pt-PT_full/result_style_ALUGAR_CASA%5B1%5D.html
❤️ ❤️ ❤️ ❤️
=> [pt-PT] Removed "temp_off" from rule ID:ALUGAR_CASA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have rewritten the rule to make it simpler and more flexible.
```
Portuguese (Portugal): 36 total matches
Portuguese (Portugal): 809459 total sentences considered
Portuguese (Portugal): 56090 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```
[8.txt](https://github.com/languagetool-org/languagetool/files/14924900/8.txt)
=> [pt-PT] Rewrote rule ID:CONCLUIR_UM_CURSO

languagetool-core/src/main/java/org/languagetool/rules/patterns/MatchState.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-language-modules/ar/src/main/resources/org/languagetool/rules/ar/grammar.xml, languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/added.txt, languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/disambiguation.xml, languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/spelling.txt, languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml, languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk/grammar-style.xml
The bug was this: 
`<match no="1" include_skipped="following"/>`
In a match using `include_skipped="following"`, if there are no following tokens, the token (no=1 in this case) was added. Now the suggestion will be empty, as expected. 
Some unnecessary white spaces in suggestions are removed as well.
=> [core] fix bug in include_skipped="following"

languagetool-language-modules/pt/src/main/java/org/languagetool/tagging/pt/PortugueseTagger.java, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tagging/pt/PortugueseTaggerTest.java
As per [Slack](https://languagetooler.slack.com/archives/C03MQKNKQG5/p1712731407229069).
The loss in the coverage of legitimate derivations that are not present in the dictionary should be far outweighed by the issues with the introduction of misspellings for valid verbs that are already present.
=> [pt] Remove 're' and 'auto' prefixes from tagger exceptions

languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Per [Slack comment](https://languagetooler.slack.com/archives/C058BK14VND/p1712749903029809).
First we fix the incorrect enclitic verb form (e.g. `abraça-la` -> `abraçá-la`) and only then do we move pronouns around.
=> [pt] Move ACENTUAÇÃO_VOGAL_ÊNCLISE to before COLOCACAO_PRONOMINAL_COM_ATRATOR_SIMPLES

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseEnclisisFilter.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- just taking care of a few [glaring gaps in our coverage](https://internal1.languagetool.org/regression-tests/via-http/2024-04-11/pt-BR/result_grammar_REFLEXIVE_VERB_SE_AGREEMENT%5B1%5D.html) where gGEC is a little inconsistent;
- I also noticed that gGEC is not good at spotting errors in mesoclitic placement (e.g. `faria-lhe` -> `far-lhe-ia`), so I've also significantly changed the `PODERIAM_SE` rule;
- with the new tagging schema and the `EnclisisFilter`, I could condense the many sub-rules into a single one, and also account for irregular forms (e.g. `faria` from `fazer`).
---
<sup>Not sure how to treat _tem-se_, as it can be many things.</sup>
=> [pt] Add APs to REFLEXIVE_VERB_SE_AGREEMENT

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseProclisisFilter.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Fix bug described [here](https://languagetooler.slack.com/archives/C02R689CQ1W/p1713361355114399).
That filter was being too naïve about verb tags. Now it's more restrictive. Added an example to test it — should work.
@SteVio89 & @susanaboatto — I suppose you can decide if this is worth a redeploy.
=> [pt] Fix SENT_END bug with PortugueseProclisisFilter

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @susanaboatto  and @p-goulart ,
Here is a formal rule.
Notice it has thousands of hits, it is a very high-impact rule.
I tried to remove as many FPs as possible, but it is impossible to check thousands of sentences one by one.
```
Portuguese (Portugal): 3964 total matches
Portuguese (Portugal): 809459 total sentences considered
```
[27.txt](https://github.com/languagetool-org/languagetool/files/15052977/27.txt)
=> [pt] Added rule ID:MORRER_PERECER_FALECER

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRule.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/chars.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/english.ent, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
@susanaboatto I've sent you on Slack a sample diff showing the performance of the speller after tagging English words with `_english_ignore_`. If you need a different test set, do let me know.
@jaumeortola this logic seems to work for me. The one annoying thing about it is that, since we need the English tagger for the filter to work, I cannot add Java tests without making English a dependency. Any ideas? I'd really like to add some proper tests here.
=> [pt] Check English words in speller

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- remove '_ORTHOGRAPHY' suffix to allow users more control;
- add 'picky' tag;
- this should only really work as of v0.16 of the dictionary, where 'email' is accepted in pt-BR.
---
@susanaboatto please decide on the precise UX in terms of tone tags and pickiness.
Closes languagetool-org/portuguese-pos-dict#27 (together with languagetool-org/portuguese-pos-dict#33).
=> [pt] Make EMAIL_SEM_HIFEN picky

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
After some six days working on it almost non-stop, it is ready.
I have created a rule to replace the obsolete rule ID:QUE_SER_ESTAR_PARTPASSADO .
This rule is a lot more accurate than the obsolete one it replaces.
The code looks huge, but that happens because of the commented examples (thus why I asked the other day how many examples were acceptable, and Pedro told me not to worry about aesthetics).
The code of this new rule is very simple and both of you can easily fix FPs by changing the last two antipatterns.
So, here is some useful information:
```
rule ID:QUE_SER_ESTAR_PARTPASSADO (old rule)
Portuguese (Portugal): 593 total matches
Portuguese (Portugal): 809459 total sentences considered
``` …
=> [pt] Created rule ID:QUE_SER_ESTAR_PARTPASSADO_V2 to replace rule ID:QUE_SER_ESTAR_PARTPASSADO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
It is time to start removing 'temp_off' from the rules.
The two rules here:
AUTO-FALANTE has only one hit: https://internal1.languagetool.org/regression-tests/via-http/2024-04-25/pt-PT_full/result_grammar_AUTO-FALANTE%5B1%5D.html
CRIAR_QUERER has zero hits.
Thanks!
=> [pt-PT] Removed 'temp_off' from rules ID:AUTO-FALANTE and CRIAR_QUERER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya, @p-goulart and @susanaboatto ,
Like Pedro suggested, for simple pt-PT rules, I may create pull requests and press “merge” myself after the test finish.
This rule only has 11 hits:
https://internal1.languagetool.org/regression-tests/via-http/2024-05-02/pt-PT_full/result_style_CONCLUIR_UM_CURSO%5B1%5D.html
and I changed: “é mais corrente” to “é mais formal” in the suggestion.
In an hour or two, I will give another look in the pt-PT .XMLs to see what more rules can have the temp_off removed.
=> [pt-PT] Removed "temp_off" from rule ID:CONCLUIR_UM_CURSO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Since my last two pull requests were giving conflicting errors, I decided that the best approach would be to create a new pull request with all the changes from the other two.
I have done all the changes you both suggested.
Regarding "terceiro mundo" I moved it also to the category Susana suggested, and here are the bases for this specific rule:
https://www.infopedia.pt/dicionarios/lingua-portuguesa/Terceiro+Mundo?express=terceiro%20mundo
Thanks!
=> [pt] Added rule ID:AGORA_ATUAL and removed temp_off:DAR_EXEMPLO_EXEMPLIFICAR, SER_CONSISTIR_RESIDIR, PAÍSES_DO_TERCEIRO_MUNDO

languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java
Rule ID was changed because of https://github.com/languagetool-org/portuguese-pos-dict/issues/27.
=> [pt] Fix priority for EMAIL_SEM_HIFEN rule

languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseBarbarismsRule.java, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
- when tokens are tagged with _english_ignore_, the 'barbarism' rule should not be triggered;
- add a couple of tests to make sure it is working.
---
@jaumeortola @GillouLT 
I've just noticed this issue also affects French:
The first sentence here should match, since it triggers the vanilla Anglicism replacement rule. But the second sentence shouldn't trigger — 'screencast' is tagged with `_english_ignore_`, and it is in an English sentence.
=> [pt] Skip foreign terms rule for _english_ignore_

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is an enhanced version of the rule, fixing some FPs and more flexible.
❤️ ❤️ ❤️ ❤️ 😛 😛 😛 😛 😛 😛 😛 
Thanks!
=> [pt] Improved rule ID:MORRER_PERECER_FALECER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The rule only has one hit:
https://internal1.languagetool.org/regression-tests/via-http/2024-05-14/pt-BR_full/result_style_AGORA_ATUAL%5B1%5D.html
It is a very low-impact rule.
=> [pt] Removed "temp_off" from rule ID:AGORA_ATUAL

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here are a couple of antipatterns.
I tested the rule on my thesis and the only FP I got was fixed with the second antipattern:
`“O batalhão vence caso os seus elementos não se encontrem mortos na totalidade.”`
Meanwhile, I gave a quick look at the results of the rule and added an extra antipattern for some FPs.
I guess that soon we must consider removing the “temp_off” since the number of hits is huge (high-impact rule) with almost 4000 hits, so I can only fix what can be spotted by luck.
Thanks!
=> [pt] Added APs to rule ID:MORRER_PERECER_FALECER

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java, languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
For measurements that include multiplication signs, our disambiguator is not adding an `ignore_spelling` flag, which results in stuff like this:
From the speller dashboard:
<sup>Note that here they **look** like proper multiplication signs, but if you look at the regex and inspect the values, you'll see they are really just `x`. Probably the browser being clever when rendering stuff.</sup>
---
This PR:
- adds `X_AS_MULTIPLICATION_SIGN_IGNORE` to the disambiguator (this the most important thing);
- adds tests to the speller and tokeniser (just to be on the safe side);
- add an example to `MULTIPLICATION_SIGN` picky rule (to make sure the `x` can properly be changed to a `×` even before unspaced units);
- improves the messages for `UNITS_OF_MEASURE_SPACING` picky rule (chapter 7,103 of 'our …
=> [pt] Improve behaviour of compound measurements

languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexAntiPatternFilter.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java
This PR fixes a few FPs with valid hexadecimals like `0x5A` stemming from the multiplication rule<sup>1</sup>.
To achieve that, we:
- fix a logic bug in `RegexAntiPatternFilter` (@jaumeortola);
- add a `RegexAntiPatternFilter` to `MULTIPLICATION_SIGN`;
- add a couple of hexadecimal examples to `MULTIPLICATION_SIGN`;
- add `HEXADECIMAL_NOTATION` and `OCTAL_NOTATION` rules to the disambiguator so we can reliably ignore spelling for valid hexadecimal and octal numerals<sup>2</sup>;
- add tests to the speller rule to make sure we're ignoring what we should be ignoring.
---
<sup>**1**: this is not a new issue, but the matches appear as new because of the recent improvements to the disambiguator.</sup>
<sup>**2**: I decided to only ignore spelling of C-style hexadecimal and C-inspired octal …
=> [pt] Fix hexadecimal number bug

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @susanaboatto  and @p-goulart 
I was looking at the nightly results and these antipatterns fix numerous things.
How come the nightly results (pt-BR) have sentences that my pt-BR corpus for tests doesn't have?
Thanks!
=> [pt] Added/Improved APs in rule ID:MORRER_PERECER_FALECER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have improved slightly the APs to remove even more FPs.
I believe the rule is good enough for deployment:
https://internal1.languagetool.org/regression-tests/via-http/2024-05-28/pt-BR/
MORRER_PERECER_FALECER[1]: removed 51 FPs
MORRER_PERECER_FALECER[2]: removed 1 FP
Thanks!
=> [pt] Improved APs and removed "temp_off" from rule ID:MORRER_PERECER_FALECER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- add 'alllower' to avoid '10 H 30 MIN';
- add sub-rules to turn "10:00h" (no minutes) into "10 h" instead of "10 h 00 min".
=> [pt] Update HOURS_ABREVIATION

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have replaced the old rule FAZER_VERBO_VERBO_INFINITIVO with a new rule FAZER_VERBO_VERBO_INFINITIVO_V2.
The old rule was useless, and it was only good at providing false positives.
Now we have a decent rule with 0 hits in 900 000 sentences.
Thanks!
=> [pt] Replaced rule ID:FAZER_VERBO_VERBO_INFINITIVO with rule ID:FAZER_VERBO_VERBO_INFINITIVO_V2

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
<sup>Hopefully the final commit to this rule for now... 😑</sup>
This rule is annoying because it's difficult to find **authoritative** sources on it. Just a bunch of blogs with *opinions*, but none actually cite any proper sources.
The URL there was linking to a `pt-PT`-specific *opinion*, and it is not even universally accepted in Portugal. I've removed the URL, since it no longer matches the recommendations we're making users... and since we can't find a **proper** source, there's no URL there any more.
Here's what we do now:
- remove leading zeroes when using the `h` abbreviation, e.g. `08h -> 8h`;
- when there are no minutes, we accept both spaced and unspaced variants, e.g. both `8h` and `8 h` are correct (some style guides recommend no space for consistency with the format below, …
=> [pt] Improve spacing in HOURS_ABREVIATION

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The rule has zero hits in the nightly results.
So, I have removed the “temp_off” and also added an antipattern.
Thanks!
=> [pt] Removed temp_off and added AP to rule ID:FAZER_VERBO_VERBO_INFINITIVO_V2

languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PortugueseOrthographyReplaceRule.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/english.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/multiwords.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/replace_orthography.txt, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml, languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/PortugueseOrthographyReplaceRuleTest.java, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java, pom.xml
**This PR:**
- updates the version of the POS dict to `v1.1.0`;
- adds `PT_SIMPLE_REPLACE_ORTHOGRAPHY`...
- this is a rule that adds a simple replace to certain pairs of words (e.g. `ja -> já`, `nao -> não`) to counteract a bit of the Morfologik noise and, hopefully, improve acceptance rate for basic corrections like `voce -> você`;
- this rule has higher priority than the base Morfologik rule, but lower than the gGEC spelling rule (those suggestions tend to be better in context);
- it uses the `replace_orthography.txt` file, which can be freely modified;
- adds English suggestions to `_english_ignore_`-tagged words;
- adds a spelling ignore rule to laughter like `rsrsrs` (was already done for `hahaha` and `kkkkk`);
- adds a silly style rule to enforce `ok` -> `OK` (issues with dictionary …
=> [pt] Update dictionary to v1.1.0

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/english.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
This PR contains improvements to the multi-token spelling corrections.
- now that we actively ignore possible English words with the `_english_ignore_` tag, the entity containing multi-token exceptions could be significantly simplified;
- instead of FPs with `the`, we were getting tonnes of **FNs** — e.g.:
- _Ela lê o jornal the guardian toda manhã._
- the two-token sequence _the guardian_ is tagged (comme il faut) with `_english_ignore_`;
- because 'the' was present in the `exceptions_multitoken_spell` entity, 'the guardian' was **not** matched by `PT_MULTITOKEN_SPELLING_TWO`;
- this left the user with an **uncorrected** lowercase 'the guardian'.
Removing those English words from `exceptions_multitoken_spell` ensures that we correct the letter case of global multi-token entites beginning …
=> [pt] Improve multi-token foreign word checks

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have rewritten the complete rule, and now it should work very well.
```
Portuguese (Portugal): 73 total matches
Portuguese (Portugal): 854003 total sentences considered
```
[2.txt](https://github.com/user-attachments/files/15859782/2.txt)
=> [pt-PT] Rewrote rule ID:PRAZER_EM_CONVIDAR to ID:PRAZER_GOSTO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have removed the temp_off from the rule:
https://internal1.languagetool.org/regression-tests/via-http/2024-06-17/pt-PT_full/result_style_PRAZER_GOSTO%5B1%5D.html
There isn't much magic in this rule as the suggestion sentence says: if it is used for pleasure/sex activities one uses “prazer” and in all other cases “gosto”.
=> [pt-PT] Removed "temp_off" from rule ID:PRAZER_GOSTO

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
I had to use the word “possível” for the AP to work properly.
Using adjectives and nouns would work badly.
=> [pt] Added AP to rule ID:GENERAL_NUMBER_AGREEMENT_ERRORS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
PÔR_FIM_TERMO (25 hits)
https://internal1.languagetool.org/regression-tests/via-http/2024-07-01/pt-PT_full/result_style_P%C3%94R_FIM_TERMO%5B1%5D.html
DIFICULDADES_PROVAÇÕES (0 hits)
After the checks I will press “merge” since they are pt-PT rules (Pedro).
Thanks!
=> [pt-PT] Removed temp_off from rule ID:PÔR_FIM_TERMO and ID:DIFICULDADES_PROVAÇÕES

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is another enhancement of an old rule now with more hits.
😛 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛
=> [pt] Improved rule ID:VERBO_SER_ÚTIL_PARA_SERVIR_PARA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have removed the temp_off of:
SIMPLIFICAR_A_XXX_DE_VOCES
https://internal1.languagetool.org/regression-tests/via-http/2024-07-17/pt-PT_full/result_style_SIMPLIFICAR_A_XXX_DE_VOC%C3%8AS%5B1%5D.html
CIENTÍFICO_DETERMINADAS_ESPECÍFICAS
https://internal1.languagetool.org/regression-tests/via-http/2024-07-17/pt-PT_full/result_style_CIENT%C3%8DFICO_DETERMINADAS_ESPEC%C3%8DFICAS%5B1%5D.html
VERBO_SER_ÚTIL_PARA_SERVIR_PARA
https://internal1.languagetool.org/regression-tests/via-http/2024-07-17/pt-PT_full/result_style_VERBO_SER_%C3%9ATIL_PARA_SERVIR_PARA%5B1%5D.html
After it passes the checks, I will merge it since it is pt-PT.
Thanks!
=> [pt-PT] Removed "temp_off" from rules

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have added “[pt-PT]” to the rule names in pt-PT that didn't have it to make the whole process coherent.
It is only useful for the LibreOffice Extension (Fred Kruse).
After it passes the checks, I will merge it.
=> [pt-PT] Added "[pt-PT]" to missing rule names

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
ID:FAZER_DESPORTO has zero hits.
ID:SIMPLIFICAR_É_NECESSÁRIO_TER_REQUER has four hits:
https://internal1.languagetool.org/regression-tests/via-http/2024-07-20/pt-PT/result_style_SIMPLIFICAR_%C3%89_NECESS%C3%81RIO_TER_REQUER%5B1%5D.html
Removing temp_off and merging after it passes the checks, since it is pt-PT.
=> [pt-PT] Removed temp_off of ID:FAZER_DESPORTO and ID:SIMPLIFICAR_É_NECESSÁRIO_TER_REQUER

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
It had zero hits, so I am removing the “temp_off”.
=> [pt-PT] Removed temp_off from rule ID:PERANTE_O_MESMO_IDENTICO

languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/Rule.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java
- allow controlling whether premium rules run as part of hidden matches
- expose setting as configuration option for RemoteRules
- respect setting when configuring rules in PipelinePool
=> feat(core): add Rule property includedInHiddenMatches

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
For the internal feedback here:
https://languagetooler.slack.com/archives/CG7ULA9T6/p1721383643012519
>But neither deployment, nor the local development flow, is containerized yet.
I believe there are two solutions here, and I'm not sure if my change is the best one.
Either an AP to block the match for the first subrule (which is what I did), or expand the second subrule to remove the second comma (after 'flow') and write an AP to block the HydraLeo match.
Do you have a preference or another idea?
=> [en] improve NEITHER_NOR_SUPERFLUOUS_COMMA

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have improved this pt-PT rule.
=> [pt-PT] Improved rule ID:DEPOIS_É_QUE_VERBO_DEPOIS_VERBO_PT_PT

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have rewritten another pt-PT rule, I will merge it after the checks since it is pt-PT.
=> [pt-PT] Rewrote rule ID:SIMPLIFICAR_QUE_VERBO_A_VERBOINFINITIVO

languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleTest.java
allows rules to be disabled when an abtest parameter matching a regex is set
=> feat: add option excludeABTest to remote rule

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
=> [pt-PT] Rewrote rule ID:GRANDES_ENORMES_RECURSOS_FINANCEIROS_AVULTADOS

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I guess that maybe it is time to start removing “temp_off” from rules created weeks or months ago:
BÁSICO_ELEMENTAR
https://internal1.languagetool.org/regression-tests/via-http/2024-07-22/pt-BR_full/result_style_B%C3%81SICO_ELEMENTAR%5B1%5D.html
MUITO_BASTANTE_EXTENSIVAMENTE
https://internal1.languagetool.org/regression-tests/via-http/2024-07-22/pt-BR_full/result_style_MUITO_BASTANTE_EXTENSIVAMENTE%5B1%5D.html
😛 😛 😛 😛 😛 😛 😛 😛
=> [pt] Removed "temp_off" from rule ID:BÁSICO_ELEMENTAR and ID:MUITO_BASTANTE_EXTENSIVAMENTE

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/disambiguation.xml
Simple, quick and safe fix for: https://app.asana.com/0/1207342200148885/1208022931754948/f
PERSOS[1] rule in the disambiguation file was changing "chéris" POS to Noun automatically, causing issues when it's used as a verb.
=> [fr] PERSOS_fix

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is the rule.
Notice that all hits except one happened with the verb “ajudar”:
```
Portuguese (Portugal): 27 total matches
Portuguese (Portugal): 854003 total sentences considered
```
Results file .txt:
[0.txt](https://github.com/user-attachments/files/16589402/0.txt)
Here is the ChatGPT 4o “background”:
=> [pt] Added formal rule ID:ESTAR_AQUI_PARA_INF_VIR_INF

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have removed the "temp_off".
https://internal1.languagetool.org/regression-tests/via-http/2024-08-14/pt-BR/result_style_ESTAR_AQUI_PARA_INF_VIR_INF%5B1%5D.html
=> [pt] Removed "temp_off" from rule ID:ESTAR_AQUI_PARA_INF_VIR_INF

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/messages.ent
I have added this message because of the dozens of pt-PT rules such as:
```
<rule>
<pattern>
<token inflected='yes'>o</token>
<token>nem-nem</token>
</pattern>
<message>Esta é uma expressão oral. Reveja.</message>
<url>https://pt.wiktionary.org/wiki/a_nem-nem</url>
<short>Coloquialismo</short>
<example correction=''><marker>a nem-nem</marker></example>
</rule>
```
Also, would it be a good idea for me to remove all `<short>` messages in pt-PT, since they are terrible? A person is revising a document, and it shows a suggestion with just one or two words which is completely unclear and not useful at all… I prefer longer explaining messages.
`<short>Coloquialismo</short>`
=> [pt] Added ENTITY colloquialism_msg to messages.ent

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Just a "temp_off" removal from a colloquialism subrule I created days ago.
=> [pt-PT] Removed "temp_off" from subrule in ID:INFORMALITIES

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @p-goulart and @susanaboatto ,
What about now?:
https://internal1.languagetool.org/regression-tests/via-http/2024-08-20/pt-BR/result_style_ESTAR_AQUI_PARA_INF_VIR_INF%5B1%5D.html
Thanks!
=> [pt] Removed "temp_off" in rule ID:ESTAR_AQUI_PARA_INF_VIR_INF

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have removed the “temp_off”.
I gave a quick look at the nightly diff, and it seems okay?:
https://internal1.languagetool.org/regression-tests/via-http/2024-08-23/pt-BR_full/result_style_QUE_TER_COMO_POR_NOME_ADJ%5B1%5D.html
I will try to remove as many “temp_off”'s as possible before the next release of LanguageTool.
Thanks!
=> [pt] Removed "temp_off" from rule ID:QUE_TER_COMO_POR_NOME_ADJ

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
GEC AP targeting HALLOWEEN gender FP, this fix is important since the content team is working on a new blog entry on this subject.
=> [fr] GC_HALLOWEEN_GENDER_AP

languagetool-language-modules/crh/src/main/resources/org/languagetool/rules/crh/grammar.xml
New grammar and spelling rules added
Added rulegroups:
Phraseology (20 rules)
Cyrillic verb case collocations (2 rules)
=> [crh] Crimean Tatar language rules updated and expanded

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is a formal rule:
```
Portuguese (Portugal): 467 total matches
Portuguese (Portugal): 854003 total sentences considered
```
[13.txt](https://github.com/user-attachments/files/16827816/13.txt)
=> [pt] Added rule ID:OS_DOIS_AS_DUAS_AMBOS_AMBAS

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
@GillouLT 
AI_FR_GGEC_MISSING_PUNCTUATION_PERIOD creates undesired matches, for example, in bulleted lists. We can rely on other rules, with proper exceptions, for this.
=> [fr] ignore adding punctuation at the sentence end
