languagetool-org/languagetool

languagetool-language-modules/ja/src/main/resources/org/languagetool/rules/ja/grammar.xml
I fixed the example of the rule.
=> Fix example of SINGLE-MARKON

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
ignore  "Big Ben/Data", "à la carte", "Ave Maria", "coram publico"
=> added some [de] rules to ignore

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
A possible solution to:http://languagetool-user-forum.2306527.n4.nabble.com/A-false-tag-about-quot-run-quot-td4643530.html#a4643553
=> A false tag about "run" in "The hotel is run by his uncle."

languagetool-language-modules/km/src/main/resources/org/languagetool/rules/km/grammar.xml
=> Third try for Khmer addition

languagetool-language-modules/pl/src/main/resources/org/languagetool/resource/pl/disambiguation.xml
=> [pl] fix name of DO_CZYSTA

languagetool-language-modules/pt/pt-BR/grammar.xml
I start the pt-BR rules. Also i add folder with grammar.xml into ` languagetool\languagetool-language-modules\pt  ` please check if place is ok.
http://forum.languagetool.org/users/matheuspoletto
Best Regards, Matheus Otavio Poletto - from Brazil
=> Add folder pt-BR with grammar.xml

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
Hi, here are more 15 rules i wrote. Thx
=> +15 rules to pt-BR grammar.xml

languagetool-language-modules/ru/src/main/resources/org/languagetool/rules/ru/grammar.xml
Solved agreement by number of #451
=> Unification

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/compounds.txt, languagetool-language-modules/el/src/main/java/org/languagetool/tokenizers/el/GreekWordTokenizerImpl.java, languagetool-language-modules/el/src/main/resources/org/languagetool/resource/el/hunspell/README_el_GR.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/agid-readme.txt, languagetool-language-modules/fa/src/main/resources/org/languagetool/rules/fa/grammar.xml, languagetool-language-modules/km/src/main/resources/org/languagetool/rules/km/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/README_pt_PT.txt, languagetool-language-modules/sv/src/main/resources/org/languagetool/rules/sv/grammar.xml
All of them were found by codespell.
=> Fix some typos

languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java
=> Fix typo in abbreviation

languagetool-standalone/README.md
Update old URL Spanish Freeling project
=> Update README.md (Update Old URL)

README.md
=> README: Add hints for shallow clone

languagetool-core/src/main/java/org/languagetool/rules/UppercaseSentenceStartRule.java, languagetool-core/src/test/java/org/languagetool/languagemodel/LanguageModelTest.java
FindBugs report: Condition has no effect
Remove the useless conditions.
=> languagetool-core: Remove useless code

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Changes in comma rules to fit false positives
=> update german grammar.xml

languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/pt_BR.aff, languagetool-language-modules/ru/src/main/java/org/languagetool/language/Russian.java, languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/RussianVerbConjugationRule.java, languagetool-language-modules/ru/src/test/java/org/languagetool/rules/ru/RussianVerbConjugationRuleTest.java
Hi,
I've noticed that there are not any rules for verb conjugation in Russian. For example, if I write "It's sitting". LT consideres it as right sentence. So, I've tried to create a rule, but I checked my rule only by the test class, that I've also added. Is it possible to check code using application?
=> [ru] rule to check verb conjugation

languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/RussianVerbConjugationRule.java, languagetool-language-modules/ru/src/test/java/org/languagetool/rules/ru/RussianVerbConjugationRuleTest.java
add headers to RussianVerbConjugationRule.java and RussianVerbConjugationRuleTest.java
=> [ru] add header

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> German grammar

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Add some new rules for Duden-recommandations to German grammar.xml
Merge the rules from f-knorr with the rules in the new category (use a little bit more compact formulation for simular rules).
=> add some new rules for recomanded writing to german grammar.xml

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Some rules added for compound spelling.
Added an exception for an older rule.
=> Add some rules to german grammar.xml

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
fix false positives in German grammar.xml
=> [de] german grammar.xml fix false positives

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
add new rule for compound spelling with prefix 'über'.
fix the rule "KOMMA_VOR_ERLAUTERUNG"
=> [de] german grammar.xml add a new rule / fix another

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
I changed two URLs so that they lead to the specific rule at duden.de and not just the main topic.
=> Changed links to duden.de

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/compounds.txt
Added some new compounds to compounds.txt. All of these are words that I have seen written somewhere with a space between the words ("Deppenleerzeichen").
=> [de] Added compounds to compounds.txt

languagetool-language-modules/de/src/main/java/org/languagetool/tagging/de/GermanTagger.java, languagetool-language-modules/de/src/test/java/org/languagetool/tagging/de/GermanTaggerTest.java
Sorry about the new pull request. I seem to have messed up the old one.
Here is the modified class with the requested changes and unit test.
=> German tagger improvement for dash-linked words

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
The last request was about :
Validity extension of gender and number agreement rules in French. 
And this one is an answer to :
[ https://languagetool.org/regression-tests/20180108/result_fr_20180108.html ](https://languagetool.org/regression-tests/20180108/result_fr_20180108.html)
=> Refinement of last request (lo-fr-171229 #869)

languagetool-dev/src/main/java/org/languagetool/dev/RuleOverview.java, languagetool-dev/src/main/java/org/languagetool/dev/archive/SimpleRuleCounter.java
Language sorting can be improved using Comparator.comparing and List method .sort
=> Language sorting improvements

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/disambiguation.xml, languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
Hi all,
Here is an enhancement for detecting Roman numerals in Spanish (issue #816).
Hope everything is fine.
;-)
=> Detect Roman numerals (issue #816)

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
Hello,
This PR makes some corrections in the Spanish grammar.xml.
=> [es] fix typos and outdated URLs in grammar.xml

languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
Solving issue #63. 
*Firstly*, get message from `Rule` - run it on the first `IncorrectExample`
*Secondly*, run `LanguageTool`, i.e. all enabled Rules, on this message
Notice, that some matches are ignored:
- If `RuleMatch` was created by the same `Rule` that we are checking - it doesn't count
- If `RuleMatch` is in brackets or quotes - it doesn't count *but this is customizable*
Disabled by default rules are configurable, I disabled some that are the most frequent, but they still might carry useful information and suggest some reasonable fixes.
Some (probably most) of these matches don't make a lot of sense, but some certainly do.
I can start fixing Rules that this test found mistakes in, should I?
=> Check rules' messages by LanguageTool: issue #63

languagetool-language-modules/ru/src/main/resources/org/languagetool/rules/ru/grammar.xml, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
Finish test from #935 and fix mistakes in Russian rules.
I left fixing English rules to native English speakers and fixed Russian ones.
=> Add printing error's location and fixing Russian rules

languagetool-tools/src/main/java/org/languagetool/tools/SynthDictionaryBuilder.java
Attempted fix for #746, write in in the same directory as the .dict file instead of temp
=> updated tags file location

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
[Collective Noun Verb Agreement.pdf](https://github.com/languagetool-org/languagetool/files/1821291/Collective.Noun.Verb.Agreement.pdf)
Kindly, review the changes @danielnaber.
=> Added collective noun verb agreement

languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java
Just figured out that there can be uninformative exceptions. Added some handling.
=> re:pr#940 | added pretty exceptions handling

languagetool-language-modules/ca/src/main/resources/org/languagetool/rules/ca/replace.txt
=> [ca] Replace "debo" with "debò"

languagetool-office-extension/src/main/java/org/languagetool/openoffice/Main.java
This worked for me.
Let me know if it needs anything else :+1:
=> Issue #957: Changed logging to use XDG_DATA_HOME if available

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Hello.
I examined almost all URLs in the English grammar.xml and fixed some unavailable ones.
=> [en] fix outdated URLs in grammar.xml

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Fix #866
Replace #874 
Ok i hope spaces and tabs are ok now :)
=> [fr] Fix issue #866 : sentences with "qui"

languagetool-language-modules/sv/src/main/resources/org/languagetool/rules/sv/grammar.xml
Spelling errors, corrected capitalisation, shortened some sentences to save space in a GUI, corrected some prepositions, changed some wordings
=> Various fixes to Swedish grammar.xml

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
See https://en.wikipedia.org/wiki/Discoverability
=> [en] add 'discoverability'

.gitignore, languagetool-core/src/main/java/org/languagetool/rules/ConfusionSetLoader.java, languagetool-dev/scripts/disableProhibitedCompounds.sh, languagetool-dev/scripts/extractProhibitedCompounds.sh, languagetool-dev/scripts/extractProhibitedCompoundsErrors.sh, languagetool-dev/src/main/java/org/languagetool/dev/ExportGermanNouns.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/AllConfusionRulesEvaluator.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/AutomaticProhibitedCompoundRuleEvaluator.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/ProhibitedCompoundRuleEvaluator.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/RuleEvalResult.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/RuleEvalValues.java, languagetool-language-modules/de/pom.xml, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/ProhibitedCompoundRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/ProhibitedCompoundRuleTest.java, languagetool-standalone/src/main/resources/third-party-licenses/README.txt, languagetool-standalone/src/test/java/org/languagetool/rules/patterns/PerformanceTest.java
Added automatic search tools for compound confusion pairs
Added Aho-Corasick substring matching to ProhibitedCompoundRule for better performance with large confusion sets
=> [de] Extended ProhibitedCompoundRule

languagetool-server/scripts/database/migrations/20180927_add_check_log_user_id_index.sql, languagetool-server/scripts/database/migrations/20180927_extend_check_log_language_detected_column_size.sql
created new migrations directory for alterations to the database,
added statements to fix language_detected field in check_log being too short
and improve performance for some queries on check_log
=> minor database changes

languagetool-server/src/main/java/org/languagetool/server/DatabaseAccess.java, languagetool-server/src/main/resources/org/languagetool/server/mybatis-config.xml
better exception logging in DatabaseAccess
configured keepalive/ping query in mybatis
=> debugged sql connection errors

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-server/src/main/java/org/languagetool/server/ActiveRules.java, languagetool-server/src/main/java/org/languagetool/server/ActiveRulesMBean.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServer.java
enable with -DmonitorActiveRules
will keep track of rules and sentences being processed at the moment
and allow to view this information via monitoring tools like jconsole
purpose: track rules that cause endless loop under certain conditions
=> added optional JMX monitoring

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleHandler.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleLoader.java
useful for debugging e.g. duplicate rule IDs
=> added source file to PatternRule.toString()

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseAccess.java
see https://github.com/mybatis/mybatis-3/issues/821
also added comment w.r.t. new field check_mode in check_log table
=> workaround: close pooled connections properly

languagetool-server/scripts/database/migrations/20181105_modify_check_log_text_session_id_column.sql, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Extended field size of text_session_id in check_log, added code to save id from chrome addon
=> Better textSessionId, compatibility with chrome

languagetool-server/src/main/java/org/languagetool/server/ErrorRequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/RequestLimiter.java, languagetool-server/src/test/java/org/languagetool/server/ErrorRequestLimiterTest.java
client, referer and user-agent should now always be provided for entries to access_limits table
=> fixed missing fields in some logs from RequestLimiter

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/names.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@janschreiber what do you think?
=> [de] add words

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
IVA = VAT (tax)
DNI = https://en.wikipedia.org/wiki/Documento_Nacional_de_Identidad_(Spain)
recomendable = https://www.spanishdict.com/translate/recomendable
logo = short form of logotipo (https://es.wikipedia.org/wiki/Logotipo)
FB = Common abbreviation of Facebook
=> [es] add common spanish words

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
Alan = Name
BBVA = Banco Bilbao Vizcaya Argentaria
Eladio = Name
Eric = Name
IP = Abbreviation for Internet Protocol
iPod = Apple Device
HTML = Markup Language
IVA = tax (https://es.wikipedia.org/wiki/Impuesto_al_valor_agregado)
Jennifer = Name
Karen = Name
link = https://es.wikipedia.org/wiki/Hiperenlace
Londres = London (https://es.wikipedia.org/wiki/Londres)
Marisol = Name
Max = Name
Miami = City
Motorola = Company
MXN = Mexican Peso (https://es.wikipedia.org/wiki/Peso_mexicano)
Nintendo = Company
Paco = Name
PC = Personal Computer
PVC = polyvinyl
Telcel = Telecommunication company
URL = Web address
Word = Microsoft Word
=> [es] add words to spelling.txt

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
Sorted and added new (uncritical) company, person and product names.
@danielnaber this should also be easy to merge.
=> [es] add some nouns to dictionary

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
@MikeUnwalla here's a list of words that many people add to their personal dictionary. I marked the words that I already added to `added.txt` in bold. For the rest I don't know if they should be included and if so what POS they have.
Can you provide feedback which words are legit and add the necessary POS?
* **AdWords** (Product Name)
* **Akmal** (Person Name)
* **APIs** (plural of Application Programming Interface)
* **ASINs** (plural of Amazon Standard Identification Number)
* **Astrid** (Person Name)
* availabilities
* benchmarked
* chargebacks
* Costa Rica (Country)
* cyber
* **Daniela** (Person name)
* decrypt
* dropdown
* eco-friendly
* endeavour
* flyer
* greyed
* **Groupon** (Company Name)
* **Huffington** (Newspaper: Huffington Post)
* **ICANN** (Organization)
* impactful
* …
=> [en] add words to dictionary

languagetool-language-modules/it/src/main/resources/org/languagetool/resource/it/hunspell/spelling.txt
Add some common names to Italian dictionary. @danielnaber I think this is safe to merge.
=> [it] add some words

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
@MikeUnwalla I added some common company, product, city and person names
=> [en] add names to dictionary

languagetool-core/src/main/java/org/languagetool/ResultCache.java, languagetool-server/pom.xml, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Added labels to check metrics: language, mode, client
Added status for hidden matches server
Added instrumentation for ResultCache
Counting rule matches: total per check, matches per rule ID
=> Extended Prometheus instrumentation

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
Added common words that are very often added to the user's personal dictionary.
=> [es] add words to spanish dict

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
See https://www.merriam-webster.com/dictionary/undiagnosed
=> [en] added 'undiagnosed' to spelling.txt

languagetool-dev/src/main/java/org/languagetool/dev/RuleDetails.java
Adds a column with category id & description to CSV with rule ids
=> added script for adding more information about rules to reports

languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
See https://github.com/languagetool-org/languagetool/issues/1560
=> [en] suggest McDonald's (closes #1560)

languagetool-core/src/main/java/org/languagetool/ResultCache.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Use `cacheTTLSeconds` in server configuration.
=> made ResultCache expire time configurable for server

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@danielnaber habe ein paar Namen bzw. Substantive hinzugefügt.
Die Anglizismen "Sale", "Exchange", "MC" und "Professional" stehen im Duden.
"Habeck" = Nachname des möglicherweise nächsten deutschen Kanzlers.
=> [de] add words to german dict

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@danielnaber bitte einmal schauen.
Viele Anglizismen, die aber mittlerweile auch im Duden stehen (Ads, cheers, Benefits, Executive, Battle ...)
=> [de] add words to dict

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanWordRepeatRule.java
https://www.duden.de/rechtschreibung/moin__moin_
=> [de] fix false alarm in word repetition 'Moin moin'

languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java
Added histogram metrics for check latency and size
=> New Prometheus metrics to enable alerts based on percentiles

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
Closes https://github.com/languagetool-org/languagetool/issues/1655
=> [de] fix more false alarms caused by DE_AGREEMENT

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java
Resolves:
https://github.com/languagetool-org/languagetool/issues/1696
https://github.com/languagetool-org/languagetool/issues/1519
=> [de] fix some false alarms caused by DE_CASE

languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt, languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
See https://forum.languagetool.org/t/es-usage-of-am-pm/4522
=> [es] rule for am/pm abbreviation

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/VerbAgreementRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/VerbAgreementRuleTest.java
=> [de] fixes for DE_VERBAGREEMENT

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java
=> [de] fixes for DE_CASE

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
For https://github.com/languagetool-org/languagetool/issues/1694
@MikeUnwalla please let me know if this is good.
=> [en] improve SEVERAL_OTHER

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
See #1811
@MikeUnwalla please let me know what you think. Thanks in advance.
=> [en] improve A_INFINITIVE (closes #1811)

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/create_dict.sh
Update the LT version used to the current one (4.7-SNAPSHOT) and document some additional requirements for the script.
=> update version, doc requirements

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Es könnte noch dauernd, bis ich alles gesammelt habe, denn es kommen immer wieder neue Wörter dazu.
=> Nachtteil statt Nachteil

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Hey @MikeUnwalla this is my attempt to fix https://github.com/languagetool-org/languagetool/issues/1960
What do you think?
Thanks in advance.
=> [en] improve IT_VBZ

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
rauszunehmen -> Infinitiv mit "ZU" von rausnehmen https://www.duden.de/rechtschreibung/rausnehmen
=> [de] add 'rauszunehmen'

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
Just made this mistake myself. Seems like a common confusion.
=> [en] rule to detect confusion of 'heave' and 'heavy'

languagetool-language-modules/pl/src/main/resources/org/languagetool/resource/pl/disambiguation.xml, languagetool-language-modules/pl/src/main/resources/org/languagetool/resource/pl/hunspell/spelling.txt
I have added some more Polish words and a simple disambiguation rule to avoid having temperature and degrees marked as misspelling.
=> [pl] add common ignored words and add disambiguation rule

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java
Quick fix to not parse numbers in number ranges as negative,
bigger changes needed to properly handle ranges (i.e. proper range for match + suggestions for start and end)
=> partial fix for #2170

languagetool-core/src/main/java/org/languagetool/language/LanguageIdentifier.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseAccess.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java, languagetool-server/src/main/java/org/languagetool/server/ResultExtender.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/resources/logback.xml
Replaced some print statements in the server code with slf4j logging statements to add levels and allow easier parsing in log aggregation tools
=> Convert print statements to proper logging

languagetool-language-modules/ga/src/main/resources/org/languagetool/resource/ga/disambiguation.xml, languagetool-language-modules/ga/src/main/resources/org/languagetool/rules/ga/grammar.xml
=> [ga] not PresSubj:Neg if not after 'nár'

languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java
simplified
now works when there are suggestions with equal values for
replacement
=> fixed reordering of SuggestedReplacement objects

languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleMetrics.java, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java
neccessary for averaging quantiles across servers
also removed some deprecated, unused metrics
=> replaced Summary with Histogram in RemoteRuleMetrics

languagetool-core/src/main/java/org/languagetool/rules/AbstractUnitConversionRule.java
extended ignored range and matched area + suggestions
=> fixed #2508

languagetool-gui-commons/src/main/java/org/languagetool/gui/Configuration.java
fixes https://forum.languagetool.org/t/pb-running-server-as-non-root-service/5440
=> fixed exception because of missing GUI configuration file in server

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Issue #1081 of the premium repo
=> [fr] added new antipattern for à la base in ACCORD_GENRE

languagetool-core/src/main/java/org/languagetool/rules/AbstractDashRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/EnglishDashRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/EnglishDashRuleTest.java, languagetool-language-modules/pl/src/main/java/org/languagetool/language/Polish.java, languagetool-language-modules/pl/src/main/java/org/languagetool/rules/pl/DashRule.java, languagetool-language-modules/pl/src/test/java/org/languagetool/rules/pl/DashRuleTest.java, languagetool-language-modules/pt/src/main/java/org/languagetool/language/AngolaPortuguese.java, languagetool-language-modules/pt/src/main/java/org/languagetool/language/BrazilianPortuguese.java, languagetool-language-modules/pt/src/main/java/org/languagetool/language/MozambiquePortuguese.java, languagetool-language-modules/pt/src/main/java/org/languagetool/language/PortugalPortuguese.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PostReformPortugueseDashRule.java, languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/PreReformPortugueseDashRule.java, languagetool-language-modules/ru/src/main/java/org/languagetool/language/Russian.java, languagetool-language-modules/ru/src/main/java/org/languagetool/rules/ru/RussianDashRule.java, languagetool-language-modules/ru/src/test/java/org/languagetool/rules/ru/RussianDashRuleTest.java
Currently all DashRules don't have a correct category.
=> Grazie migration: Add category and messages to DashRule

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
Add possibility for user to stop grammar check if he is no longer interested in results. Useful for local use-cases, when change of document by user should lead to cancel of all background checks.
=> Grazie migration: Add check cancelled callback to JLanguageTool

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
Add possibility to request all spellchecking rules from JLanguageTool.
=> Grazie migration: Add JLanguageTool.getAllSpellingCheckRules method

languagetool-core/src/main/java/org/languagetool/tagging/BaseTagger.java, languagetool-core/src/main/java/org/languagetool/tagging/ManualTagger.java, languagetool-core/src/main/java/org/languagetool/tagging/MorfologikTagger.java, languagetool-language-modules/en/src/main/java/org/languagetool/tagging/en/EnglishTagger.java
Add possibility to intern string tags for Taggers. Intern tags for English because it have a megabytes of duplicated strings.
=> Grazie migration: Add intern tags for taggers and EnglishTagger

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/AbstractDashRule.java, languagetool-core/src/main/java/org/languagetool/rules/RuleMatch.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AvsAnRule.java, languagetool-language-modules/pl/src/main/java/org/languagetool/rules/pl/DecadeSpellingFilter.java
Add possibility to know rule pattern range.
=> Grazie migration: Add pattern position to RuleMatch

languagetool-core/src/main/java/org/languagetool/tools/StringTools.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AvsAnRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/synthesis/en/EnglishSynthesizer.java, languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
If it at the start of the sentence you need to lowercase word after determiner.
=> Grazie migration: Lowercase words if necessary after adding determiner for English language

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/disambiguation.xml, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Added antipatterns for ACCORD_NOMBRE #1057
Added rule TOUT_A_COMMENCE #1080
=> Added antipatterns & new rule

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Transferred a few rules from premium.
Added new & to existing rule for #1141
Added new dictionary entries
=> [fr] transfer rules from premium & added rule for premium #1141

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
- Adjusted rule #2767; 
- Adjusted rules;
- Disabled temp_off on new rules;
- Added exception for accord_genre;
- Added rule priority for BYTES and Y_A
=> [fr] Improvements ↓

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
Imperativ renn (rennen)
Z. B. Renn weg!
=> Add Verb #2740

languagetool-core/src/main/java/org/languagetool/Languages.java
This is needed if you want to download languages and use them at runtime.
=> Grazie migration: Add possibility to dynamically add languages by class names

languagetool-core/src/main/java/org/languagetool/LanguageAnnotator.java, languagetool-core/src/test/java/org/languagetool/LanguageSpecificTest.java, languagetool-dev/src/main/java/org/languagetool/dev/NoSuggestionRuleList.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/ga/src/main/java/org/languagetool/tagging/ga/IrishTagger.java, languagetool-language-modules/uk/src/main/java/org/languagetool/tagging/disambiguation/uk/UkrainianHybridDisambiguator.java
This is for better readability and slightly better performance.
=> Use collection.isEmpty()

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/symspell/implementation/SymSpell.java, languagetool-core/src/main/java/org/languagetool/synthesis/BaseSynthesizer.java, languagetool-core/src/test/java/org/languagetool/rules/ConfusionSetLoaderTest.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternRuleTest.java, languagetool-core/src/test/java/org/languagetool/tagging/CombiningTaggerTest.java, languagetool-core/src/test/java/org/languagetool/tools/StringToolsTest.java, languagetool-dev/src/main/java/org/languagetool/dev/archive/RuleSimplifier.java, languagetool-dev/src/main/java/org/languagetool/dev/archive/WordTokenizer.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/ConfusionFileIndenter.java, languagetool-dev/src/main/java/org/languagetool/dev/bigdata/ConfusionSetOccurrenceLookup.java, languagetool-dev/src/main/java/org/languagetool/dev/diff/ResultToHtml.java, languagetool-dev/src/main/java/org/languagetool/dev/httpchecker/HttpApiSentenceChecker.java, languagetool-gui-commons/src/main/java/org/languagetool/gui/Configuration.java, languagetool-http-client/src/main/java/org/languagetool/remote/RemoteLanguageTool.java, languagetool-language-modules/ca/src/main/java/org/languagetool/rules/ca/PronomFebleDuplicateRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/chunking/GermanChunker.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CompoundCoherencyRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/SuggestionRegressionTest.java, languagetool-language-modules/el/src/main/java/org/languagetool/rules/el/NumeralStressRule.java, languagetool-language-modules/uk/src/main/java/org/languagetool/tagging/uk/CompoundDebugLogger.java, languagetool-standalone/src/test/java/org/languagetool/LanguageAnnotatorTest.java, languagetool-tools/src/main/java/org/languagetool/tools/DictionaryBuilder.java, languagetool-tools/src/main/java/org/languagetool/tools/SpellDictionaryBuilder.java, languagetool-tools/src/main/java/org/languagetool/tools/SynthDictionaryBuilder.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/dumpcheck/WikipediaSentenceExtractor.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/index/Indexer.java, languagetool-wikipedia/src/main/java/org/languagetool/dev/wikipedia/TextConverter.java
This has a slight better performance
=> Use character instead of string

languagetool-server/src/test/java/org/languagetool/server/HTTPTools.java
With this change, all tests pass.
=> Fix UserDictTest with Maven on Windows

languagetool-core/src/main/java/org/languagetool/rules/GRPCConfusionRule.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/ml/MLServerProto.java, languagetool-core/src/main/proto/ml_server.proto, languagetool-core/src/main/resources/org/languagetool/MessagesBundle_en.properties
Allow remote servers to provide rule descriptions and match messages
prioritize remote descriptions, allow fallback to local ones, else raise error
Delete obsolete messages for GRPCConfusionRule
=> new version of MLServer protocol

languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java
Because of prior aggregation, existing Histogram metrics for request latency / size won't suffice.
=> added metric for relative processing speed

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Language.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCConfusionRule.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/ml/MLServerProto.java, languagetool-core/src/main/proto/ml_server.proto, languagetool-core/src/test/java/org/languagetool/rules/GRPCRuleTest.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java, languagetool-server/src/main/java/org/languagetool/server/Pipeline.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/PipelinePoolTest.java
need their own implementation to honor new setting
pass information through: parameter for remote rule, extended gRPC protocol
=> pass inputLogging parameter to remote rules

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
Grafikkarte war gnädig und ist nur einmal abgestürzt.
=> Add Zuruf #3327

languagetool-client-example/pom.xml
=> add maven plugin to avoid release version 5 not supported

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java
offset adjustment for remote rule results didn't distinguish duplicated sentences at different positions in the text
=> fixed missing results for duplicated sentences

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
https://www.duden.de/rechtschreibung/Showdown
=> Add Showdown

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
Die Maskulinformen sind bereits vorhanden
=> Add Neutrumformen von Gokart

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
Disabled verbose logging for remote result cache
Added temporary logging for waiting on remote results
=> Small changes to logging for remote rules

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-GB/replace.txt
Veränderungen wie besprochen... bis auf ein paar Fälle, wo mir beim Eintragen noch was aufgefallen ist (z.B. dass es doch nur in eine Richtung geht)
=> [en-GB] update replace.txt

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
not vital, but since I've spotted it...
=> [en] add anacoluthon to spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] eliminate FP for Bell

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
These two unfinished rulegroups make up for most of the temp_off rules in the test
=> [fr] ACCORD_NOM_VERBE & POUR_PAS_QUE --> off (not ready yet)

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
This monster rulegroup is now ready to be released to the public. `temp_off` to test it one last time.
=> [fr] temp_off POUR_PAS_QUE

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
Fixed loop, eliminated other potential loops, eliminated FPs
=> [en] preventing loop, eliminating FPs (ANY_MORE + JJ)

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
This fixes the first out of five sub-rules. The other four should not take too long either. I'm curious to see the impact afterwards!
=> [fr] amendments ACCORD_NOMBRE[1]

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java
=> [de] add antipattern to CaseRule for 'um das herauszubekommen'

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
https://www.duden.de/rechtschreibung/Pinata
Ist ziemlich beliebt geworden und nicht nur auf Kinderfesten vertreten.
=> Add Word Piñata

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
https://www.duden.de/rechtschreibung/Holster
=> Add Word Holster

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java
Using try-with-resources block to close the Scanner which reads the aff file.
=> Using try-with-resources block to close the Scanner which reads the aff file.

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
As signalled in [#3766](https://github.com/languagetool-org/languagetool/issues/3766)
=> [fr] correcting URL in AUX_ETRE_VCONJ

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Spotted by Wild94 in [#3766](https://github.com/languagetool-org/languagetool/issues/3766)
=> [fr] relocate misplaced RPERSSUJ_ETRE_V

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling_en-GB.txt
Just added some more new words:
* hasteful - [Merriam-Webster](https://www.merriam-webster.com/dictionary/hasteful) | [Lexico](https://www.lexico.com/definition/hasteful)
* hastefully - [Merriam-Webster](https://www.merriam-webster.com/dictionary/hastefully) | [Lexico](https://www.lexico.com/definition/hastefully)
* hastelessness - [Lexico](https://www.lexico.com/definition/hastelessness)
This adds "hasteful" and "hastefully" to the global English dictionary, and "hastelessness" to the British dictionary.
---
I attempted to do the POS tags, but got confused if these words needed them and what tags.
I'm reading more about it, so I can take the correct action in the future, sorry about that.
=> Added "hasteful", "hastefully", "hastelessness"

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java
because immunization is pretty expensive
=> PatternRule: check for antipatterns only after a rule actually produced problems

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java
to avoid expensive matching for rules whose simple regexps are definitely inapplicable to the current sentence
=> PatternRule.canBeIgnoredFor: check token form hints as well #3744

languagetool-core/src/main/java/org/languagetool/MultiThreadedJLanguageTool.java
allocate thread_count futures instead of rule_count
For me, this speeds up the analysis of 5000 English sentences (via `SentenceSourceChecker`) by ~2 seconds (31->29)
=> MultiThreadedJLanguageTool.performCheck: reduce parallelization overhead

languagetool-wikipedia/src/main/java/org/languagetool/dev/dumpcheck/SentenceSourceChecker.java
plus cleanup (make some methods static)
=> SentenceSourceChecker: add an option to print duration

languagetool-language-modules/it/src/main/resources/org/languagetool/rules/it/grammar.xml
This fixes the FP signaled to us [on Twitter](https://twitter.com/ChiaraLoQAce1/status/1322214904057810952) by a user
=> [it] fix FPs for GR_07_001 ('da' vs. 'dà')

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java
Interestingly, I observe a small speedup after this change, sometimes up to 5% for English.
=> simplify PatternToken.isPosTokenMatched

languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java, languagetool-core/src/main/java/org/languagetool/tagging/ManualTagger.java
use more memory-efficient maps, arrays instead of lists, intern duplicate strings
=> decrease memory usage by ManualSynthesizer and ManualTagger

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/StringMatcher.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/XMLRuleHandler.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/PatternTokenTest.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/StringMatcherTest.java
reuse duplicate matchers, intern possible values
=> extract text matching with regexp optimizations out of PatternToken

languagetool-core/src/main/java/org/languagetool/rules/spelling/SpellingCheckRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java, languagetool-language-modules/uk/src/main/java/org/languagetool/rules/uk/MorfologikUkrainianSpellerRule.java
=> SpellingCheckRule: remove unused parameters, cleanup

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RegexPatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/XMLRuleHandler.java
This also saves a bit of memory: ~200KB for English
=> AbstractPatternRule: remove fields specific to RegexPatternRule

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
Ein Fehler in den Tags hatte sich eingeschlichen. Das habe ich korigiert.
=> DAK to AKK

languagetool-core/pom.xml, languagetool-core/src/main/java/org/languagetool/tools/StringTools.java, languagetool-http-client/pom.xml
to avoid incorrect "possible NPE" IDE warnings
=> update JetBrains annotations version to use @Contract

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Another quick FP fix from the Nightly Diff
=> [de] fix FP for KOMMA_ZWISCHEN...[9] (wird werden)

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Quick fix for FP spotted in Nightly Diff
=> [de] fix FP for KOMMA_ZWISCHEN... (hatte Hab und Gut)

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/removed.txt
...damit "Jahrhundertes" nicht mehr vorgeschlagen wird.
=> [de] add "Jahrhundertes" to removed.txt

languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java
This speeds up single-threaded German checking (without suggestion retrieval) by ~50%
=> HunspellRule: calculate suggestions lazily

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/RuleMatch.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/hunspell/HunspellRule.java, languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java, languagetool-server/src/test/java/org/languagetool/server/HTTPServerTest.java
take 2: no unrelated cleanups, don't miss translated suggestions (and add a test), no unnecessary synchronization
=> morfologik/hunspell rules: calculate suggestions lazily

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Thanks, @jaumeortola, for making this rule :)
=> [fr] fine tuning IMPERATIVE_PRONOUN

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/removed.txt
@tiff Will adding "staid" to removed.txt stop it from being suggested by the synthesizer? See [#3948](https://github.com/languagetool-org/languagetool/issues/3948)
=> [en] removed.txt staid as VBD and VBN

languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java, languagetool-core/src/main/java/org/languagetool/tagging/ManualTagger.java
This saves some 1.2 MB for English
=> avoid duplicate lemma strings inside ManualSynthesizer and ManualTagger

languagetool-core/src/main/java/org/languagetool/AnalyzedSentence.java, languagetool-core/src/main/java/org/languagetool/rules/GenericUnpairedBracketsRule.java
This speeds up my `Main -l en 20KSentenceFile` by 5-10%
=> cache token and sentence concatenation results

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java
This saves some humble 200KB memory for English, and several LOC
=> reduce PatternToken size: extract most exception-related fields into a sub-object

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
I'll let the tests run and then try and merge it myself :)
=> [de] eliminate FPs for ALS_ERSTES

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
to fix FP on LT website, word is in common use (even though purists would rather have "expert·e en mégadonnées")
=> [fr] add "data scientists?" to multiwords

languagetool-core/src/main/java/org/languagetool/AnalyzedSentence.java
=> fix typo in AnalyzedSentence.getText leading to a race condition

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Fixing new FP in Diff after fixing `néo-zélandaise?` rule
=> [fr] add 'fille au pair' to FR multiwords

languagetool-core/src/main/java/org/languagetool/rules/Rule.java, languagetool-core/src/main/java/org/languagetool/rules/ngrams/ConfusionProbabilityRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractTokenBasedRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule2.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CompoundInfinitivRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanWordRepeatRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/MissingCommaRelativeClauseRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/SubjectVerbAgreementRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/VerbAgreementRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/CompoundRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/UpperCaseNgramRule.java, languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/QuestionWhitespaceRule.java, languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/QuestionWhitespaceStrictRule.java
This gives 5-7% speedup on `Main -l de` for me.
There are 2 commits here, and they might be easier to review separately.
=> DisambiguationPatternRule: check for available form/lemma hints before full matching

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRule.java, languagetool-core/src/main/java/org/languagetool/tools/Tools.java, languagetool-standalone/src/test/java/org/languagetool/JLanguageToolTest.java
enableRule/disableRule didn't respect full rule IDs
=> Fix: enable/disableRule with full rule IDs (i.e. from rule groups)

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
Some improvements and test cases. Fixes #3969.
=> [en] improve ADVERB_WORD_ORDER[9] and [10]

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] plus mauvais

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] alternative ou possibilité

languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/RequestLimiter.java, languagetool-server/src/main/java/org/languagetool/server/Server.java
add emails to whitelist, has separate request limit value
e.g. for enterprise customers with high request volume
new options:
requestLimitWhitelistUsers, requestLimitWhitelistLimit
=> special limits for whitelisted users

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
https://forum.languagetool.org/t/plural-mammut/6522
=> Add Mammut

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://forum.languagetool.org/t/plural-mammut/6522/3
=> Add Mammute/N Wörterbuch

languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternToken.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/StringMatcher.java, languagetool-core/src/test/java/org/languagetool/rules/patterns/StringMatcherTest.java
This gives me about 5% speedup on `Main -l de`
=> use StringMatcher for POS patterns as well

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Plusieurs expressions figées avec le terme "tout".
=> [fr] expressions figées tout

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] pluriel de al

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
=> Wörter hinzugefügt

languagetool-core/src/main/java/org/languagetool/languagemodel/bert/RemoteLanguageModel.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleTimeoutTest.java
pass timeout, add missing cancel(), deadline in GRPCRule, test
=> fix zombie threads from remote rule timeouts

languagetool-core/pom.xml, languagetool-server/pom.xml, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java
add new metric like `languagetool_build_info{buildDate="null",premium="false",revision="34ecf07",version="5.3-SNAPSHOT",}`
=> update prometheus, expose build information

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
=> Add wrong Word

languagetool-core/src/main/java/org/languagetool/languagemodel/bert/RemoteLanguageModel.java, languagetool-core/src/main/java/org/languagetool/rules/BERTSuggestionRanking.java, languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleTimeoutTest.java
timeout = 0 interpreted as unlimited in remote rule, now passed through
needs to be handled equally there
=> fix handling of timeout=0 in RemoteRule subclasses

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] place de la virgule rule

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Kartenrune/N statt Kartenrunde/N
=> Add Kartenrune/N statt Kartenrunde/N

languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
Also, there's one:
- CricleCI
but I think it should be:
- CircleCI
ri->ir
=> Remove duplicates

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
La virgule  en début de phrase.
=> [fr] virgule debut de phrase rule improved

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] il y a rule improved

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Confusion entre les prépositions à et en.
=> [fr] a ou en moyen de transport rule

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
subrules "de suite" and "faute d'attention" improved.
=> [fr] confusion dans une expression rule improved

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Subrule "solutionner" improved.
=> [fr] confusion orthographique rule improved

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Oberschenke/N statt Oberschenkel
Unterschenke/N statt Unterschenkel
=> add Ober/unterschenke statt Ober/unterschenkel

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Le signe &amp est ajouté et les AP sont améliorés.
=> [fr] pas de virgule rule improved

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Inversion de l'ordre des mots dans la question.
=> [fr] question registre soutenu rule

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Confusion entre 'd'en' et 'dans'.
=> dans ou d'en rule

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Erreurs d'accord dans certaines expressions relatives à la quantité.
=> [fr] accord de la quantité rule

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Erreur d'accord problématique.
=> [fr] accord superlatif possible

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] sur accent rule improved

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Hauptaktaktion statt Hauptattraktion
Hauptaktaktionen statt Hauptattraktionen
=> Add Hauptaktaktion statt Hauptattraktion

languagetool-office-extension/src/main/resources/Addons.xcu, languagetool-office-extension/src/main/resources/description.xml
Added three sentences translated into Galician.
=> Added Galician translations

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
Modifications on previous commit, with Udo's and Jaume's comments taken into account
=> [fr] add rule for sentence start with BIEN_SÛR on SUR_ACCENT v.2

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
* Created a new entity to deal with non-reflexive verbs.
* Added URL to rules about non-reflexive verbs.
* Added several contractions.
* I include the legal declaration I missed on my first commit.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or
(c) The …
=> [gl] Non-reflexive verbs ; legal declaration

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
I pushed the original branch... I guess it's opening a new pull request because the first one is closed?
Added some antipatterns to get rid of the last FPs :)
=> [en-US] "the United States" verb agreement

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
=> [en] improved US_ONE_ENTITY

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
=> [en] US verb agreement final

languagetool-language-modules/en/src/main/java/org/languagetool/language/AmericanEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/BritishEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/NewZealandEnglish.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AmericanReplaceRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/BritishReplaceRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/NewZealandReplaceRule.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/AmericanReplaceRuleTest.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/BritishReplaceRuleTest.java
The changes were based on f29ebd4425f9f5b73da70ddbe2a59ae04c78bc93. Also, added a few more test cases.
=> Make EnglishDialectsReplaceRules detect expressions too (#4846)

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
**Removed default="temp_off":**
MAYBE_COMMA (now FINAL_ADVERB_COMMA)
DT_NNS_AGREEMENT
TAG_QUESTIONS_2
WILL_ALLOW
ETC_PERIOD
**default="off"**
USED_FOR_VBG
=> [en] activate rules

languagetool-server/src/main/java/org/languagetool/server/ApiV2.java, languagetool-server/src/main/java/org/languagetool/server/BadRequestException.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseAccess.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/ServerTools.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/java/org/languagetool/server/V2TextChecker.java, languagetool-server/src/test/java/org/languagetool/server/TextCheckerTest.java
Use new exception BadRequestException so bugs related to IllegalArgumentExceptions appear as 500 errors
=> Replace use of IllegalArgumentException for 400 errors

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Reviewed messages trying to adapt https://forum.languagetool.org/t/en-guidelines-rules-for-messages/5350 - There were too many 'Did you mean' phrases.
Reworked rule about apostrophe
=> [gl] Nicer messages

languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleConfig.java, languagetool-core/src/test/java/org/languagetool/RemoteRuleCacheTest.java, languagetool-core/src/test/java/org/languagetool/rules/GRPCRuleTest.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleTimeoutTest.java, languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java
Added options timeoutLimitTotalMilliseconds, timeoutLimitIntervalMilliseconds
Abort running remote rule checks when rule is marked as down
=> better timeout handling for RemoteRule

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Rearranged categories. Merged two previous ones for foreign words and created one for archaisms
Created index of categories, inspired by Italian grammar.xml
Added one rule for Portuguese loanwords and one for archaisms
=> [gl] Rearranged categories

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Following the example of Dutch, all rules are now within a rule group
=> [gl] Every rule is within a rule group

languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/java/org/languagetool/server/V2TextChecker.java
catch IllegalArgumentException, throw BadRequestException
=> fix: unknown language code leads to 500 error, should be 400

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx
=> [pt] improve segmentation for arts.

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Rule about cacophony works now; name changed; moved to category Agreement
=> [gl] Rule about cacophony

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
prefer suggestions from more specific rules because of better messages
=> default priority for HydraLEO: -1

languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleFilters.java
Show removed and remaining matches, allow testing without a running server
=> added testing RemoteRuleFilters w/ stored matches

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
this is a first shot
I'm sure that the 3 rules are factorisable so I'll rework the rulegroup to optimize the code
=> [fr] VIRGULE_DEBUT_DE_PHRASE_3

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Rule 'CLITICS / Start of sentence' is complete (antipatterns, url, short)
=>  [gl] clitics - rule completed

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Added three entities to deal with clitics (simple, complex, full list).
Added two rules for clitics in questions and exclamations.
=> [gl] added entities, rules for clitics

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
=> [en] add picky tag

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
=> Projekttor statt Projektor

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
add picky to TELL_IT, PREVENT_FROM
remove picky from ETC_PERIOD
=> [en] picky tags

languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
should improve latency, load balancing
=> split large requests in GRPCRule

languagetool-language-modules/gl/src/main/resources/org/languagetool/rules/gl/grammar.xml
Rule names were reviewed so that they're easier to understand and to group in GUI.
No changes to the rules themselves.
=> [gl] Human legibility of rule names

languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRuleExceptions.java, languagetool-language-modules/de/src/main/java/org/languagetool/tokenizers/de/GermanCompoundTokenizer.java
=> [de] reduce memory usage by using THashSet

languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpeller.java, languagetool-core/src/main/java/org/languagetool/synthesis/BaseSynthesizer.java, languagetool-core/src/main/java/org/languagetool/tagging/BaseTagger.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CompoundInfinitivRule.java
=> deduplicate morfologik dictionaries to decrease memory usage

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
=> Armee statt Arme

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRuleExceptions.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/CaseRuleTest.java
=> [de] save some memory by replacing Patterns with mostly more efficient StringMatchers

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AdaptSuggestionFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AdvancedSynthesizerFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/synthesis/GermanSynthesizer.java, languagetool-language-modules/de/src/main/java/org/languagetool/tagging/de/GermanTagger.java, languagetool-language-modules/de/src/main/java/org/languagetool/tokenizers/de/GermanCompoundTokenizer.java, languagetool-language-modules/de/src/test/java/org/languagetool/synthesis/GermanSynthesizerTest.java
This saves 7 more MB for GermanyGerman
=> deduplicate GermanSynthesizer, GermanTagger and GermanCompoundTokenizer objects

languagetool-language-modules/ga/src/main/resources/org/languagetool/rules/ga/grammar.xml
Create a rule to correct for the phrase "i ndeireadh na dála".
=> [ga] i ndeireadh na dálai (closes #5185)

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/FindSuggestionsFilter.java, languagetool-language-modules/en/src/main/java/org/languagetool/tagging/en/EnglishTagger.java, languagetool-language-modules/en/src/main/java/org/languagetool/tokenizers/en/EnglishWordTokenizer.java, languagetool-language-modules/en/src/test/java/org/languagetool/tagging/en/EnglishTaggerTest.java
=> save memory by reusing EnglishTagger instance

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/SpellingData.java
2-2.5 seconds less on my machine
=> [de] speedup SpellingData initialization by not synthesizing forms that aren't needed

languagetool-core/src/main/java/org/languagetool/synthesis/BaseSynthesizer.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/LineExpander.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/SpellingData.java, languagetool-language-modules/de/src/main/java/org/languagetool/tagging/de/GermanTagger.java
=> [de] speedup initialization: don't compile/match POS tag regexps inside synthesizer each time

languagetool-core/src/main/java/org/languagetool/rules/AbstractSpecificCaseRule.java
The loading of the phrases is performed in every initialization, so this commit increases its speed.
=> Speed up the SpecificCaseRule (#5227)

languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-core/src/test/java/org/languagetool/rules/RemoteRuleOffsetsFixTest.java
adjust offsets for unicode characters with multiple code points
fixes wrong offsets with emojis, etc. in sentence
=> added option fixOffsets for RemoteRule

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/removed.txt
New branch due to many conflicts on previous RM13
=> [fr] modify incorrect Lemma for franche/franches

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
I re-wrote this entire rule because of a low apply rate, but not sure if I can
I set this PR into "draft mode" for the moment, until we clarify
=> [fr]CEST_CETTE

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
updated priorities, new name in configuration
=> German hydraleo

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java, languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
New branch due to several conflicts on the old one (RM12)
=> Rm25 verbes familiers

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanRemoteRuleFilterTest.java
=> Fix DE HL_MISSING_COMMA APs

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-US/grammar.xml
=> [en] rules to picky/temp off

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
"Weil man oft bei **anderen schreckliches Essen** vorgesetzt bekommt" etc.
=> [de] new AP for DE_AGREEMENT

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
AI Antipattern for not suggesting lower casing the first word of a sentence.
=> Add AP for CASE_LOWER

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
I'm just waiting for Premium test results before merging
=> [de] more DE_AGREEMENT refinements

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
Adds an AI AP for HydraLEO CASE_UPPER for cases such as mRNA, iPhone etc.
=> Add AP for HydraLEO CASE_UPPER (mRNA, iPhone etc.)

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar-l2-de.xml
@udomai 
Do the messages check out ([1] and [2])?
If so, please merge.
=> [en] improve message and activate WH_VERB_SUBJECT

languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
=> [fr] Night Diff improvement (2021Sep22)

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
— CURRENTLY BEING TESTED, DO NOT MERGE —
=> [de] disamb APs for "Sein Wissen"

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
@udomai 
Still fails and idk why :/
=> [en] add to dictionary for Premium issues 3121, 3192

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
Merge if test results are satisfactory
=> [en] APs for E_NP_NN_VBP

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
@udomai 
It works! Please merge :)
=> [en] add to dictionary for Premium issue 3217

languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/resources/logback.xml
log requests on start / end
introduce MDC, only set and log request ID for now
=> improved logging

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
[core] add logging to see how error rate is growing in case of an error
=> [core] add error rate calc after each rule check based on hole text size

languagetool-server/pom.xml, languagetool-standalone/pom.xml, pom.xml
[parent] add dependency checker plugin
[standalone| add test scope to core
=> [server]Update dependency Versions fixes: #5978

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
- fixes small problems I found while doing QC
- rules: DOPPELUNG_MODALVERB, CAFE_KAFFEE, IM_STILLEN
=> [de] improve rules

languagetool-core/src/main/java/org/languagetool/rules/LanguageDependentFilter.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RuleSet.java
=> speed up LanguageDependentFilter creation

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Adding some APs for AI_HYDRA_LEO_CPT_IS_ARE for Premium [#3430](https://github.com/languagetooler-gmbh/languagetool-premium/issues/3430) @udomai
=> [en] add APs for AI_HYDRA_LEO_CPT_IS_ARE

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] improve DIES_DIE

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractTokenBasedRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRule.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleMatcher.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRule.java, languagetool-core/src/main/java/org/languagetool/tagging/disambiguation/rules/DisambiguationPatternRuleReplacer.java
~4% speedup on IntelliJ scenarios, ~2% on the usual English analysis
=> DisambiguationPatternRuleReplacer: don't instantiate relatively expensive PatternRules

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Improved the APs for AI_HYDRA_LEO_CPT_IS_ARE @udomai
=> [en] improve APs for AI_HYDRA_LEO_CPT_IS_ARE

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
More APs for AI_HYDRA_LEO_CPT_IS_ARE Premium [#3430](https://github.com/languagetooler-gmbh/languagetool-premium/issues/3430) @udomai
=> [en] more APs for AI_HYDRA_LEO_CPT_IS_ARE

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Add APs for AI_HYDRA_LEO_CPT_NOW_KNOW for Premium [3332](https://github.com/languagetooler-gmbh/languagetool-premium/issues/3332) @udomai
=> [en] add APs for AI_HYDRA_LEO_CPT_WERE_WEARE

languagetool-core/src/main/java/org/languagetool/tools/LtThreadPoolExecutor.java, languagetool-core/src/main/java/org/languagetool/tools/LtThreadPoolFactory.java, languagetool-server/src/main/java/org/languagetool/server/HTTPSServer.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServer.java, languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java, languagetool-server/src/main/java/org/languagetool/server/Server.java, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
use subclass of ThreadPoolExecutor in LtThreadPoolFactory
tracks active threads and queue size, exposes metrics
use LtThreadPoolFactory for server thread pool
=> added metrics for thread pool usage

languagetool-server/pom.xml, languagetool-server/src/main/java/org/languagetool/server/ApiV2.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseAccess.java, languagetool-server/src/main/java/org/languagetool/server/DatabaseAccessOpenSource.java, languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java, languagetool-server/src/main/java/org/languagetool/server/LoggingInterceptor.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/resources/logback.xml, languagetool-server/src/main/resources/org/languagetool/server/mybatis-config.xml
Removed unused/duplicate methods and dependency
=> clean up dictionary methods

pom.xml
to fix version issue in deployed pom files (local and repo)
=> add flatten plugin

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
url suggestions provided by Marvin
=> [de] add / replace urls

.circleci/config.yml, languagetool-core/src/test/java/org/languagetool/FailTest.java
=> [circleci]

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/RemoteRule.java
tryAcquirePermissions requires manual tracking of success/failure
=> fix for circuitbreaker transitions

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleTransformer.java, languagetool-core/src/main/java/org/languagetool/rules/patterns/RepeatedPatternRuleTransformer.java, languagetool-language-modules/ca/src/test/java/org/languagetool/rules/ca/CatalanTest.java, languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/EnglishTest.java
allow grouping multiple rules in one rule,
including or excluding rules for further transforms, etc.
group in RepeatedPatternRuleTransformer so repetitions from one rulegroup match
TODO:
=> refactor PatternRuleTransformer interface

languagetool-server/src/main/java/org/languagetool/server/PipelinePool.java, languagetool-server/src/main/java/org/languagetool/server/TextChecker.java, languagetool-server/src/main/resources/logback.xml
reduce logging output by partially reverting logback.xml and updating some log levels
=> clean up log levels and configuration

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml, languagetool-language-modules/es/src/main/java/org/languagetool/language/Spanish.java, languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
=> change rule IDs for HydraLEO

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
Same changes that were made to Premium.
@udomai @jaumeortola
=> [en] adjust priority (OS)

languagetool-core/src/main/java/org/languagetool/rules/LongSentenceRule.java, languagetool-core/src/test/java/org/languagetool/rules/LongSentenceRuleTest.java
Fixes languagetooler-gmbh/languagetool-premium#3909
=> Improve LongSentenceRule

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Dies ist mein erster Code-Beitrag zu LanguageTool. Ich bin gespannt, ob er so annehmbar ist. :)
Fixes #1483.
=>  [de] avoid more false alarms with DATUM_ZUKUNFT_VERB_VERGANGENHEIT (#1483) 

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Fixes #6381.
Ich hoffe, das ist so in Ordnung. :)
=> [de] fix "(des) Grüns" (#6381)

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-CH/grammar.xml
@affemitkaraffe, hast du diese Regel schon im nightly diff getestet?
=> [de] CH quotes rule to CH grammar

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] improve EGAL_STIL

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Das suggestion-Problem sollte behoben sein. 
Für das Problem mit den Internetadressen habe ich noch keine gute Lösung.
=> [de] SPACE_AFTER_BEFORE_SLASH (new)

languagetool-core/src/main/java/org/languagetool/Premium.java, languagetool-server/src/main/java/org/languagetool/server/ApiV2.java, languagetool-server/src/main/java/org/languagetool/server/ServerMetricsCollector.java
=> [core] update git info

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai Ich denke, hier kann temp_off raus.
=> [de] IM_ENDDEFEKT 'temp_off' aus

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai hier kann temp_off auch raus
=> [de] HAUPTPROTAGONIST 'temp_off' aus

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai auch hier kann temp_off raus
=> [de] SICH_GEGENSEITIG 'temp_off' aus

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] improve FALSCHER_IMPERATIV

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai habe noch ein AP ergänzt.
=> [de] improve ZUM_STATT_FUERS

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai Ich habe noch ein paar APs hinzugefügt für Situationen, bei denen ich denke, da wäre 'komplett' ok.
Bei allen anderen Situation muss ich allerdings sagen, finde ich 'komplett' zwar ok, aber stilistisch nicht elegant gelöst.
Ich habe die message noch mal angepasst und 'umgangssprachlich' rausgenommen, weil es in vielen Kontexten nicht direkt umgangssprachlich ist, aber es anders besser klingt.
=> [de] improve KOMPLETT_STIL

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Tag.java, languagetool-server/src/main/java/org/languagetool/server/ServerTools.java
@danielnaber, im lokalen Test sieht es so aus, als wäre jede Regel mit dem Tag jetzt einfach aktiv. Sieht das erstmal okay aus?
=> [core] introduce new tag

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://de.wikipedia.org/wiki/Syndikus
=> [de] add words to spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] improve AN_FUER_SICH[2]

languagetool-language-modules/zh/src/main/java/org/languagetool/tagging/zh/ChineseTagger.java
This is a correction for #issue6281, which is resolved by adding a check for"/".
=> Update ChineseTagger.java, correct for #issue6281

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/LineExpander.java
several lines can contain the same verb with different prefixes, so reuse the expensive synthesizer results
this shaves off 300-400ms of German loading (7-10%)
=> [de] LineExpander: cache verb forms, not line results

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
Ich habe noch die subrules durchnummeriert und das Leerzeichen nach `<message>` entfernt. @udomai: könntest du das nochmal mergen? Vielen Dank :).
=> [de] improve EINE_ORIGINAL_RECHNUNG_TEST

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
@udomai: ich habe die Regel basierend auf den Fehlalarmen überarbeitet, indem ich drei weitere antipatterns ergänzt habe. Wenn ich jetzt den Main-Test mit den Sätzen mache, die die Fehlalarme ausgelöst haben, passt es. Könntest du das noch in der Sandbox testen? Vielen Dank!
=> [de] add disamb INDEFINITPRONOMEN_ALS_SUBJEKT

languagetool-language-modules/ja/src/main/resources/org/languagetool/rules/ja/grammar.xml
A suggested fix for #6592 
- changed the rule name replacing "_" with "+" to make the rule name consistent with others
- added a marker tag to clarify which part has a problem
- added inflected and regex attribute for the last token to catch various expressions
- changed the message to remove an irrelevant correction and make it a general recommendation
- changed the example to remove the suggestion, because there is no general suggestion for this rule
=> [ja] Update DOUSI_KOTOGADEKIRU rule

languagetool-core/src/main/java/org/languagetool/JLanguageTool.java, languagetool-core/src/main/java/org/languagetool/Tag.java, languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd, languagetool-server/src/main/java/org/languagetool/server/ServerTools.java
@jaumeortola, I've added the new tags in `rules.xsd`, too. Look good?
=> [core] add more (sub)tags

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRuleAntiPatterns1.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java
@udomai: Antipattern für Fälle wie "Inwiefern soll denn das romantische Hoffnungen begründen?"
=> [de] add AP for DE_AGREEMENT

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: Ich habe ein paar Regeln zu mir vs. mit geschrieben. Leider musste ich sie z.T. recht speziell halten, da es ansonsten einfach viel zu viele Fehlalarme geben würde. Schau gerne mal, ob das in die Richtung geht, die du die vorgestellt hattest.
=> [de] add CONFUSION_RULE_MIR_MIT_NEU

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: jetzt sollte es hoffentlich weniger FPs geben. Wenn ich die message anpassen soll (wenn ich das richtig gesehen habe, hat @St-ac-y gerade auch einen pull request dazu laufen - zumindest zu ein paar der messages), gib gerne Bescheid.
=> [de] improve CONFUSION_RULE_MIR_MIT_NEU

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRule2.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/WiederVsWiderRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] spelling check

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] improve KRASS_STIL + 'temp_off' aus

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: Ergänzung einer neuen Regel, die für Fälle wie "Dazu fehlt mir dir Kraft." "mir die" vorschlägt.
=> [de] add VERWECHSLUNG_MIR_DIR_MIR_DIE

languagetool-core/src/main/java/org/languagetool/rules/patterns/AbstractPatternRulePerformer.java
Previously the unifier was run for any token reading once any previous one of them was matched. Now we do that only for the matched ones. Besides, we now call the expensive `getFinalUnified` once per the last unified token, not for each of its readings.
This saves ~10% in GermanPatternRuleTest for me.
=> don't unify non-matched token readings

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: Ich habe wie besprochen noch zwei weitere AP ergänzt, damit die Regel hoffentlich besser angenommen wird.
=> [de] add more APs CONFUSION_RULE_MIR_MIT_NEU

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] add AUSLASSUNGSPUNKTE

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: nach einem Blick auf Grafana heute habe ich noch ein weiteres AP für Subrule 14 ergänzt.
=> [de] add AP CONFUSION_RULE_MIR_MIT_NEU

languagetool-core/src/main/java/org/languagetool/rules/UppercaseSentenceStartRule.java, languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/EnglishSpecificCaseRule.java
=> [en] update URLs

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] mvn test warning reduction

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
=> [de] GERMAN_SPELLER fix

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] 'temp_off' aus ARGUMENT_ANBRINGEN

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
@udomai: wenn das Diff dazu morgen passt, würde ich die Regel aktivieren.
=> [de] improve VERWECHSLUNG_MIR_DIR_MIR_DIE

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
=> [de] add spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
=> [de] add PRAEP_GEN

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
https://github.com/languagetool-org/languagetool/issues/6729
=> [es] improve NUMBER_DAYS_MONTH

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
currently being tested (do any actually helpful suggestions disappear?)
=> [de] avoid... unlikely suggestions

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CompoundCheckFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanRepeatedWordsRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/InsertCommaFilter.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/SubjectVerbAgreementRule.java, languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/UppercaseNounReadingFilter.java
For me, the speedup is 4.2->3.5 seconds
=> speedup new JLanguageTool(new GermanyGerman()): lazier tagger/synthesizer/word list loading

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
https://github.com/languagetool-org/languagetool/issues/6729
=> [es] add APs NUMBER_DAYS_MONTH

languagetool-http-client/src/main/java/org/languagetool/remote/CheckConfiguration.java, languagetool-http-client/src/main/java/org/languagetool/remote/CheckConfigurationBuilder.java, languagetool-http-client/src/main/java/org/languagetool/remote/RemoteLanguageTool.java, languagetool-http-client/src/test/java/org/languagetool/remote/CheckConfigurationTest.java
This would make it possible to access premium API using RemoteLanguageTool
=> Add username and apiKey parameters to RemoteLanguageTool

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Just a small change to get started.
Please take a look.
=> [nl][INSPECIFIEK] Disable sub-rule with many false positives

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
New rule detecting misspelling of the word "mas".
=> [pt] CONFUSION OF MAS AND MAIS

languagetool-server/src/main/java/org/languagetool/server/DatabaseAccessOpenSource.java, languagetool-server/src/main/resources/org/languagetool/server/mybatis-config.xml
Set database timeout directly in mybatis configuration.
=> [server] configure mybatis defaultStatementTimeout

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Made some antipatterns to avoid annoying/unwanted corrections in the double punctuation rule. Let's see if this works @danielnaber
=> [pt] created antipattern in rule DOUBLE PUNCTUATION to avoid FAs

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
Addition of antipatterns and improvement of message and suggestion based on Matomo disables.
=> [es] improve MALO_AMIGO_MAL_AMIGO

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
See: https://github.com/languagetool-org/languagetool/commit/de8cc355d6128be85329ded57405236e61d01ede
=> [es] fix examples NUMBER_DAYS_MONTH

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRuleAntiPatterns1.java, languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/AgreementRuleTest.java, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt, languagetool-language-modules/nl/src/main/java/org/languagetool/language/Dutch.java, languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml, languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wordiness.txt
@danielnaber: ich habe versucht, für die meisten Fälle mit "zu" Aps zu ergänzen. 
Was mir noch aufgefallen ist: Bei ART + zu + substantiviertes Partizip (z. B. "der zu Pflegende") schlägt die Regel allerdings noch ART Partizip-Partizip vor (also z. B. "der Pflegende-Pflegende").
=> [de] add AP DE_AGREEMENT

languagetool-language-modules/de/src/main/java/org/languagetool/tagging/de/GermanTagger.java, languagetool-language-modules/de/src/test/java/org/languagetool/tagging/de/GermanTaggerTest.java
- allow for cases where the last part does not determine the postag
=> [de] improve PA2.+ tagging

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://www.google.com/search?q=%22Mittelstandskunden%22
=> [de] Add "Mittelstandskunde(n)" to spelling.txt

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
Adding Broca to dictionary, as in Broca's area https://github.com/languagetooler-gmbh/languagetool-premium/issues/4557
=> [en] update spelling

languagetool-core/src/main/resources/org/languagetool/resource/segment.srx
@tiff  can you please check my PR?
=> [DE] trying out expanding abbreviations

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://de.wikipedia.org/wiki/Unverz%C3%BCglichkeit 
https://de.wikipedia.org/wiki/Verweisungsnorm
=> [de] Add some law terms to spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
=> [de] Add "Signatur" to spelling.txt

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
=> [fr] Hot fix for added.txt file (countries entries)

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/removed.txt
Cuba had wrong PoS tags:  Cuba [Cuba/Z e ps] -> Cuba[Cuba/Z m s]
=> [fr] Change in removed.txt file (country entry)

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/multiwords.txt
It's a Latin term:
- [M-W](https://www.merriam-webster.com/dictionary/ignis%20fatuus)
- [Lexico](https://web.archive.org/web/20220825212314/https://www.lexico.com/definition/ignis_fatuus)
- [Collins](https://www.collinsdictionary.com/us/dictionary/english/ignis-fatuus)
- [Dictionary.com](https://www.dictionary.com/browse/ignis-fatuus)
- [American Heritage](https://www.ahdictionary.com/word/search.html?q=ignis+fatuus)
=> [en] Add "ignis fatuus" + "ignes fatui"

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
Adding new words that are accepted into French dictionaries in 2023.
=> [fr] Dictionnary additions

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Diese Regel habe ich aufgrund Marvins Nachricht im #lingu-ruledev-de Channel erstellt und auch ins spelling.txt hinzugefügt, aber warte ich muss sie noch temp_off stellen...
=> [de] created new rule group + added to spelling

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Hi Agnes, könntest du das für mich checken und ggf. mergen, bitte? Danke :-)
=> [de] added noun

languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
@St-ac-y please merge :-) Thanks!
=> [de] add name to spelling_global.txt

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
Adding _homophonographe_ to dictionary files, per request https://github.com/languagetooler-gmbh/languagetool-premium/issues/4826.
=> [fr] Dictionary additions

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
took my best shot at this, good chance I did this wrong
closes #7519
=> [en] add the word unbirthday

languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/prohibit.txt, languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
[#4841](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4841)
[#4842](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4842)
=> [en] update dictionary

languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
=> [fr] PLACE_DE_LA_VIRGULE>C_EST_QUOI, OU_PAS>VERBE_OBJ

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt, languagetool-language-modules/de/src/test/java/org/languagetool/tagging/de/GermanTaggerTest.java
NEW: New branch and new PR (includes all changes in spelling and GermanTaggerTest)
[This branch and PR](https://github.com/languagetool-org/languagetool/pull/7563) are obsolete...
=> [de] all P changes + GermanTaggerTest changes

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/prohibit.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/removed.txt
To fix:
- https://github.com/languagetooler-gmbh/languagetool-premium/issues/4749
- https://github.com/languagetooler-gmbh/languagetool-premium/issues/4872
=> Dictionary addition, file prohibit.txt creation

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Adding herbes aromatiques as N f p to fix FP in https://github.com/languagetooler-gmbh/languagetool-premium/issues/4716
=> [fr] Dictionary addition

languagetool-server/pom.xml, languagetool-server/src/main/java/org/languagetool/server/GRPCServer.java
- [languagetool-server] enable analyze() in GRPCServer
- feat[languagetool-server]: TLS support for GRPCServer
=> Enable analyze() and add TLS to GRPCServer

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
Vorletzter Punkt: https://github.com/languagetooler-gmbh/languagetool-premium/issues/4851
=> [de] changed/added P for PA2 (-en)

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/alt_neu.csv
=> Wurde wurde

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
[#4906](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4906)
[#4907](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4907)
[#4908](https://github.com/languagetooler-gmbh/languagetool-premium/issues/4908)
=> [en] 01/03/2023

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
=> [pt] DOUBLE_PUNCTUATION_XML

languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
antipatterns refined
temp_offs removed from good working subrules
#7642
=> [pt] DOUBLE_PUNCTUATION_XML - ELLIPSIS

languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
=> [de] return=-2

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/prohibit.txt
First fix for https://github.com/languagetooler-gmbh/languagetool-premium/issues/4926
=> [fr] Dictionary addition prohibit

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
Adding antipattern to fix https://github.com/languagetooler-gmbh/languagetool-premium/issues/4917
=> [fr] MOTS_INCOMP

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
=> [de] Add disambiguation rule

languagetool-language-modules/en/src/main/java/org/languagetool/language/English.java
=> Rename Rule ID for LECTOR

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola @maphjo Please check the new added rule
=> [es] added rule ex alto cargo

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola @maphjo the rule has been improved by adding the plurals
=> [es] improved rule ex alto cargo

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
-Improved rule to address this issue from [Feedback Board](https://github.com/orgs/languagetooler-gmbh/projects/46/views/1): https://github.com/languagetooler-gmbh/languagetool-premium/issues/5062
-Added words to spelling / ignore to improve speller: https://regression.languagetoolplus.com/via-http/2023-02-15/de-DE/result_java_GERMAN_SPELLER_RULE.html
=> Speller+improve rule

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/MissingCommaRelativeClauseRule.java
To address this issue: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5061
=> [de] added explanation to the message

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://www.dwds.de/wb/wirtschaftsrechtlich
=> [de] Add "wirtschaftsrechtlich" to spelling.txt

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetool-org/languagetool/pull/7838
=> [de] from spelling to ignore and removed shipped (was added to the PR rule)

languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/MissingCommaRelativeClauseRule.java, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://regression.languagetoolplus.com/via-http/2023-02-16/de-DE/result_java_COMMA_IN_FRONT_RELATIVE_CLAUSE.html
=> Improvements

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling-de-CH.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5078
+
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5080
+
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5082
=> Appartement

languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt, languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://regression.languagetoolplus.com/via-http/2023-02-21/de-DE/result_grammar_IM_INNEREN[1].html
=> [de] added AP

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
[#115](https://github.com/languagetooler-gmbh/LECToR/issues/115)
=> [en] AI antipatterns - 02/24/2023

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
[#115](https://github.com/languagetooler-gmbh/LECToR/issues/115)
=> [en] AI antipatterns

languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt, languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/removed.txt
- To fix https://github.com/languagetooler-gmbh/languagetool-premium/issues/5160
- See also https://forum.languagetool.org/t/sigles-et-acronymes-quelques-remarques/8764
=> [fr] acronyms OVNI/SIDA removal

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Split up rulegroup to see what can be improved
=> [nl] split up rule "OVERDRIJVING" for detailed analysis

languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola a new rule group has been added - COMMA_SINO2
**Fundéu 03/03/2023**
=> [es] added new rulegroup COMMA_SINO2

languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
[#115](https://github.com/languagetooler-gmbh/LECToR/issues/115)
=> [en] AI antipatterns - 03/08/2023

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Unpopular rule, disabled for now.
=> [nl] disabled rule KORT_2

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Nowadays one of the most common loanwords
=> [nl] disabled rule CHECKEN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Just like "checken", nowadays too common to suggest alternatives.
=> [nl] disabled rule DESIGN

languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
One of the lowest performing rules, disabled for now.
=> [nl] disabled rule KORT_1
