- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Improved rule, got rid of some FPs
> [nl] improved rule HEBT_ZONDER_U_JE

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Unpopular rule, meaning is too unique to suggest alternative
> [nl] disabled rule CREËREN

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, nowadays this is a very common loanword
> [nl] disabled rule FEEDBACK

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, nowadays this is a very common loanword
> [nl] disabled rule MEETING

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, nowadays this is a very common loanword
> [nl] disabled rule MATCH

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
> [nl] improved rule REALISEREN

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled, too common in professional context to suggest alternatives
> [nl] disabled rule BETREFFENDE

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled the least popular rule of the rulegroup
> [nl] improved rule VAAG

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
> [nl] enabled rule JOU_JOUW_VNW

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola new APs have been added to improve the rules DE_LA and DE_LAS
> [es] added new APs to DE_LA / DE_LAS

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Added suggestions, modified antipattern
> [nl] improved rule DER

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Disabled OVERDRIJVING 4, modified message for 2 and 3
> [nl] improved rules OVERDRIJVING 2, 3 and 4

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
quick AI antipattern and regular URL updates
> [en] 03/13/2023

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola temp_off has been removed from the rule COMMA_SINO2
> [es] removed temp_off

- languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
Overte: open-source social VR software
KDevelop: open-source IDE software
Geany: open-source IDE software (what I used to write this PR)
> [core] add global spelling

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRuleAntiPatterns.java
> [de] AP für DE_CASE

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola new APs have been added to improve the rule U_NO
> [es] added new APs to U_NO

- languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/grammar.xml
Meanings were mixed up, fixed rules
> [nl] improved mixed up rules NIET_X_MINST

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola to improve the performance of the rule CONCORDANCIA_GRAN, an AP, as well as a new rule, have been added.
> [es] added rule DANES and AP to CONCORDANCIA_GRAN

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5170
> [de] modified rule + added tag

- languagetool-standalone/CHANGES.md
> Added Portuguese changes

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/remote-rule-filters.xml
Came across an FP in the wild, so decided to write a quick AP for it.
> [en] added AP for AI_EN_LECTOR_REPLACEMENT_VERB_FORM

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/en-GB/grammar.xml
> [en] fix message and update URL

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5257
> [de] added words

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola new APs have been added/modified to improve the rulegroup OLA_HOLA
> [es] added APs to OLA_HOLA

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
> [de] AP for AI_DE_HYDRA_LEO_CASE_LOWER

- languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
- languagetool-core/src/main/java/org/languagetool/Language.java
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Add style for Portuguese (main and variants), and optionally for any other language.
> [core] new style.xml files

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola in order to solve [this issue,](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5440) a couple of APs have been added to the rule AUN2.
> [es] added APs to AUN2

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola an AP has been added to solve this [issue](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5450)
> [es] added AP to NUMERO_DE_SG_PL

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/case_rule_exceptions.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5257
> Corrections

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/grammar.xml
@jaumeortola to solve this [issue](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5468), a couple of APs have been added to the rule ESTAS_TILDE2
> [es] added APs to ESTAS_TILDE2

- languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling-de-AT.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling-de-CH.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5457
> [de] added word to spelling CH+AT (rule for DE in Premium)

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Rule linking: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5043
- REP_DIRE[1]
- REP_AIDER[1]
- BAILLER_BAYER [1-11]
> [fr] Rule linking CW15 CW16

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/multiwords.txt
@jaumeortola new words have been added to `multiwords.txt`
> [es] added new words

- languagetool-core/src/main/java/org/languagetool/rules/DictionaryMatchFilter.java
- languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
Fixes test failures and interaction of DictionaryMatchFilter with AnnotatedText with markup
> fix(core): make DictionaryMatchFilter work with markup

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/style.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5601
> [de] added rule + AP

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/style.xml
Had to merge the master branch into my branch because of conflicts that could be resolved in the PR
> Luisa12.5 

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
- To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5658
- The rules from the repetition category have been tagged
- Off and Temp_off rules haven't been tagged, that would be done later on
- Other rules from the bottom part of the document have been tagged
> [fr] Style_Tagging First part Repetitions

- languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
[#5642](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5642)
[#5678](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5678)
[#5686](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5686)
> [en] improve rules

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5675
New rule created for this expression
> [fr] AU_FUR_ET_A_MESURE Rule creation

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
- Category REPETITIONS_STYLE tagged as clarity
- Category CAT_PLEONASMES tagged as clarity
- FRENCH_WORD_REPEAT_RULE tagged as clarity
- Other few rules tagged
> [fr] Style rules tagging 2

- languagetool-core/src/main/java/org/languagetool/rules/patterns/CaseConversionHelper.java
- languagetool-core/src/main/java/org/languagetool/rules/patterns/Match.java
- languagetool-core/src/main/java/org/languagetool/rules/patterns/MatchState.java
- languagetool-core/src/main/java/org/languagetool/tools/StringTools.java
- languagetool-core/src/main/resources/org/languagetool/rules/pattern.xsd
- languagetool-language-modules/ar/src/main/java/org/languagetool/tools/ArabicStringTools.java
> [ar] add notashkeel to case conversions (replace #4626)

- languagetool-dev/src/main/java/org/languagetool/dev/GenerateIrishWordforms.java
- languagetool-dev/src/test/java/org/languagetool/dev/GenerateIrishWordformsTest.java
Adding wordforms is a little tedious, so I've started this to help but it needs quite a lot to be more generally useful:
> [WIP] [ga] wordform generator

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
3 "Off" rules have been placed in "Temp_off" so we can see their performance.
The rest of the rules in "Off" are mainly anglicisms and repetitions with a predictable behavior.
> [fr] Style rules temp_off

- languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
https://github.com/languagetool-org/languagetool/commit/131b9256f6578e854277a64aa1d7d39984dd774b
Changed prio and added 3 APs (more APs to be added)
Diff: https://internal1.languagetool.org/regression-tests/via-http/2023-05-23/de-DE_full/result_grammar_DOPPELTES_VERB%5B1%5D.html
> Doppeltes verb - added APs (still temp_off)

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
- A few tone_tags have been added
- AVOIR_BESOIN_DE new exception added based on diff, will see new results tomorrow
- ETRE_DAFFAIRES temp_off removed
- ETRE_JUSTIFIE_DE has been deleted
- FAIRE_APPLICATION has been deleted
- QUOI_FAIRE[1] improved
- QUOI_FAIRE[2] temp_off until tone tags are fully implemented
- NEGATION_PLUS_OU_DAVANTAGE temp_off after seeing results in diff
> [fr] Style tagging 3 follow up

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Too many FPs expected and hardly improvable
> [fr] ETRE_DAFFAIRES rule deletion

- languagetool-core/src/main/java/org/languagetool/ToneTag.java
[#5745](https://github.com/languagetooler-gmbh/languagetool-premium/issues/5745)
> toneTag general added

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
What it says on the tin, just some minor things I neglected.
> [pt] Address ESTA_ESTÁ nightly FPs

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- mostly stuff seen in the corpus that I noticed we needed to expand, nothing ground-breaking;
- really surprised about the lack of 'sera'->'será' correction, but I've triple-checked and it really doesn't get flagged anywhere 🤯
> [pt] Add and expand misc rules

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Closes languagetooler-gmbh/languagetool-premium#5790
> [pt] Improve antipatterns for CONFUSÃO_E_É

- languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/compounds.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetool-org/languagetool/issues/8766
+
https://regression.languagetoolplus.com/via-http/2023-06-07/de-DE/result_java_GERMAN_SPELLER_RULE.html
+
Reflektion -> Reflexion
> Jetzt erste

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
Simple rule inspired by annotation.
> [pt] Add CONFUSÃO_POSSO_POÇO rule

- languagetool-core/src/main/java/org/languagetool/synthesis/ManualSynthesizer.java
This saves ~2.8MB for me when English + German languages are loaded
> ManualSynthesizer: save memory by storing only suffixes where they're just added to the lemma

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
Removing `temp_off` after w24 QC.
> [pt] Enable CONFUSÃO_POSSO_POÇO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
> [pt] Enable new abbreviation rule

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://regression.languagetoolplus.com/message-spelling/result/2023-06-13/de-DE_diff.html
> [de] corrections

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
In the context of: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5855
> [fr] Grammalecte in OS HOTFIX

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/style.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5339
> [de] added rule group (temp_off) TEST

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Works as expected per nightly results.
> [pt] Enable X_RAY_MACHINE

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
In the context of:https://github.com/languagetooler-gmbh/languagetool-premium/issues/5842
More details in https://docs.google.com/spreadsheets/d/18ZEBC_s8MxBW4HwIi_TIoRfLU2UM8ih8Kwg4Gr4H3I0/edit?
**IMPORTATION of rules from Premium:**
- L_ON
- MAIS_SENT_START
CORRESPONDING PREMIUM PR: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/663
> [fr] Inclusion of Style rules from Premium to OS.

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
- languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanCompoundRuleTest.java
> [de] changed test rule (since test word was deleted)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Nothing too serious, tagging @susanaboatto so she sees it though.
> [pt] Replace nome with substantivo in grammar messages

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
A couple of minor changes inspired by the annotation task.
> [pt] Add PAIS_COUNTRY_OR_PARENTS

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
_I'm currently checking a scientific poster of mine and might add words to this PR tomorrow or so. For some reason, I don't see the option to convert this PR anymore. As such, sorry for the noise._
- https://en.wiktionary.org/wiki/nonlinearity
- https://en.wiktionary.org/wiki/attenuator
> [en] add spelling: "nonlinearity"

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
Grammalecte rules cleanup after https://github.com/languagetooler-gmbh/languagetool-premium/issues/5855.
> [fr] Grammalecte rules 21 june cleanup

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetool-org/languagetool/commit/82246d67d7d4a09521dc384df2f4554384d0ba87#r119106574
> [de] moved words

- languagetool-server/src/main/java/org/languagetool/server/HTTPServerConfig.java
- languagetool-server/src/main/resources/org/languagetool/server/mybatis-config.xml
Allow configuring connection pool
> feat(languagetool-server): added option dbMaxConnections

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
> [pt] Add tone tag disclaimer in style file

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
@susanaboatto @p-goulart 
Heya,
My first pull request.
Feel free to make changes if they are required.
Thanks!
> [pt] Added (style) rule ID:NOMECOMUM_PRONOME_VERBINF_REM_PRON

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
@susanaboatto @p-goulart @maphjo 
Here is an antipattern that fixes some false positives.
> [pt] Added AP to rule ID:VER_OBSERVAR_CONSTATAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is an antipattern to fix some false positives.
Thanks!
> [pt] Added AP to rule ID:SIMPLIFICAR_QUE_E_TEM_TÊM

- languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
Not needed for GRPCPostProcessing as it calls the getManagedChannel from GRPCRule
> Add client lb grpc rule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, Pedro and Susana,
Here is a brand-new academic/scientific rule developed thanks to Ricardo Joseh Lima.
https://github.com/languagetool-org/languagetool/issues/8948
> [pt] Added rule ID:CIENTÍFICO_DAR_CONFERIR (thanks to Ricardo Joseh Lima)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
This is not really a pleonasm, it's a valid, albeit informal, turn of phrase.
> [pt] Disable REDUNDANCY_16_DE for "de jeito maneira"

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/case_rule_exceptions.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@AgnesKleinhans: I added the short forms of the street name I added to spelling last, as we agreed. Please check and merge :-) Thx!
> [de] added words + comment in instructions re street names (above)

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/LineExpander.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
- languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/LineExpanderTest.java
Related PR: [[de] add street names](https://github.com/languagetool-org/languagetool/commit/1bf2271d3a2cfbb020a3c6bedfbb39c301f52338#commitcomment-121961848)
@danielnaber Could you please review this PR? :-) Thank you!
> [de] add str / strasse to LineExpander.java

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/added.txt
- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/spelling.txt
Heya!
Here are some missing words.
> [pt] Added words to added.txt and spelling.txt

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@Luisa-LT please review and merge :-) 
`# /T will add str. (Goethestraße --> Goethestr.)`
> [de] clean up spelling.txt straße

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
> [fr] Off rules 2

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/AgreementRuleAntiPatterns1.java
https://github.com/languagetool-org/languagetool/commit/59c42367063a696008dd15947f50536e717d7c93
> Halbe millionen

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
> [fr] Fix on instructions for Tone_Tags and WG to OS style file

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
> [fr] Off rules 3

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace.txt
Quick fix for: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5985
Prio seems good, greater than speller.
> [fr] Adding FR_SIMPLE_REPLACE_LU

- languagetool-core/src/main/java/org/languagetool/rules/patterns/PatternRuleHandler.java
The message is made more explicit about what is causing the error and a suggestion on how to eliminate the cause of the error has been added in bold.
> [all] Change wording for test message if default="…" is set on rulegroup and rule level

- languagetool-language-modules/sv/src/main/java/org/languagetool/language/Swedish.java
- languagetool-language-modules/sv/src/main/java/org/languagetool/tagging/disambiguation/sv/SwedishHybridDisambiguator.java
- languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/disambiguation.xml
- languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/multiwords.txt
- languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/sv.sor
- languagetool-language-modules/sv/src/main/resources/org/languagetool/resource/sv/tagset.txt
- languagetool-language-modules/sv/src/main/resources/org/languagetool/rules/sv/coherency.txt
- languagetool-language-modules/sv/src/test/java/org/languagetool/tagging/disambiguation/sv/SwedishDisambiguationRuleTest.java
- languagetool-language-modules/sv/src/test/java/org/languagetool/tagging/sv/SwedishTaggerTest.java
Adding a hybrid disambiguator for Swedish. Adding supporting files and some initial tests. Updating some other already existing supporting files.
> [sv] Adding a hybrid disambiguator for Swedish

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Add common verbs that introduce complements with 'de' as anti-patterns.
> [pt] Add AP to ACCENTUATED_PARONYMS_DE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Noticed this (very important) rule didn't have support for common 'para' contractions!
> [pt] Add contractions to FORMAL_PRA_PARA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
> [pt] Add ATOA_BR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- a handful are actually working okay (per nightly diffs) or have very little effect;
- the majority are very tricky, very old, and it makes sense to just switch them off;
- whenever I saw them, I removed those noisy comments (I've already let Marco know those aren't needed).
> [pt] Address very old temp_off rules

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/style.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5761
> [en] added toneTag disclaimer for OS contributors

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Just accounting for some usages of 'pro' from English.
> [pt] Add APs to FORMAL_PRA_PARA rule 3

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- https://internal1.languagetool.org/regression-tests/via-http/2023-07-25/pt-BR_full/result_grammar_ATOA_BR%5B1%5D.html
For w30 QA check ahead of premium deployment.
> [pt] Enable ATOA_BR and FORMAL_PRA_PARA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
This is the rule I couldn't create last week because TESTRULES PT wasn't working.
Depends on #9030
> [pt] Added rule ID:DAR_VALOR_VALORIZAR

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt
- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
As this is my first time adding to `spelling.txt` and `added.txt`, I'd appreciate the review.
> [en] added word

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/verbs.ent
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
A few more changes based on nightly diffs. The rule isn't ready yet, I'll be doing this gradually and iteratively until it's ready, as it's quite complex.
> [pt] Make improvements to 2SG rule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
An antipattern for false positives.
> [pt] Added AP to rule ID:VERB_QUE_É_VERB_SER

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Previous suggestion removed punctuation from the original sentence. This was fixed.
> [pt] fix suggestion in INTERNET_ABBREVIATIONS

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Rules deleted:
Envie
Auvent
Surtout
Autour
Encours
Enfer
Encas de (was temp_off)
2 more envie temp_off rules 
D’autrefois (was temp_off)
2 Maven warnings fixed in style.
> [fr] MOTS_COLLES_OU_SEPARES rules removed

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> [pt] Rewrote AP of rule ID:CONFUSION_POR_PÔR_V2

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Like I wrote before, the wordiness-pt.txt rules were giving too many FPs in the two lines I added there.
So, I have converted the lines into a XML rule.
Here are the results:
[_1.txt](https://github.com/languagetool-org/languagetool/files/12266696/_1.txt)
❤️ ❤️ ❤️ 
Thanks!
> [pt] Added rule ID:SER_NECESSARIO_NECESSARIO_V2

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/style.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6082
> [de] H2O moved from grammar to style and changed messages

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> [pt] Add AP to pt/grammar/ACCENTUATED_PARONYMS_DA

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5043
> [fr] Rule linking OS CW29/CW30

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Bad results of the rule, also related to: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/876
> [fr] LEVEE_DE_FONDS Removed

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/replace.txt
https://github.com/languagetool-org/languagetool/issues/9145
> [de] added corrections

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Removing temp_off for 
- BOSS
- BODY_BUILDING
> [fr] Removing temp_off

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
I have removed the "temp_off".
Thanks!
> [pt] Removed "temp_off" from rule ID:SER_NECESSARIO_NECESSARIO_V2

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
POINT_VIRGULE_OS still not behaving as expected, temp_off so we can see the diff
1 rule moved from grammar to style
> [fr] POINT_VIRGULE_OS temp_off

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
[Results](https://internal1.languagetool.org/regression-tests/via-http/2023-08-25/pt-BR/result_grammar_CONC_NUM_GEN_O_SUAS%5B2%5D.html) look good, just a couple of APs.
> [pt] Add APs to CONC_NUM_GEN_O_SUAS and enable

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
[Works](https://internal1.languagetool.org/regression-tests/via-http/2023-08-25/pt-BR/result_grammar_ENCIMA_LOCUCAO%5B1%5D.html) okay.
> [pt] Enable ENCIMA_LOCUCAO

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/removed.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6076
> [de] remove postag

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Added AP to rule id:SIMPLIFICAR_À_VERBO_DE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya, @p-goulart 
I noticed that you had added it to the pt-PT grammar.xml already, thank you.
I have now added it to the pt-PT style.xml as well.
My goal for 2024 will be to revise all pt-PT rules and improve them the maximum possible, adding these messages.
The year is ending, which means that in this year it isn't doable… too much going on… I can't focus 100% on specific tasks.
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
> [pt-PT] Added "ENTITY % messages SYSTEM" to style.xml

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
No FPs, no hits at all lol, should be safe.
> [pt] Enable DEUS_DARA rule

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Related to: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/942
> [fr] DICTIONARY_UPDATE added.txt and multiwords.txt

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @p-goulart and @susanaboatto 
Here is a nice academic rule:
```
Portuguese (Portugal): 4 total matches
Portuguese (Portugal): 599999 total sentences considered
```
[7.txt](https://github.com/languagetool-org/languagetool/files/12501362/7.txt)
Discussion here:
https://github.com/languagetool-org/languagetool/issues/9220
Thanks!
> [pt] Added rule ID:TOMAR_ASSUMIR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/post-reform-compounds.txt
> [pt] Remove via láctea from compounds for #9140

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/compounds.txt
Related to https://github.com/languagetooler-gmbh/languagetool-premium/issues/6174
Commented out some of the justified low apply rate sub IDs
> [fr] FR_COMPOUNDS checked

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6220
Premium PR: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/956
> [fr] check_case.txt verified, OS related changes

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
Added APs and activated rule ([diff](https://regression.languagetoolplus.com/via-http/2023-09-07/de-DE/result_grammar_FINANZTIP%5B1%5D.html))
> [de] added APs + activated rule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Based on [Matomo disables](https://analytics.languagetoolplus.com/matomo/index.php?module=Widgetize&action=iframe&secondaryDimension=eventName&moduleToWidgetize=Events&actionToWidgetize=getAction&idSite=18&period=week&date=today&flat=1&filter_column=label&show_dimensions=1&filter_pattern=MAIS_BEM_MELHORES).
The rule performance isn't amazing thus far... let's keep it alive a little more so I can gather more data on why.
> [pt] Add APs to MAIS_BEM_MELHORES

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
> add suggestion

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
https://github.com/languagetool-org/languagetool/commit/1a9ac5f49acf4e67eab77baba0496a4c1cfea83f#r127007025
> [de] removed Vermögensteuer

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
For #8945, part of languagetooler-gmbh/languagetool-premium#6261.
> [pt] Add CONCORDANCIA_DAR_HORAS rule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
> [pt] Added antipattern to rule ID:FAZER_VERBO_VERBO_INFINITIVO

- languagetool-core/src/test/java/org/languagetool/rules/WordListValidatorTest.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/5257
> [de] added words from Marvin

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The [pt] one seems to have the results right:
https://internal1.languagetool.org/regression-tests/via-http/2023-09-13/pt-BR_full/result_style_TOMAR_ASSUMIR%5B1%5D.html
The [pt-PT] seems to have no results (at least I didn't find it there).
Thanks!
> [pt][pt-PT] Removed "temp_off" from rules

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- added a subrule to detect `daqui há`
- cleaned up rule comments
> [pt] add subrule and clean up CONFUSÃO_À_HÁ

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/added.txt
- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/spelling.txt
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Adding 'acontecer' to the list of non-impersonal verbs has brought to light many other structures we weren't quite handling very well in this rule, so I've made a few fixes.
> [pt] Improve pt/fix/NON_IMPERSONAL_VERBS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Diff results are encouraging. One minor change but otherwise it should be ready for primetime.
> [pt] Enable NON_IMPERSONAL_VERBS[2]

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
Diff for 2nd commit: https://regression.languagetoolplus.com/via-http/2023-09-17/de-DE/result_grammar_SCHOENE_WETTER%5B2%5D.html
> [de] improvements (various)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Looks [good](https://internal1.languagetool.org/regression-tests/via-http/2023-09-21/pt-PT_full/result_grammar_URL_INICIAL%5B1%5D.html) to me, I suppose.
> [pt] Enable URL_INICIAL

- languagetool-http-client/src/main/java/org/languagetool/remote/SentenceAnnotator.java
- md5 hashes to keep track of unique sentences;
- username;
- timestamp.
> Add more info to SentenceAnnotator output

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-AO/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-MZ/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Just adding a link to our docs.
> [pt] Add comment linking OS contributors to PT docs

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- add numerals;
- improve disambiguator to remove extremely rare verbs that were polluting the user suggestions.
> [pt] Improve NON_IMPERSONAL_VERBS

- languagetool-language-modules/de/src/main/java/org/languagetool/language/German.java
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6370
> [de] changed prio over gGEC

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya, Pedro and Susana,
Only two hits:
https://internal1.languagetool.org/regression-tests/via-http/2023-09-27/pt-PT/result_style_PARA_SER_MELHORADA_A_MELHORAR%5B1%5D.html
😋 😛 ❤️
> [pt] Removed "temp_off" from rule ID:PARA_SER_MELHORADA_A_MELHORAR

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6392
> [de] added AP for FP after horizontal ellipsis

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Broadening the time expression antipattern.
> [pt] Fix time expressions after NON_IMPERSONAL_VERBS

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/CaseRuleAntiPatterns.java
- languagetool-language-modules/de/src/main/java/org/languagetool/tokenizers/de/GermanCompoundTokenizer.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/added.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
@St-ac-y ich habe noch tags für Oval als Nomen hinzugefügt. FYI
> Improvements 28.9. 

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Only three hits:
```
Portuguese (Portugal): 3 total matches
```
[_1.txt](https://github.com/languagetool-org/languagetool/files/12774093/_1.txt)
> [pt] Added rule ID:TORNAR_MELHOR_PIOR_MELHORAR_PIORAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
An antipattern to fix false positives.
> [pt] Added AP to rule ID:GENERAL_NUMBER_AGREEMENT_ERRORS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
TORNAR_MELHOR_PIOR_MELHORAR_PIORAR
https://internal1.languagetool.org/regression-tests/via-http/2023-09-30/pt-BR/result_style_TORNAR_MELHOR_PIOR_MELHORAR_PIORAR%5B1%5D.html
https://internal1.languagetool.org/regression-tests/via-http/2023-09-30/pt-BR/result_style_TORNAR_MELHOR_PIOR_MELHORAR_PIORAR%5B2%5D.html
SER_SIGNIFICATIVO
https://internal1.languagetool.org/regression-tests/via-http/2023-10-01/pt-BR/result_style_SER_SIGNIFICATIVO%5B1%5D.html
https://internal1.languagetool.org/regression-tests/via-http/2023-10-01/pt-BR/result_style_SER_SIGNIFICATIVO%5B2%5D.html
> [pt] Removed temp_off from rules

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Fxing the loop from: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6321
The second suggestion of the rule causing the loop has been deleted, therefore fixing the loop issue.
> [fr] PAS_DE_VIRGULE rework 2

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
Just improved the suggestion to also suggest “expressivo”.
The idea came up during sleep.
> [pt] Improved suggestions in rule ID:SER_SIGNIFICATIVO

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6459
List of rule IDs involved:
- PLEONASMES_DIVERS[83]
- AUX_ETRE_VCONJ[2]
- A_ACCENT[31]
- VOIE_VOIX[3]
- QUELQUE_TRUC[1]
- QUE_AVOIR[2]
- MOTS_INCOMP[94]
- ENUMERATION_DET[7]
> [fr] FP_FIX_BATCH1_6459

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Absolutely disastrous idea lol. May need to come up with better triggering conditions...
> [pt] Disable URL_INICIAL

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
To address: https://github.com/languagetooler-gmbh/recurring-issues/issues/4
Also closes: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6422
> [fr] [BAU] Grammalecte check W40-41

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
- languagetool-language-modules/de/src/main/java/org/languagetool/tokenizers/de/GermanCompoundTokenizer.java
- languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java
@danielnaber GermanSpellerRuleTests pass! 💪
Edit: CircleCi fails on testGetAdditionalTopSuggestions
> [de] improve GermanSpellerRule java + add GermanSpellerRuleTest Cases

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
@p-goulart @susanaboatto 
I hope to have it done right trying to branch and pull or push, I can't remember.
Here are the results of this rule.
There is no way to deal (antipattern) with these results, I believe.
```
Portuguese (Portugal): 22 total matches
```
[_6.txt](https://github.com/languagetool-org/languagetool/files/12843524/_6.txt)
Thank you!
> [pt] Added rule ID:FAZER_EXERCER

- languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
- languagetool-core/src/main/java/org/languagetool/rules/RemoteRuleConfig.java
- languagetool-core/src/test/java/org/languagetool/rules/GRPCRuleTest.java
This configures a parameter called maxSentenceLength for long sentences to be handled in another way.
> GRPC length parameter for long sentences

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/removed.txt
Requesting a review since I don't often make changes to the dictionary files.
> [en] added entries to removed.txt

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
Hello Pedro and Susana,
Is this it? Two or three lines of XML?
It was supposed to be hard?
> [pt] Added verb "tomar" to disambiguation.xml

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
AP added in MOTS_INCOMP[94] to fix: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6538
Dictionary addition to fix: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6536
> [fr] MOTS_INCOMP_94_AP_added

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
please check @AgnesKleinhans  :-)
> [de] 2 APs for gGEC

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/ignore.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Week 40 edition of the word addition https://github.com/languagetooler-gmbh/languagetool-premium/issues/5240
> [fr] words addition

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
> [de] AP for gGEC

- languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java
- languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/MorfologikAmericanSpellerRuleTest.java
TODO:
- need to check locally generated diff with `SentenceSourceChecker`
> [en] test for misspelled hyphenated words

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
The rule now handles more situations.
> [pt] Improved rule ID:INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Hello Pedro and Susana,
I have spent day and night almost working on this rule to replace the old one that had `default=off`.
As I was adding the exceptions and antipatterns, I observed that it was moving in a direction different than I expected.
Could you please examine the rule and the examples in it to see if changes are required?
Thanks!
Here are the results:
```
Portuguese (Portugal): 98 total matches
```
[_57.txt](https://github.com/languagetool-org/languagetool/files/13038630/_57.txt)
```
<rule id='COLOCACAO_ADVÉRBIO_VERBO_ANTES' name="Colocação de advérbio mover verbo" type="style" default="temp_off" tone_tags="clarity">
<antipattern>
<token>que</token>
<token …
```
> [pt] Replaced old default=off rule with new one ID:COLOCACAO_ADVÉRBIO_VERBO_ANTES

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
@p-goulart 
Pedro, here is an example of SPS00.
I will fix the other two things you told me in the other rules later at afternoon/night as I am stressed… 😛 nothing to worry about, it is normal.
Thanks!
> [pt] Added example SPS00 to rule ID:TOMAR_ASSUMIR

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-DE-AT/grammar.xml
Moved rule from premium wrt this issue: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6289
> [de] add rulegroup to de-DE-AT from prem

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
AP to solve FP in the sentence:
_Él dijo: Bendita seas de Yahvé, hija mía; tu segundo acto de lealtad ha sido mejor que el primero, porque no has pretendido a ningún joven, pobre o rico._
> [es] added AP to AI_ES_HYDRA_LEO_MISSING_COMMA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
This should remove the false positives.
❤️ ❤️ ❤️ ❤️ ❤️
> [pt] Removed false positives from rule ID:INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/added.txt
- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/removed.txt
Heya,
This should fix the false positive of “`tórax”` in the INIMIGOS_ rule.
The other ones I will fix later.
> [pt] Fixed postags of word "tórax"

- languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikMultiSpeller.java
load dictionary content lazily, when we don't have it already cached
also fixed formatting
> feat[core]: skip reading dictionary when cached one exists

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/ProhibitedCompoundRule.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/prohibit.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/replace.txt
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6225#issuecomment-1785632204
> [de] added words + prohibited compound parts

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-CH/grammar.xml
please check :-) @AgnesKleinhans
> [de] add typography rules for CH

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
After over a month of complete writes and rewrites, it is ready.
This is the best it can get.
https://github.com/languagetool-org/languagetool/issues/9303
```
Portuguese (Portugal): 127 total matches
```
[58.txt](https://github.com/languagetool-org/languagetool/files/13216243/58.txt)
```
<rule id='IR_CONTRACTION_NOUN' name="Ir + 'na/no' + nome → à/ao" default="temp_off">
<antipattern>
<token postag='VMN0000' postag_regexp='no'/>
<token regexp='yes' spacebefore='no'>&tracos_de_separacao;</token>
<token regexp='yes' spacebefore='no'>&pronomes_obliquos_sem_a_as_o_os;</token>
<token regexp='yes' spacebefore='no'>&tracos_de_separacao;</token>
<token …
```
> [pt] Complete rewrite of rule ID:IR_CONTRACTION_NOUN

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Rules for gender agreement.
Number of hits against 900 000 sentences=0
Thanks!
> [pt] Added rule ID:PELO_QUAL_PELA_QUAL and rule ID:PELA_QUAL_PELO_QUAL

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
An antipattern.
❤️ ❤️ ❤️ ❤️
> [pt] Added AP to rule ID:CRASE_CONFUSION

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wordiness.txt
Heya,
I moved the rules from wordiness.txt and created an XML rule with a broader scope (more powerful).
> [pt] Moved and improved rules from wordiness.txt to rule ID:QUALQUER_QUE_SEJA_FOSSE_INDEPENDENTEMENTE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
0 hits in 900 000 sentences.
> [pt] Rewrote rule ID:É_IGUAL_AO_LITRO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/spelling.txt
Heya,
I have just added a few missing words that already had postags.
> [pt] Added words to spelling.txt

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
Here is a formal rule.
Follow the discussion here:
https://github.com/languagetool-org/languagetool/issues/9555
Thanks!
> [pt] Added rule ID:QUASE_QUE_PRONOME_QUASE_PRONOME

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
@susanaboatto 
You approved this commit:
https://github.com/languagetool-org/languagetool/pull/9594
This is it without the conflicts, I hope.
> [pt] Recommit of rule ID:DIFERENTES

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
> [de] added gunsten + ungunsten (should be capital)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
Some FPs removed.
Thanks!
> [pt] Added exceptions to rule ID:CONFUSÃO_ESTA_ESTÁ (soon I must join both rules into one)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
I have improved the rule, and it can't become much better than this.
0 hits in 900 000 sentences.
> [pt] Improved rule ID:AFEAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Removed temp_off from rule ID:É_IGUAL_AO_LITRO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Hi!
An antipattern to fix false positives.
> [pt] Added antipattern to rule ID:GENERAL_NUMBER_AGREEMENT_ERRORS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Hi,
I have rewritten this rule.
Please suggest more or other verbs for it if required.
It is a very low-impact rule with 0 hits in 900 000 sentences.
> [pt] Rewrote rule ID:ESTAR_NO_ECRA

- languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
https://github.com/languagetool-org/languagetool/issues/9560
> [de] improved message

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6692
> [de] added gGEC AP

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/ProhibitedCompoundRule.java
https://github.com/languagetool-org/languagetool/pull/9637
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6225
> [de] added potential confusion pairs

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
Not much of an improvement, I know 😛
> [pt-PT] Improved slightly rule ID:ERRO_TRADUÇÃO_FURTO_ROUBO_IDENTIDADE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Slightly improved, but still zero hits in 900 000 sentences.
> [pt-PT] Improved slightly rule ID:ERRO_TRADUÇÃO_ESTIMAÇÃO_MÁXIMA_SEMELHANÇA_PT_PT

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Removing temp_off on NOUVEL_AN
> [fr] NOUVEL_AN removing temp_off

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
The only hit in 900 000 sentences was:
```
Title: <plaintext>
1.) Line 1, column 70, Rule ID: CAUSAR_DIFICULDADE_DIFICULTAR[1] [temp_off]
Message: Para conferir mais clareza ao seu texto, busque usar uma linguagem mais concisa.
Suggestion: dificultou
Rule source: /org/languagetool/rules/pt/style.xml
Retomou a teoria aristotélica sobre a eternidade do mundo, o que lhe causou dificuldades com os círculos islâmicos ortodoxos.
^^^^^^^^^^^^^^^^^^^                                     
Portuguese (Portugal): 1 total matches
Portuguese (Portugal): 54439 input lines ignored (e.g. not between 10 and 300 chars or at least 4 tokens)
```
> [pt] Another attempt to recommit rule ID:CAUSAR_DIFICULDADE_DIFICULTAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wordiness.txt
> [pt] Added words to wordiness.txt

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/ignore.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/5240
> [fr] Dictionary additions Ongoing FBB issue

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
But the number of hits in 900 000 sentences is still zero.
> [pt] Rewrote rule ID:TRABALHO_PAGO_REMUNERADO

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/replace.txt
To fix https://github.com/languagetooler-gmbh/languagetool-premium/issues/6728
> [fr] Replace addition

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/words_infix_s.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/words_no_infix_s.txt
First part of the re-visited words listed in `words without infix s`.
Now that we have more knowledge about compound formation, I have revised the list again and removed some cases due to possible confusion, added, removed or moved to `words infix s`
@danielnaber @AgnesKleinhans could you please check if this procedure is correct/helpful?
If yes, I will continue the same way with the second part of the list.
> [de] corrected, removed, added words (some moved to infix_s) to avoid FNs

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/de-CH/grammar.xml
please check :-) @AgnesKleinhans 
Gibt es noch etwas, was in den Regeln bis jetzt nicht vorkommt ([issue als Referenz](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6289))?
@danielnaber
> [de] SWISS_GERMAN_NUMBER_FORMAT

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
To address: https://github.com/languagetooler-gmbh/recurring-issues/issues/23
Information on disable reasons in the linked issue.
> [fr] GRAMMALECTE_DISABLES_w46

- languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
Two lists have been added:
- names of singers from Latin America, Spain, and Italy;
- names of apps, websites...
> spelling_global.txt new lists

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @p-goulart and @susanaboatto 
I have removed this useless rule.
😛 😛 😛 😛 😛 😛
> [pt] Removed rule ID:MADRUGADA_MATINAL

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Added exception to rule ID:SIMPLIFICAR_QUE_VERBO_A_VERBOINFINITIVO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Ahhh… it is like an antipattern to remove some FPs.
> [pt] Added exception to rule ID:ESTA_ESTÁ

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/multiwords.txt
List of multitoken _municipios_ from Spain and Colombia. @jaumeortola
> [es] added names of municipios from Spain and Colombia

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/ignore.txt
- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/hunspell/spelling.txt
- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/multiwords.txt
PR until the build is sorted out
> [en] add words

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
An antipattern to fix false positives.
😛 😛 😛 😛 😛 😛
> [pt] Added AP to rule ID:SENDO_PARTPASS_PARTPASS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
Zero hits in the nightly results.
> [pt] Removed "temp_off" from rule ID:TRABALHO_PAGO_REMUNERADO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
I have fixed false positives, but I need to rewrite the rule soon to make it less complex and more accurate.
> [pt] Improved AP in rule ID:SIMPLIFICAR_QUE_E_TEM_TÊM

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- New verb agreement rule based on user feedback.
- Merged to check diff results.
> [pt] add rule CONCORDANCIA_SER_PLURAL

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6748
> [de] added 2 APs

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- Agreement rule based on user feedback;
- Merged to check diff results.
> [pt] add rule CONCORDANCIA_QUALQUER

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
https://github.com/languagetool-org/languagetool/pull/9772#discussion_r1407906404
> [de] modified gGEC AP

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
https://github.com/languagetooler-gmbh/languagetool-premium/issues/3106
Local testing showed expected results (no speller matches)
To merge after premium deploy
@affemitkaraffe @St-ac-y @AgnesKleinhans, could 1 of you please review and approve if it looks good to you or let me know if I missed smth? Thx!
> [de] added rule

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
@St-ac-y @Luisa-LT please review :-)
> [de] add AP AI_DE_HYDRA_LEO_CP_DEM_DEN

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> [pt] Add AP to GENERAL_VERB_AGREEMENT_ERRORS

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/multiwords.txt
List with multitoken _municipios_ from Chile.
> [es] added municipios to multiwords.txt

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
> [de] fix AP for GGEC

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Handle a couple of FPs from temp disable stats.
> [pt] Add APs to NON_IMPERSONAL_VERBS

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanCompoundRule.java
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/remote-rule-filters.xml
To address this issue: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6392
and this issue: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6670
> [de] added/modified gGEC APs 

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To fix: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6700#issuecomment-1833666799
(see the last part of the comment)
> [fr] BELGICISME-AI_AP

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/6788
> [fr] Dictionary additions 

- languagetool-core/src/main/java/org/languagetool/rules/spelling/morfologik/MorfologikSpellerRule.java
- languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
- languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/MorfologikAmericanSpellerRuleTest.java
... so we have better suggestions for cases like "snoww-covered"
> [en] re-add the call to addHyphenSuggestions() 

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Related to premium: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/1193
> [fr] BONJOUR-AI_AP

- languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/wrongWordInContext.txt
- languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanWrongWordInContextRuleTest.java
to monitor impact and then decide if we need a fix or deactivate this pair
> [de] modifications

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/style.xml
Reverts languagetool-org/languagetool#9825
> Revert "[en] added AP to serial comma rule"

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Here are the `pt-PT` files indented with 4-space-wide soft tabs, same as the other files.
> [pt-PT] Indent grammar and style files

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/ignore.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/5240
To address and close: https://github.com/languagetooler-gmbh/recurring-issues/issues/32
Linked to premium: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/1208
I'm not fully on point with dictionary additions, I might have done some unnecessary or wrong things!
> [fr] New-words-week-49

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
@marcoagpinto this should address #9873. Feel free to merge the PR once the tests pass, then just rebase your working branch on `master`.
> [pt] Update regex in IGNORE_SPELLING_KKK_LAUGHTER disambig rule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is one of the rules I was going to work on the weekend.
```
Portuguese (Portugal): 113 total matches
Portuguese (Portugal): 811129 total sentences considered
```
[_REGRAS_1e2_20.txt](https://github.com/languagetool-org/languagetool/files/13635040/_REGRAS_1e2_20.txt)
> [pt] Added rule ID:BÁSICO_ELEMENTAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/misc.ent
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Presumably the last round of fixes, nightlies looking pretty solid now.
> [pt] Update ESPERA_QUE_INDICATIVO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
No FPs in the nightlies for either rulegroup.
> [pt] Enable DET_FEM_MAS_A_O and SUBST_SOBRECOMUM_MASCULINO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Nightlies finally looking cleaner, I think we can go ahead with this one.
> [pt] Enable ESPERA_QUE_INDICATIVO

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
- Moved a few FR grammar rules that were living in style
- Intruding myself into the EN grammar file to fix a few messages with wrong token position (found them in the diff, [I did the same for FR](https://github.com/languagetool-org/languagetool/pull/9912) but we had much more), it affects EN CURE_FROM_OF and LOG_IN
> [fr] Impostor-style-to-grammar + EN messages fix

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/state_name_mapping.txt
We can fix the articles later if we see something odd. For now I just want to use the name and abbreviation, but in a premium rule.
> [pt] Add state name mapping

- languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
> [fr] GGEC_REPLACEMENT_ORTHOGRAPHY-prio-lowered

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya,
Just an antipattern to fix false positives.
> [pt] Added AP to rule ID:QUE_É-SÃO_NC-ADJ_COMO-POR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
A few false positives removed, and came up with a strategy:
I will look at the next night diff and will only use valid words in the next change instead of using all with exceptions.
(Fewer results but more accurate)
(WIP).
Thanks!
> [pt] Improved rule ID:BÁSICO_ELEMENTAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> [pt] Improved rule ID:CONFUSÃO_ASSERTO_ACERTO_DE_CONTAS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
Improved the message like Pedro suggested.
> [pt] Improved message in rule ID:ARREAR_ARRIAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> [pt] Improved suggestions in rule ID:CONFUSÃO_APROXIMA_A_PRÓXIMA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Heya,
I improved the message like Pedro suggested.
> [pt] Improved suggestion of rule ID:CONFUSÃO_ASSERTO_ACERTO_DE_CONTAS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Simple fix for a couple of FPs. Not very frequent so prob. not very urgent. Related to #9958.
> [pt] Add SIMBOLO_DE_GRAUS_COM_UNIDADE_EM_MINUSCULA

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To partially address "dash and numbers" from: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6700
At least this one is working... But it's not the most useful, the most important one is still UNNECESSARY_PUNCTUATION_DASH
> [fr] gGEC-AP-numbers1

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Simple regexp fix. We're almost there, though. I feel like after this iteration we'll be ready to deploy this properly.
> [pt] Fix SEPARADORES_DE_ESTADO regexp

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6844
> [fr] multiwords-added

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Now, instead of two subrules, all is done in one rule.
The words it accepts are there, making it easier to add or remove words.
This means, that if one of you detects false positives, it is just a matter of deleting the specific word from the rule.
> [pt] Improved/rewrote rule ID:BÁSICO_ELEMENTAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @susanaboatto  and @p-goulart ,
Here it is an academic rule.
It had 0 hits in 900 000 sentences.
> [pt] Added rule ID:APAGAR_INDELÉVEL

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
I have been enhancing a few rules.
This one has zero hits in 900 000 sentences.
> [pt-PT] Improved rule ID:CONFUSÃO_CAIXA_EMBALAGEM

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
Heya,
An antipattern.
❤️ ❤️ ❤️ ❤️ ❤️ ❤️
> [pt-PT] Added AP to rule ID:POSSESSIVE_WITHOUT_ARTICLE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
@p-goulart had already approved it:
https://github.com/languagetool-org/languagetool/pull/9998
But it had conflicts with the repository, so I have repulled it as a new branch and after the tests finish I will merge it.
😛 😛 😛 😛 😛 😛 😛
> [pt-PT] Repull of rule conflicting with repository, rule ID:PRAZER_EM_CONVIDAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
Moved it to pt-PT.
https://github.com/languagetool-org/languagetool/pull/9991
> [pt-PT] Moved pull request from PT to pt-PT, rule ID:QUE_SE_VERBO_PART_PASSADO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/messages.ent
Heya,
A message for translations that can't be translated literally.
> [pt] Added message to messages.ent (ENTITY translation_msg)

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
I have rewritten the rule and made it really simple.
It has zero hits in 900 000 sentences.
> [pt-PT] Rewrote rule ID:CRIAR_QUERER

- languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
- languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
- languagetool-language-modules/ca/src/test/java/org/languagetool/rules/ca/CatalanTest.java
- languagetool-language-modules/en/src/test/java/org/languagetool/JLanguageToolTest.java
> feat: support for tags/picky mode from GRPCRule

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
Another pt-PT rule rewritten and thus a lot smaller/simpler than the previous code.
> [pt-PT] Rewrote rule ID:DO_QUE_AQUELE_QUE_ÀQUELE_QUE_PT_PT

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Correcting some wrong suggestions linked to https://github.com/languagetooler-gmbh/languagetool-premium/issues/6777
Also in the context of 
https://github.com/languagetooler-gmbh/languagetool-premium/issues/6844
> [fr] Additions | corrections (duplicates)

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/remote-rule-filters.xml
@jaumeortola: I hope this fixes the issue [#6758](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6758)
> [es] add rules AI_ES_HYDRA_LEO_MISSING_COMMA

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Related to: https://github.com/languagetooler-gmbh/match-maker/issues/73 (see the last comment)
> [fr] GGEC_AP_ADDED_OLDSPELL

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Found new names in the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/6777
> [fr] New batch from spelling rules diff

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/entities.ent
FR_MULTITOKEN_SPELLING rules can FP on Madame + Name.
This could fix it, we could lose some good matches, but it won't be massive.
> [all] adding Madame to exceptions_multitoken_spell

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6825
Premium PR: https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/1250
For style rules with at least ~500 opens and up to 20% apply rate.
Everything is also documented in the spreadsheet.
> [fr] Cleanup Style rules 2

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
[#6813](https://github.com/languagetooler-gmbh/languagetool-premium/issues/6813)
> [en] add some spelling rules

- languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Adding names to fr dictionnary files
One addition also to spelling_global. 
(after https://github.com/languagetool-org/languagetool/commit/9b4f348ee5fee61ad5282a144e5dabc8f0d474cc)
> [all][fr] Dictionnary additions

- languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanUnpairedBracketsRule.java
https://github.com/languagetool-org/languagetool/commit/9a9446a1b266a42e5b0f47a432b249a4f6503486#r136592866
> [de] removed also "<"

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Heya, @susanaboatto  and @p-goulart 
These exceptions added here fix false positives.
> [pt] Added exceptions to rule ID:INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/multiwords.txt
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Addressing an [unintended side effect](https://internal1.languagetool.org/regression-tests/via-http/2024-01-09/pt-BR/) of fixing the multi-token prepositions in `multiwords.txt`. Relatively urgent 😬 ⚠️
> [pt] Fix multi-token prepositions

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have just created this rule.
It had zero hits in 900 000 sentences.
Follow the discussion here:
https://github.com/languagetool-org/languagetool/issues/10053
Thanks!
> [pt] Added rule ID:FICAR_PARADO_TEMPO_ESTAGNAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
@p-goulart 
I am going to merge it after the checks, this is the easiest way to solve merge conflicts without much stress.
> [pt] Repulled request ID:DAR_EXEMPLO_EXEMPLIFICAR to solve conflict in merge

- languagetool-language-modules/pt/src/main/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizer.java
- languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
Fix issue with new tokenisation of strings containing `%`, and add tests.
> [pt] Fix percent tokenisation

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Just a couple of antipatterns.
Thanks!
> [pt] Added APs to rule ID:VERBO_ESTAR_A_VERBO_INF

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/multitoken-ignore.txt
- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/multitoken-suggest.txt
Improvements (added words  + exceptions + examples) + changed messages
Diff: https://regression.languagetoolplus.com/via-http/2024-01-15/de-DE_full/result_grammar_DE_MULTITOKEN_SPELLING_TWO%5B4%5D.html
@jaumeortola could you please review the changes (especially the exceptions added to the rules)? Thanks!
> [de] DE_MULTITOKEN_SPELLING_TWO_4 

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/style.xml
Discussions with the WV french data team led to move these rules from grammar to style.
> [fr] Moving rules from grammar to style

- languagetool-language-modules/ca/src/main/resources/org/languagetool/resource/ca/compounds.txt
- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/compounds.txt
https://github.com/languagetool-org/languagetool/pull/10192
> Luisa lt test line expander

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Following: https://github.com/languagetool-org/languagetool/pull/9969
But also to finish addressing the "dash and numbers" issue from: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6700 (see the last comment on why it's an important fix)
> [fr] gGEC-AP-numbers2

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/replace.txt
Requesting review, as it's my first change in `replace.txt`
> [en] simple replace {untied Ireland=>united Ireland}

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
In the context of [fr][BAU] Grammalecte check week 05
[#58](https://github.com/languagetooler-gmbh/recurring-issues/issues/58)
> [fr] Grammalecte rules deactivations

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
If you have a better idea for a more detailed message, be my guest, but I had to fix that. Portuguese (at least prescriptively) doesn't have object agreement. (And if we did, this wouldn't be an instance of it, that's clearly the subject.) (UGH)
> [pt] Fix message of REFLEXIVE_VERB_SE_AGREEMENT

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/spelling.txt
Already put it in the source dict, but since that work is still in progress I'm adding a hotfix here.
> [pt] Add hotfix for verossimilhança

- languagetool-core/src/main/java/org/languagetool/rules/LongSentenceRule.java
- languagetool-core/src/test/java/org/languagetool/rules/LongSentenceRuleTest.java
It solves https://github.com/languagetooler-gmbh/languagetool-premium/issues/7066
> LongSentencceRule: sentences with quotes

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
See last comment in: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6700#issuecomment-1974215379
Edit: CircleCi test failure fixed
> [fr] AI_FR_GGEC-IEL-APs

- languagetool-server/src/main/java/org/languagetool/server/LanguageToolHttpHandler.java
Adds more data to root span for better visibility
> adds metadata to root span

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/compounds.txt
https://github.com/languagetool-org/languagetool/issues/10399
> [en] commented out terms from compounds.txt

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/added.txt
- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
@jaumeortola: Could you take a quick look whether it's fine like this? Thank you!
> [es] add words to dict

- languagetool-language-modules/ca/src/main/resources/org/languagetool/rules/ca/replace.txt
> [ca] add word to replace.txt (reanudació)

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To address: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7088
Issue will be closed once tested in production.
> [fr] ETRE_VPPA_OU_ADJ-15-AP-ADDED+gGEC-AP

- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/multiwords.txt
Heya, @p-goulart and @susanaboatto 
Here are the words added.
Thanks!
❤️ ❤️ ❤️ ❤️
> [pt] Added words to multiwords.txt

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
Attempt to fix suggestions for Quick/Quic in FR (see https://www.quick.fr/)
> [fr] Adding Quick to fr dictionaries

- README.md
> Add Forum to the README.md

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
To fix and close: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7097
> [fr] MAIS_SENT_START_GGEC_LOOP_FIX

- languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
- languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
Second attempt from https://github.com/languagetool-org/languagetool/pull/10458 (now with working tests in `JLanguageToolTest.java`)
> [fr] AI_FR_GGEC_MAIL2

- languagetool-language-modules/es/src/main/resources/org/languagetool/rules/es/replace_verbs.txt
[Based on this Fundeu article](https://www.fundeu.es/recomendacion/colorear-y-coloreo-mejor-que-colorizar-y-colorizacion/)
> [es] add colorizar-colorear to replace_verbs

- languagetool-language-modules/pt/src/main/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizer.java
- languagetool-language-modules/pt/src/test/java/org/languagetool/tokenizers/pt/PortugueseWordTokenizerTest.java
After a lot of tsuris, managed to find the guilty line.
@SteVio89, I'm afraid we'll need a redeploy of OS with this change.
(cc @susanaboatto)
> [pt] Fix word tokeniser

- languagetool-core/src/main/java/org/languagetool/rules/AbstractAdvancedSynthesizerFilter.java
- languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/AdvancedSynthesizerFilter.java
- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Fixing FPs like `vê-lo`, `lê-lo`, etc.
> [pt] Fix ACENTUAÇÃO_VOGAL_ÊNCLISE

- languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
- languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
Related to https://github.com/languagetooler-gmbh/languagetool-premium/issues/7072
> [fr] AI_FR_GGEC_TRES_tonetags_test

- languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
- languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
To fix empty suggestion with AI_FR_GGEC_MAIL_JOINED
> [fr] MAIL_JOINED_add-suggestion

- languagetool-language-modules/fr/src/main/java/org/languagetool/language/French.java
- languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
Back to https://github.com/languagetool-org/languagetool/pull/10458
> [fr] revert-mail-changes4

- languagetool-language-modules/pt/src/main/java/org/languagetool/language/Portuguese.java
- languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/disambiguation.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
- languagetool-language-modules/pt/src/test/java/org/languagetool/tagging/pt/PortugueseTaggerTest.java
- pom.xml
Just stuff I've noticed. None of this is particularly frequent, but still. Pretty much all of them are issues with rules that used to ignore enclitic forms (or, worse, that relied on the old tagging schema).
> [pt] Add sundry pronoun fixes

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
Adding words from the Grafana Dashboard.
Also goes with https://github.com/languagetooler-gmbh/languagetool-premium-modules/pull/1325
> [fr] Dic addition from Grafana dictionary dashboard

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have fixed a FP in the rule after seeing the nightly results:
https://internal1.languagetool.org/regression-tests/via-http/2024-04-10/pt-PT/result_style_SER_CONSISTIR_RESIDIR%5B1%5D.html
I know both of you are terribly busy with the new verbs scheme, so now I will work on other rules during the weekend, when I will also try to add words to the dictionaries.
❤️
> [pt] Fixed FP in rule ID:SER_CONSISTIR_RESIDIR

- languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/remote-rule-filters.xml
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7111
> [fr] AI_FR_GGEC_URLs2

- languagetool-core/src/main/java/org/languagetool/JLanguageTool.java
Adding rules and subrules.
Related to: https://github.com/languagetooler-gmbh/languagetool-premium/issues/6964
> [fr] isRuleActiveForLanguageWithModel-new-IDs

- languagetool-language-modules/pt/src/main/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRule.java
- languagetool-language-modules/pt/src/test/java/org/languagetool/JLanguageToolTest.java
Not entirely sure why it only started happening this week, since this logic is already a few months old, but it's never too late to fix it, I suppose.
> [pt] Fix logic issue with compounds in speller

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
Also to fix and close: https://github.com/languagetooler-gmbh/languagetool-premium/issues/7054
> [fr] grammalecte disables

- languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/multiwords.txt
See issue [#7113](https://github.com/languagetooler-gmbh/languagetool-premium/issues/7113)
> [es] add names to multiwords.txt

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
It is just an antipattern to fix FPs.
> [pt-PT] Added AP to rule ID:FORMAL_T-V_DISTINCTION

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Both these rules have zero hits.
Thanks!
> [pt] Removed 'temp_off' from rule ID:FICAR_PARADO_TEMPO_ESTAGNAR and rule ID:APAGAR_INDELÉVEL

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
I was revising my thesis with the LibreOffice add-on and spotted a FP (all rules turned on).
Then, after I already had a solution (AP) planned, I noticed that the rule was “temp_off”, nevertheless, here is an AP for it.
> [pt] Added AP to rule ID:CONCORDANCIA_DETERMINANTES_MASCULINOS

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
In the context of https://github.com/languagetooler-gmbh/languagetool-premium/issues/5240 and adding words from diff FR_SPELLING_RULE and Grafana dictionary dashboard.
> [fr] Dic addition

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Another antipattern to fix FPs.
> [pt] Added AP to rule ID:GENERAL_GENDER_AGREEMENT_ERRORS

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt
https://dictionary.cambridge.org/dictionary/english/neutral
https://www.merriam-webster.com/dictionary/neutral (example 3)
> [en] Add neutral/NNU

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/disambiguation.xml
https://languagetooler.slack.com/archives/CG7ULA9T6/p1716797163756859
> [en] add disambiguation rule

- build.sh
Some basic script syntax improvements.
> modernize and improve build.sh

- languagetool-language-modules/fr/src/test/java/org/languagetool/JLanguageToolTest.java
Simply adding a test for match-merging
> [fr] adding a java test for match-merging

- languagetool-language-modules/en/src/main/resources/org/languagetool/resource/en/added.txt
https://www.merriam-webster.com/dictionary/cold
https://www.ldoceonline.com/dictionary/cold
> [en] Add POS for 'cold'

- languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/hunspell/spelling.txt
> [de] Add Spellling

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya,
@susanaboatto 
After some hours of rest, here is the same pull request but in pt-PT.
Thanks!
> [pt-PT] Moved pull request from PT to PT-PT ID:DIFICULDADES_PROVAÇÕES

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have improved the rule.
It only has two hits in 900 000 sentences, so it is a very-low impact rule.
> [pt-PT] Improved rule ID:PÔR_FIM_À_VIDA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Here is an enhanced version of the rule.
Now it deals with all or most cases encountered.
Like Pedro said, for pt-PT rules, I just need to press the “merge” button after the rules pass the checks.
> [pt-PT] Replaced rule ID:PÔR_FIM_À_VIDA with ID:PÔR_FIM_TERMO

- languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar-l2-de.xml
Reverts languagetool-org/languagetool#10700
> Revert "[en] added rule {und=>and}"

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have rewritten partially this rule.
It is now more powerful.
❤️ ❤️ ❤️ ❤️ ❤️ ❤️
> [pt] Rewrote part of rule ID:BÁSICO_ELEMENTAR

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have rewritten the rule!
Half the size and more powerful.
😛 😛 😛 😛 😛 😛 😛
> [pt] Rewrote rule ID:QUE_TER_COMO_POR_NOME_ADJ

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Another pt-PT rule rewritten.
Like Pedro said, after it passes the tests, I will press merge.
Thanks!
> [pt-PT] Rewrote rule ID:TIVER_ESTIVER

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Not much to say.
I just updated both the licence texts in grammar.xml and style.xml (pt-PT) with the licence in style.xml and improved some text.
After it passes the tests, I will merge it since it is pt-PT.
> [pt-PT] Updated the licence of grammar.xml and style.xml to match the most up-to-date

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Improved rule ID:CIENTÍFICO_DETERMINADAS_ESPECÍFICAS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
It seems to be working.
pt-PT, will press the merge button after it passes the checks.
> [pt-PT] Imported entities to grammar.xml and style.xml and fixed the rules issues

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have completely rewritten this rule.
Since it is pt-PT, I will merge it after it passes the tests.
Thanks!
> [pt-PT] Completely rewrote rule ID:SIMPLIFICAR_A_XXX_DE_VOCÊS

- languagetool-language-modules/fr/src/main/java/org/languagetool/rules/fr/GrammalecteRule.java
See https://app.asana.com/0/1205948788428908/1207814220653799/f.
> [fr] Disabling g0__virg_virgule_après_point__b1_a1_1

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Here is a nice academic/scientific rule.
Thanks!
> [pt] Added rule ID:MUITO_BASTANTE_EXTENSIVAMENTE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Heya, @susanaboatto  and @p-goulart ,
I have removed FPs in the rule.
Since it is pt-PT, after it passes the checks, I will merge it.
Thanks!
> [pt-PT] Removed FPs in rule ID:SIMPLIFICAR_A_XXX_DE_VOCÊS

- languagetool-core/src/main/resources/org/languagetool/resource/spelling_global.txt
Adding Carlo Acutis (seen in the users additions)
https://en.wikipedia.org/wiki/Carlo_Acutis
and
[Carlo Acutis and 14 Blesseds approved for canonization](https://www.vaticannews.va/en/pope/news/2024-07/consistory-cardinals-carlo-acutis-martyrs-canonization.html#:~:text=Pope%20Francis%20presides%20at%20an,to%20be%20made%20a%20saint.&text=The%20College%20of%20Cardinals%20gathered,for%20an%20Ordinary%20Public%20Consistory.)
> [all] Carlo Acutis

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Hello @p-goulart and @susanaboatto ,
I replaced all the pleonasm messages with the entity.
Thanks!
> [pt-PT] Replaced all pleonasm messages with entity

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have improved this pt-PT rule.
I will merge it after the checks.
> [pt-PT] Improved rule ID:FAZER_DESPORTO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have rewritten the rule, and now it finally has hits (useful).
> [pt-PT] Rewrote rule ID:SIMPLIFICAR_É_NECESSÁRIO_TER_REQUER

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have rewritten the rule, but it still shows zero hits tested against the corpus.
Since it is pt-PT, I will merge it after it passes the checks.
> [pt-PT] Rewrote rule ID:PERANTE_O_MESMO_IDENTICO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have been delaying this change since it required a clear mind to do it.
Today I was able to focus on it.
So, I created a SHORTEN_IT category, moved the FORMAL category to the same order as the PT style.xml and added to the redundancy category "Pleonasmos".
Notice that as I slowly improve the rules, I will remove the useless commented out text.
After months of delay, I have done it!
After the checks, I will merge it.
> [pt-PT] style.xml, created SHORTEN_IT category, moved rules around, etc.

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Improved rule ID:AVIÃO_DE_COMBATE_PT_PT

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Just some small cleaning in the rule.
> [pt-PT] Just some cleaning in rule ID:SIMPLIFICAR_DE_VOCÊS_VOSSA_VOSSAS_VOSSO_VOSSOS

- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/added.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/hunspell/spelling.txt
- languagetool-language-modules/fr/src/main/resources/org/languagetool/resource/fr/multiwords.txt
See https://app.asana.com/0/1205948788428908/1207821748298280/f
> [fr] Adding words

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Hello @susanaboatto and @p-goulart 
I have rewritten the rule!
I will merge it after it passes the checks.
> [pt-PT] Rewrote rule ID:QUE_SE_VERBO_PART_PASSADO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Fixed FPs in rule ID:SIMPLIFICAR_QUE_VERBO_A_VERBOINFINITIVO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have removed the “temp_off” from pt-PT rules.
😛 😛 😛 😛 😛 😛 😛 😛
> [pt-PT] Removed "temp_off" from rules

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
I have moved this rule to the proper category.
> [pt-PT] Moved rule to proper category, ID:VERBO_SER_ÚTIL_PARA_SERVIR_PARA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
Just improved the category name to make it look better in the LibreOffice extension.
> [pt-PT] Improved category name for LibreOffice extension

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Improved rule ID:GRANDES_ENORMES_RECURSOS_FINANCEIROS_AVULTADOS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
ahhh... I hope it to be the last enhancement to the rule.
> [pt-PT] Last improvement (I hope) in rule ID:GRANDES_ENORMES_RECURSOS_FINANCEIROS_AVULTADOS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Hello!
I have removed the "temp_off", the rule has zero hits.
> [pt-PT] Removed "temp_off" from rule ID:GRANDES_ENORMES_RECURSOS_FINANCEIROS_AVULTADOS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Just moved it to the formal category.
> [pt-PT] Moved to formal rule ID:PÔR_FIM_TERMO

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Moved to formal rule ID:TIVER_ESTIVER

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Improved rules:CIENTÍFICO_MAIS_IMPORTANTE_CHAVE_V3 and HABILITAÇÕES_LITERÁRIAS_ACADÉMICAS

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
A pre language agreement rule.
> [pt-PT] Added rule ID:AO45_HAVER_DE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
> [pt-PT] Removed "temp_off" from rule ID:AO45_HAVER_DE

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
> [pt-PT] Added informal rule to rulegroup ID:INFORMALITIES

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
Just an antipattern to fix false positives.
> [pt-PT] Added AP to rule ID:VERBO_HIFENIZADOR_VERBOS_2

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Antipatterns that remove tons of false positives.
> [pt-PT] Added APs to rule ID:VERBO_PARA_PRONOME_PESSOAL

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
I have improved the antipattern to remove more false positives.
> [pt] Improved AP in rule ID:SIMPLIFICAR_IR_E_PARA

- languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
This should hopefully remove all false positives.
Thanks!
> [pt] Fixed FPs in rule ID:OS_DOIS_AS_DUAS_AMBOS_AMBAS

- languagetool-language-modules/ja/src/main/resources/org/languagetool/rules/ja/grammar.xml
Hi!
I am excited to start contributing to this project. As my first step, I have added a new rule to the Japanese language section, as I am Japanese. I plan to continue adding more rules when I find the time to do so. Please let me know if there are any issues 🙂
> [ja] add new rules ZUTUUGAITAI
